import React, { useEffect, useRef, useState } from 'react';
import { NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { ArrowDown, ArrowRight, ArrowUp, ArrowUpRight, BookOpen, CalendarDays, Check, ChevronLeft, ChevronRight, Compass, Menu, Pencil, Plus, Search, UserRound, X } from 'lucide-react';
import { StudyActivity } from '../StudyActivity';
import { nextMonday } from '../state';
import { configKey, contentNote, credentialsFor, faculties, majorLabel, majorProfiles, pathById, paths, relation, stagesFor, trackById, tracks, type Source, type Stage } from './fixtures';
import './prototype.css';

// Deliberately isolated review data. Do not reuse this storage model as the production architecture.
const STORAGE = 'majorweave.design.v2';
type Draft = { selected: string[]; known: string[]; sources: Record<string,string>; goal: string; hours: number; start: string };
type Task = { id: string; title: string; stage: string; stageId: string; minutes: number; week: number; day: number; url: string; notes: string; completedAt?: string };
type ClosedWeek = { week: number; total: number; done: number; minutes: number; closedAt: string };
type Plan = { id: string; name: string; path: string; track: string; goal: string; hours: number; start: string; tasks: Task[]; closed: ClosedWeek[] };
type State = { name: string; major: string; path: string; track: string; drafts: Record<string,Draft>; plans: Plan[]; active: string; bookmarks: string[] };
const defaults = (): State => ({ name: '', major: 'software', path: 'backend', track: 'node', drafts: {}, plans: [], active: '', bookmarks: [] });
function load(): State {
  try {
    const saved = JSON.parse(localStorage.getItem(STORAGE) || 'null');
    if (!saved || !paths.some(p => p.id === saved.path) || !tracks[saved.path].some(t => t.id === saved.track) || !Array.isArray(saved.plans) || !saved.drafts || !Array.isArray(saved.bookmarks)) return defaults();
    return { ...defaults(), ...saved, plans: saved.plans.filter((p: Plan) => paths.some(path => path.id === p.path) && tracks[p.path].some(t => t.id === p.track) && Array.isArray(p.tasks) && Array.isArray(p.closed)) };
  } catch { return defaults(); }
}
const minutesText = (minutes: number) => minutes < 60 ? `${minutes} phút` : `${Number((minutes / 60).toFixed(1))} giờ`;
const dateAt = (start: string, offset: number) => { const date = new Date(`${start}T12:00:00`); date.setDate(date.getDate() + offset); return date; };
const dateText = (date: Date) => date.toLocaleDateString('vi-VN', { day: '2-digit', month: '2-digit' });
const normal = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/g, 'd').toLowerCase();

function External({ href, children, className = '' }: { href: string; children: React.ReactNode; className?: string }) {
  return <a href={href} target="_blank" rel="noreferrer" className={`external ${className}`}>{children}<ArrowUpRight size={16} aria-hidden="true" /></a>;
}
function Modal({ title, children, onClose, wide = false }: { title: string; children: React.ReactNode; onClose: () => void; wide?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null);
  const titleId = React.useId();
  useEffect(() => { ref.current?.showModal(); const dialog = ref.current; return () => dialog?.close(); }, []);
  return <dialog ref={ref} className={`p-modal ${wide ? 'wide' : ''}`} aria-labelledby={titleId} onCancel={event => { event.preventDefault(); onClose(); }} onClick={event => { if (event.target === ref.current) { const r = ref.current!.getBoundingClientRect(); if (event.clientX < r.left || event.clientX > r.right || event.clientY < r.top || event.clientY > r.bottom) onClose(); } }}>
    <div className="modal-head"><div><span className="eyebrow">MAJORWEAVE</span><h2 id={titleId}>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Đóng"><X size={22}/></button></div>{children}
  </dialog>;
}
function Empty({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) { return <div className="empty"><span className="empty-mark" aria-hidden="true">○</span><h2>{title}</h2><p>{children}</p>{action}</div>; }
function Heading({ eyebrow, title, emphasis, children, side }: { eyebrow: string; title: string; emphasis: string; children: React.ReactNode; side?: React.ReactNode }) {
  return <header className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title} <em>{emphasis}</em><span className="rust">.</span></h1><p>{children}</p></div>{side}</header>;
}

export default function Prototype() {
  const navigate = useNavigate();
  const location = useLocation();
  const [state, setState] = useState<State>(load);
  const [saveError, setSaveError] = useState('');
  const [toast, setToast] = useState('');
  const [menu, setMenu] = useState(false);
  const [account, setAccount] = useState(false);
  const [stageOpen, setStageOpen] = useState<Stage|null>(null);
  const [rebuild, setRebuild] = useState(false);
  const [week, setWeek] = useState(0);
  const [planTab, setPlanTab] = useState('plan');
  const [editing, setEditing] = useState<Task|null>(null);
  const [endWeek, setEndWeek] = useState(false);
  const [endingChoice, setEndingChoice] = useState('move');
  const [detailTab, setDetailTab] = useState('roadmap');
  const [exploreQuery,setExploreQuery] = useState('');
  const [faculty,setFaculty] = useState('all');
  const [category,setCategory] = useState('all');
  const [sourceQuery,setSourceQuery] = useState('');
  const [sourceLanguage,setSourceLanguage] = useState('all');
  const [freeSources,setFreeSources] = useState(false);
  const [dayFilter,setDayFilter] = useState(-1);
  const [stageFilter,setStageFilter] = useState('all');
  const [profileName,setProfileName] = useState(state.name);
  const [profileMajor,setProfileMajor] = useState(state.major);
  const [editingNew,setEditingNew] = useState(false);
  const [reviewState,setReviewState] = useState('ready');
  const path = pathById(state.path);
  const branch = trackById(state.path, state.track);
  const stages = stagesFor(state.path, state.track);
  const key = configKey(state.path, state.track);
  const draft: Draft = state.drafts[key] || { selected: stages.filter(s => !s.optional).map(s => s.id), known: [], sources: {}, goal: stages.at(-1)?.outcome || 'Hoàn thành một dự án thực hành', hours: 5, start: nextMonday() };
  const plan = state.plans.find(p => p.id === state.active) || state.plans[0];
  const nav = [{ url: '/explore', label: 'Explore', icon: Compass }, { url: '/path', label: 'Path detail', icon: BookOpen }, { url: '/roadmap', label: 'My roadmap', icon: ArrowRight }, { url: '/plan', label: 'My plan', icon: CalendarDays }, { url: '/profile', label: 'Profile', icon: UserRound }];
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 3500); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { window.scrollTo(0,0); }, [location.pathname]);
  useEffect(() => { if(location.pathname === '/profile'){setProfileName(state.name);setProfileMajor(state.major);} }, [location.pathname,state.name,state.major]);
  function save(next: State) { try { localStorage.setItem(STORAGE, JSON.stringify(next)); setState(next); setSaveError(''); return true; } catch { setSaveError('Chưa lưu được thay đổi. Dữ liệu hiện tại vẫn được giữ; kiểm tra dung lượng hoặc quyền lưu của trình duyệt rồi thử lại.'); return false; } }
  const patch = (value: Partial<State>) => save({ ...state, ...value });
  const patchDraft = (value: Partial<Draft>) => patch({ drafts: { ...state.drafts, [key]: { ...draft, ...value } } });
  function choosePath(id: string) { patch({ path: id, track: tracks[id][0].id }); setDetailTab('roadmap'); navigate('/path'); }
  function chooseTrack(id: string) { if (patch({ track: id })) { setStageOpen(null); setToast('Đã đổi nhánh khám phá. Các kế hoạch đã lưu được giữ nguyên.'); } }
  const selectedSource = (s: Stage) => s.sources.find(r => r.id === draft.sources[s.id]) || s.sources[0];
  function toggleStage(id: string) { patchDraft({ selected: draft.selected.includes(id) ? draft.selected.filter(s => s !== id) : [...draft.selected,id] }); }
  function toggleKnown(id: string) { patchDraft({ known: draft.known.includes(id) ? draft.known.filter(s => s !== id) : [...draft.known,id] }); }
  function moveStage(id: string, delta: number) { const ordered = [...draft.selected]; const i = ordered.indexOf(id); const j = i + delta; if (i < 0 || j < 0 || j >= ordered.length) return; [ordered[i],ordered[j]] = [ordered[j],ordered[i]]; patchDraft({ selected: ordered }); }
  function createPlan(replace = false) {
    if (!draft.goal.trim() || !Number.isFinite(draft.hours) || draft.hours < 0.5 || draft.hours > 40 || !/^\d{4}-\d{2}-\d{2}$/.test(draft.start) || !Number.isFinite(new Date(draft.start).getTime())) { setToast('Kiểm tra mục tiêu, ngày bắt đầu và quỹ giờ từ 0,5 đến 40 giờ/tuần.'); return; }
    const toLearn = draft.selected.map(id => stages.find(s => s.id === id)).filter((s): s is Stage => !!s && !draft.known.includes(s.id));
    if (!toLearn.length) { setToast('Chọn ít nhất một chặng cần học trước khi tạo kế hoạch.'); return; }
    const budget = Math.round(draft.hours * 60);
    const tasks: Task[] = []; let plannedWeek = 0; let used = 0;
    for (const s of toLearn) for (let index = 0; index < s.tasks.length; index++) {
      const t = s.tasks[index]; const count = Math.ceil(t.minutes / budget);
      for (let part = 0; part < count; part++) {
        const mins = Math.min(budget, t.minutes - part * budget);
        if (used && used + mins > budget) { plannedWeek++; used = 0; }
        const id = `${key}/${s.id}/${index}/${part}`;
        const old = replace && plan?.path === state.path && plan?.track === state.track ? plan.tasks.find(item => item.id === id) : undefined;
        tasks.push({ id, stage: s.title, stageId: s.id, title: `${t.title}${count > 1 ? ` (${part + 1}/${count})` : ''}`, minutes: mins, week: plannedWeek, day: Math.min(6,Math.floor(used / Math.max(1,budget / 5))), url: selectedSource(s)?.url || '', notes: old?.notes || '', completedAt: old?.completedAt }); used += mins;
      }
    }
    const next: Plan = { id: replace && plan ? plan.id : crypto.randomUUID(), name: `${path.name} · ${branch.name}`, path: state.path, track: state.track, goal: draft.goal.trim(), hours: draft.hours, start: draft.start, tasks, closed: [] };
    const plans = replace && plan ? state.plans.map(p => p.id === plan.id ? next : p) : [...state.plans,next];
    if (patch({ plans, active: next.id })) { setWeek(0); setPlanTab('plan'); setRebuild(false); setToast('Kế hoạch đã sẵn sàng. Mỗi tuần, một bước nhỏ.'); navigate('/plan'); }
  }
  function patchPlan(value: Partial<Plan>) { return plan ? patch({ plans: state.plans.map(p => p.id === plan.id ? { ...p,...value } : p) }) : false; }
  function patchTask(task: Task) { return plan ? patchPlan({ tasks: plan.tasks.map(t => t.id === task.id ? task : t) }) : false; }
  function closeWeek() {
    if (!plan) return;
    const items = plan.tasks.filter(t => t.week === week);
    if (plan.closed.some(c => c.week === week)) return;
    let nextOpenWeek = week + 1;
    while (plan.closed.some(c => c.week === nextOpenWeek)) nextOpenWeek++;
    const tasks = plan.tasks.flatMap(t => t.week !== week || t.completedAt ? [t] : endingChoice === 'drop' ? [] : [{ ...t, week: nextOpenWeek }]);
    const snapshot: ClosedWeek = { week, total: items.length, done: items.filter(t => t.completedAt).length, minutes: items.filter(t => t.completedAt).reduce((n,t) => n + t.minutes,0), closedAt: new Date().toISOString() };
    if (patchPlan({ tasks, closed: [...plan.closed.filter(c => c.week !== week),snapshot] })) { setEndWeek(false); setToast('Đã kết thúc tuần và lưu kết quả.'); setPlanTab('weeks'); }
  }

  function TrackPicker() {
    return <section className="branch-picker"><div><span className="eyebrow">CHOOSE YOUR TOOLS</span><h2>{state.path === 'fullstack' ? 'Hai lựa chọn. Một ứng dụng.' : 'Chọn cách bạn muốn bắt đầu.'}</h2><p>Nền tảng chung được giữ lại; các chặng riêng đi theo lựa chọn của bạn.</p></div>
      {state.path === 'fullstack' ? <div className="form-row"><label>Nhánh Frontend<select value={state.track.split('-')[0]} onChange={e => chooseTrack(`${e.target.value}-${state.track.split('-')[1]}`)}>{tracks.frontend.map(t => <option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Nhánh Backend<select value={state.track.split('-')[1]} onChange={e => chooseTrack(`${state.track.split('-')[0]}-${e.target.value}`)}>{tracks.backend.map(t => <option value={t.id} key={t.id}>{t.name}</option>)}</select></label></div> : <div className={`branch-options ${tracks[state.path].length === 4 ? 'four' : ''}`}>{tracks[state.path].map(t => <button key={t.id} className={`branch-option ${t.id === state.track ? 'selected' : ''}`} aria-pressed={t.id === state.track} onClick={() => chooseTrack(t.id)}><span className="choice-circle" aria-hidden="true">{t.id === state.track ? <Check size={12}/> : null}</span><strong>{t.name}</strong><small>{t.tools}</small></button>)}</div>}
      {state.path === 'frontend' && <p className="branch-footnote">HTML → CSS → JavaScript trước. Vite là công cụ build, không phải nhánh thay thế framework.</p>}
    </section>;
  }
  function SourceCard({ s, stage }: { s: Source; stage?: Stage }) {
    const chosen = stage && selectedSource(stage)?.id === s.id;
    return <article key={s.id} className="source-card"><div className="source-top"><span className="eyebrow">{s.provider}</span><span className="pill">{s.cost}</span></div><h3>{s.title}</h3><p>{s.note}</p><div className="source-meta">{s.language === 'vi' ? 'Tiếng Việt' : 'English'} · {s.format}</div><div className="source-actions"><External href={s.url}>Mở nguồn học</External>{stage && <button className={chosen ? 'text-button selected' : 'text-button'} onClick={() => { if (patchDraft({ sources: { ...draft.sources,[stage.id]: s.id } })) setToast('Đã chọn nguồn cho chặng học.'); }}>{chosen ? <><Check size={15}/>Đang chọn</> : 'Chọn nguồn này'}</button>}</div></article>;
  }

  function Explore() {
    const query = exploreQuery; const setQuery = setExploreQuery;
    const visible = paths.filter(p => (category === 'all' || p.category === category) && normal(`${p.name} ${p.tags.join(' ')} ${p.summary}`).includes(normal(query)) && (faculty === 'all' || faculties.find(f => f.id === faculty)!.majors.some(m => relation(p,m.id) > 0))).sort((a,b) => relation(b,state.major) - relation(a,state.major));
    return <div className="page explore-page"><Heading eyebrow="EXPLORE. LEARN. GROW." title="One major." emphasis="Many possibilities" side={<div className="major-paper"><span className="eyebrow">YOUR STARTING POINT</span><label>Ngành bạn đang học<select value={state.major} onChange={e => patch({ major: e.target.value })}><option value="">Chưa chọn ngành</option>{faculties.map(f => <optgroup key={f.id} label={f.name}>{f.majors.map(m => <option value={m.id} key={m.id}>{m.name}</option>)}</optgroup>)}</select></label><p>Ngành học là điểm bắt đầu.<br/>Bạn được khám phá mọi hướng.</p><span className="paper-rule"/><small>{state.major === 'chip' ? 'Khám phá nhóm Kỹ thuật Máy tính / Thiết kế Vi mạch' : 'Dệt nên một lộ trình của riêng bạn.'}</small></div>}>Bắt đầu từ điều bạn đang học, hoặc một hướng bạn tò mò.<br/>Chọn nguồn học rồi dành thời gian cho từng bước nhỏ.</Heading>
      {state.major === 'chip' && <div className="notice">Nhóm Kỹ thuật Máy tính / Thiết kế Vi mạch chỉ gợi ý hướng phần mềm và hạ tầng có roadmap phù hợp. Đây chưa phải lộ trình nghề vi mạch. <External href={majorProfiles.chip.sourceUrl}>Thông tin ngành UIT</External></div>}
      <div className="explore-toolbar"><label className="search-field"><Search size={19}/><input aria-label="Tìm hướng học" value={query} onChange={e => setQuery(e.target.value)} placeholder="Tìm hướng, kỹ năng hoặc điều bạn tò mò…"/></label><label className="faculty-filter">Khám phá theo khoa<select aria-label="Khám phá theo khoa" value={faculty} onChange={e => setFaculty(e.target.value)}><option value="all">Tất cả các khoa</option>{faculties.map(f => <option key={f.id} value={f.id}>{f.id === 'ce' ? 'Kỹ thuật Máy tính / Thiết kế Vi mạch' : f.name}</option>)}</select></label></div>
      <div className="filter-row"><div className="filter-tabs" aria-label="Nhóm hướng">{[['all','Tất cả'],['SOFTWARE','Phần mềm'],['DATA','Dữ liệu'],['AI','AI'],['INFRASTRUCTURE','Hạ tầng'],['SECURITY','Bảo mật'],['DESIGN','Thiết kế'],['BUSINESS','Nghiệp vụ']].map(([id,label]) => <button key={id} className={category === id ? 'active' : ''} aria-pressed={category === id} onClick={() => setCategory(id)}>{label}</button>)}</div><span className="result-count">{visible.length} hướng khám phá</span></div>
      <div className="relation-legend"><span><i className="dot sage"/>Gần nền tảng ngành</span><span><i className="dot rust"/>Hướng mở rộng</span><span>Liên hệ do nhóm đề xuất · Bạn vẫn có thể chọn mọi hướng</span></div>
      {visible.length ? <div className="path-grid">{visible.map((p,index) => <article className="path-card" key={p.id}><div className="path-card-top"><span className="eyebrow">{p.category}</span><span className="path-number">{String(index + 1).padStart(2,'0')}</span></div><h2>{p.name}</h2><p>{p.summary}</p><div className="tags">{p.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="path-card-bottom"><span className={`relation-label r${relation(p,state.major)}`}>{relation(p,state.major) === 2 ? 'Gần nền tảng ngành' : relation(p,state.major) === 1 ? 'Hướng mở rộng' : 'Khám phá tự do'}</span><button className="circle-button" aria-label={`Khám phá ${p.name}`} onClick={() => choosePath(p.id)}><ArrowUpRight size={22}/></button></div></article>)}</div> : <Empty title="Chưa tìm thấy hướng này." action={<button className="secondary" onClick={() => { setQuery('');setFaculty('all');setCategory('all'); }}>Xóa bộ lọc</button>}>Thử tên khác hoặc mở rộng nhóm/khoa đang chọn.</Empty>}
      <div className="page-footnote">Một hướng có thể thuộc nhiều ngành. Roadmap giúp bạn khám phá và tổ chức tự học; không phải bài đánh giá năng lực nghề nghiệp.</div>
    </div>;
  }

  function PathDetail() {
    const query = sourceQuery; const setQuery = setSourceQuery; const language = sourceLanguage; const setLanguage = setSourceLanguage; const free = freeSources; const setFree = setFreeSources;
    const allSources = [...new Map(stages.flatMap(s => s.sources).map(s => [s.id,s])).values()];
    const filtered = allSources.filter(s => normal(`${s.title} ${s.provider}`).includes(normal(query)) && (language === 'all' || s.language === language) && (!free || s.cost === 'Miễn phí'));
    const credentials = credentialsFor(state.path,state.track);
    return <div className="page"><Heading eyebrow="A DIRECTION WORTH EXPLORING" title={path.name.replace(/ (Developer|Engineer|Analyst|Design)$/,'')} emphasis={path.name.match(/ (Developer|Engineer|Analyst|Design)$/)?.[1] || 'your way'} side={<div className="heading-aside"><span className="eyebrow">YOUR CHOICE</span><strong>{branch.name}</strong><span>{branch.tools}</span></div>}>{path.summary}</Heading>
      <div className="roadmap-reference"><div><span className="eyebrow">THE BIGGER PICTURE</span><h2>Roadmap tham khảo</h2><p>Mở bản đồ tổng quan, rồi quay lại chọn chặng muốn học.</p></div><div className="reference-links">{path.roadmaps.map(link => <External key={link.url} href={link.url} className="secondary">{link.label}</External>)}{branch.reference && !path.roadmaps.some(l => l.url === branch.reference) && <External href={branch.reference} className="secondary">{branch.name} trên roadmap.sh</External>}</div></div>
      {TrackPicker()}
      <p className="prototype-content-note">{contentNote(state.path)}</p>
      <div className="content-tabs" role="tablist" aria-label="Nội dung hướng học">{[['roadmap','Roadmap',stages.length],['resources','Nguồn học',allSources.length],['credentials','Mục tiêu bổ trợ',credentials.length]].map(([id,label,count]) => <button role="tab" key={id} aria-selected={detailTab === id} className={detailTab === id ? 'active' : ''} onClick={() => setDetailTab(String(id))}>{label}<span>{count}</span></button>)}</div>
      {detailTab === 'roadmap' && <div className="roadmap-layout"><div className="stage-list">{stages.map((s,index) => <article key={s.id} className={`stage-row ${draft.known.includes(s.id) ? 'known' : ''}`}><span className="stage-index">{String(index + 1).padStart(2,'0')}</span><button className="stage-copy" onClick={() => setStageOpen(s)}><span className="eyebrow">{s.phase}</span><h3>{s.title}</h3><p>{s.outcome}</p><span className="stage-meta">{s.sources.length} nguồn · {minutesText(s.tasks.reduce((sum,t) => sum + t.minutes,0))} thực hành {s.optional ? '· Chọn thêm' : ''}</span></button><div className="stage-row-actions"><span className={`pill ${draft.known.includes(s.id) ? 'sage' : ''}`}>{draft.known.includes(s.id) ? 'Đã biết' : draft.selected.includes(s.id) ? 'Trong roadmap' : 'Chưa chọn'}</span><button className="icon-button" aria-label={`Xem ${s.title}`} onClick={() => setStageOpen(s)}><ArrowUpRight size={21}/></button></div></article>)}</div><aside className="roadmap-side"><span className="eyebrow">A PLACE TO START</span><h2>Học theo<br/><em>nhịp của bạn.</em></h2><p>Chọn những chặng cần học và một nguồn phù hợp cho mỗi chặng.</p><div className="side-stat"><strong>{draft.selected.filter(id => !draft.known.includes(id)).length}</strong><span>chặng cần học</span></div><button className="primary" onClick={() => navigate('/roadmap')}>Tùy chỉnh roadmap <ArrowRight size={17}/></button><p className="small-note">Không cần học lại điều đã biết. Bạn có thể chỉnh từng chặng.</p></aside></div>}
      {detailTab === 'resources' && <><div className="resource-toolbar"><label className="search-field"><Search size={18}/><input aria-label="Tìm nguồn học" value={query} onChange={e => setQuery(e.target.value)} placeholder="Tìm tên nguồn hoặc đơn vị cung cấp…"/></label><select aria-label="Ngôn ngữ tài liệu" value={language} onChange={e => setLanguage(e.target.value)}><option value="all">Mọi ngôn ngữ tài liệu</option><option value="vi">Tiếng Việt</option><option value="en">English</option></select><label className="inline-check"><input type="checkbox" checked={free} onChange={e => setFree(e.target.checked)}/>Miễn phí</label></div>{filtered.length ? <div className="source-grid">{filtered.map(s => SourceCard({s}))}</div> : <Empty title="Chưa có nguồn khớp bộ lọc." action={<button className="secondary" onClick={() => {setQuery('');setLanguage('all');setFree(false);}}>Xóa bộ lọc nguồn</button>}>Thử ngôn ngữ khác hoặc xem lại lựa chọn miễn phí.</Empty>}</>}
      {detailTab === 'credentials' && <><p className="section-intro">Chứng nhận, chứng chỉ và portfolio là những mục tiêu bổ trợ. Website không cấp hoặc xác minh chứng chỉ.</p>{credentials.length ? <div className="source-grid">{credentials.map(c => <article className="source-card" key={c.id}><span className="eyebrow">{c.provider}</span><h3>{c.name}</h3><span className="pill">{c.type}</span><p>{c.note}</p><div className="source-actions"><External href={c.url}>Điều kiện chính thức</External><button className="text-button" onClick={() => { const selected = state.bookmarks.includes(c.id); if (patch({ bookmarks: selected ? state.bookmarks.filter(id => id !== c.id) : [...state.bookmarks,c.id] })) setToast(selected ? 'Đã bỏ lưu mục tiêu.' : 'Đã lưu mục tiêu bổ trợ.'); }}>{state.bookmarks.includes(c.id) ? <><Check size={15}/>Đã lưu</> : 'Lưu mục tiêu'}</button></div></article>)}</div> : <Empty title="Bắt đầu bằng một sản phẩm của bạn." action={<button className="secondary" onClick={() => navigate('/roadmap')}>Đặt mục tiêu thực hành <ArrowRight size={16}/></button>}>Danh sách chứng nhận của hướng này đang được biên soạn. Bạn có thể dùng bài thực hành cuối làm mục tiêu portfolio.</Empty>}</>}
    </div>;
  }

  function MyRoadmap() {
    const ordered = draft.selected.map(id => stages.find(s => s.id === id)).filter((s): s is Stage => !!s);
    const total = ordered.filter(s => !draft.known.includes(s.id)).reduce((sum,s) => sum + s.tasks.reduce((n,t) => n + t.minutes,0),0);
    let estimate = total > 0 && Number.isFinite(draft.hours) && draft.hours > 0 ? 1 : 0;
    if (estimate) {
      const budget = Math.round(draft.hours * 60); let used = 0;
      for (const s of ordered.filter(s => !draft.known.includes(s.id))) for (const t of s.tasks) {
        for (let remaining = t.minutes; remaining > 0; remaining -= budget) {
          const minutes = Math.min(budget,remaining);
          if (used && used + minutes > budget) {estimate++;used=0;} used+=minutes;
        }
      }
    }
    return <div className="page"><Heading eyebrow="MAKE IT YOUR OWN" title="Your path." emphasis="Your pace" side={<span className="heading-chip">{path.name} · {branch.name}</span>}>Giữ những điều muốn học, chọn nguồn phù hợp và dành một quỹ thời gian mỗi tuần.</Heading>
      <div className="builder-layout"><section><div className="section-heading"><h2>Các chặng của bạn <span className="count">{ordered.length}</span></h2><button className="text-button" onClick={() => navigate('/path')}>Chọn thêm chặng <Plus size={16}/></button></div>
        {!ordered.length && <Empty title="Roadmap còn trống." action={<button className="secondary" onClick={() => navigate('/path')}>Chọn chặng học</button>}>Mở một chặng từ Path detail để thêm vào roadmap.</Empty>}
        <div className="builder-stages">{ordered.map((s,index) => <article className={`builder-stage ${draft.known.includes(s.id) ? 'known' : ''}`} key={s.id}><div className="builder-stage-heading"><span className="stage-index">{String(index + 1).padStart(2,'0')}</span><button className="text-button stage-title" onClick={() => setStageOpen(s)}>{s.title}</button><label className="inline-check known-check"><input type="checkbox" checked={draft.known.includes(s.id)} onChange={() => toggleKnown(s.id)}/>Đã biết</label><button className="icon-button" onClick={() => toggleStage(s.id)} aria-label={`Bỏ ${s.title}`}><X size={18}/></button></div><p>{s.outcome}</p><div className="builder-stage-bottom"><label>Nguồn đang chọn<select aria-label={`Nguồn cho ${s.title}`} value={selectedSource(s)?.id || ''} onChange={e => patchDraft({ sources: { ...draft.sources,[s.id]: e.target.value } })}>{s.sources.map(r => <option key={r.id} value={r.id}>{r.provider} · {r.title}</option>)}</select></label><div className="reorder"><button className="icon-button" disabled={index === 0} aria-label={`Đưa ${s.title} lên`} onClick={() => moveStage(s.id,-1)}><ArrowUp size={16}/></button><button className="icon-button" disabled={index === ordered.length - 1} aria-label={`Đưa ${s.title} xuống`} onClick={() => moveStage(s.id,1)}><ArrowDown size={16}/></button></div></div></article>)}</div>
      </section><aside className="plan-settings"><span className="eyebrow">MAKE ROOM FOR LEARNING</span><h2>Một tuần.<br/><em>Một bước.</em></h2><form onSubmit={e => { e.preventDefault(); createPlan(); }}><label>Mục tiêu của bạn<input value={draft.goal} maxLength={180} required onChange={e => patchDraft({ goal: e.target.value })}/></label><div className="form-row"><label>Giờ học mỗi tuần<input type="number" min="0.5" max="40" step="0.5" required value={Number.isFinite(draft.hours) ? draft.hours : ''} onChange={e => patchDraft({ hours: e.target.value === '' ? 0 : Number(e.target.value) })}/></label><label>Ngày bắt đầu<input type="date" required value={draft.start} onChange={e => patchDraft({ start: e.target.value })}/></label></div><div className="estimate"><div><strong>{ordered.filter(s => !draft.known.includes(s.id)).length}</strong><span>chặng cần học</span></div><div><strong>{estimate || '—'}</strong><span>tuần dự kiến</span></div></div><p className="small-note">Thời gian dành cho các bài thực hành được chọn, không phải cam kết thành thạo một nghề.</p><button type="submit" className="primary full">Tạo kế hoạch mới <ArrowRight size={17}/></button>{plan && <button type="button" className="secondary full" onClick={() => setRebuild(true)}>Thay kế hoạch đang xem</button>}<p className="settings-note">Kế hoạch mới được lưu riêng. Bạn có thể chuyển giữa các kế hoạch trong My plan.</p></form></aside></div>
    </div>;
  }

  function MyPlan() {
    if (!plan) return <div className="page"><Heading eyebrow="ONE WEEK AT A TIME" title="Make room for" emphasis="progress">Chọn một lộ trình và dành thời gian cho những điều bạn muốn học.</Heading><Empty title="Tuần đầu tiên bắt đầu từ một kế hoạch." action={<button className="primary" onClick={() => navigate('/roadmap')}>Tạo kế hoạch đầu tiên <ArrowRight size={17}/></button>}>Bạn chưa có kế hoạch học. Hãy chọn chặng, nguồn học và quỹ giờ mỗi tuần.</Empty></div>;
    const weekCount = Math.max(0,...plan.tasks.map(t => t.week),...plan.closed.map(c => c.week)) + 1;
    const items = plan.tasks.filter(t => t.week === week);
    const finished = items.filter(t => t.completedAt).length;
    const closed = plan.closed.find(c => c.week === week);
    const total = closed?.total ?? items.length;
    const done = closed?.done ?? finished;
    const percentage = total ? Math.round(done / total * 100) : 0;
    const groups = [...new Set(items.map(t => t.stage))];
    const visible = items.filter(t => (dayFilter === -1 || t.day === dayFilter) && (stageFilter === 'all' || t.stage === stageFilter));
    const newTask = () => { setEditingNew(true); setEditing({ id: `custom-${crypto.randomUUID()}`, title: '', stage: 'Việc của bạn', stageId: 'custom', minutes: 30, week, day: 0, url: '', notes: '' }); };
    const switchPlan = (id: string) => { if(patch({active:id})) {setWeek(0);setDayFilter(-1);setStageFilter('all');} };
    return <div className="page plan-page"><div className="plan-title-row"><div><span className="eyebrow">ONE WEEK AT A TIME</span><h1>Make room for <em>progress.</em></h1></div><label className="plan-select">Kế hoạch đang xem<select aria-label="Kế hoạch đang xem" value={plan.id} onChange={e => switchPlan(e.target.value)}>{state.plans.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label></div>
      <div className="plan-context"><span>{plan.goal}</span><button className="text-button" onClick={() => navigate('/roadmap')}>Thêm kế hoạch <Plus size={15}/></button></div>
      <div className="plan-tabs" role="tablist" aria-label="My plan"><button role="tab" aria-selected={planTab === 'plan'} className={planTab === 'plan' ? 'active' : ''} onClick={() => setPlanTab('plan')}>PLAN</button><button role="tab" aria-selected={planTab === 'stats'} className={planTab === 'stats' ? 'active' : ''} onClick={() => setPlanTab('stats')}>STATS</button><button role="tab" aria-selected={planTab === 'weeks'} className={planTab === 'weeks' ? 'active' : ''} onClick={() => setPlanTab('weeks')}>WEEKS</button></div>
      {planTab === 'plan' && <><div className="week-toolbar"><div className="week-selector"><button className="icon-button" aria-label="Tuần trước" disabled={week === 0} onClick={() => {setWeek(week - 1);setStageFilter('all');}}><ChevronLeft size={22}/></button><div><strong>Tuần {week + 1}</strong><span>{dateText(dateAt(plan.start,week * 7))} — {dateText(dateAt(plan.start,week * 7 + 6))}</span></div><button className="icon-button" aria-label="Tuần tiếp theo" onClick={() => {setWeek(week + 1);setStageFilter('all');}}><ChevronRight size={22}/></button></div><div className="week-actions"><button className="text-button" onClick={() => {setWeek(0);setStageFilter('all');}}>Tuần đầu</button><button className="secondary" disabled={!!closed || !items.length} onClick={() => {setEndingChoice('move');setEndWeek(true);}}>{closed ? 'Đã kết thúc tuần' : 'Kết thúc tuần'}</button></div></div>
        <div className="progress-line"><div className="progress-track"><span style={{width:`${percentage}%`}}/></div><span>{done}/{total} · {percentage}%</span></div><div className="week-message">{closed ? 'Một tuần đã được lưu lại. Tiếp tục với bước kế tiếp.' : done ? 'Những bước nhỏ đang tạo nên tiến độ.' : 'Chừa một chút thời gian cho điều bạn muốn học.'}<span>{closed ? `${minutesText(closed.minutes)} việc hoàn thành` : `${minutesText(items.reduce((n,t) => n + t.minutes,0))} đã lên lịch`}</span></div>{!closed && items.reduce((n,t)=>n+t.minutes,0)>plan.hours*60 && <p className="budget-note">Lịch tuần vượt quỹ {plan.hours} giờ bạn đã đặt. Bạn có thể dời bớt việc hoặc giữ lịch này theo nhu cầu.</p>}
        <div className="weekly-layout"><aside className="project-column"><div className="section-heading"><span className="eyebrow">LEARNING THREADS</span><button className="text-button" onClick={() => setStageFilter('all')}>Tất cả</button></div>{groups.map(group => {const groupItems = items.filter(t => t.stage === group);const n = groupItems.filter(t => t.completedAt).length;return <button key={group} className={`project-card ${stageFilter === group ? 'selected' : ''}`} onClick={() => setStageFilter(stageFilter === group ? 'all' : group)}><strong>{group}</strong><span>{n}/{groupItems.length} việc · {minutesText(groupItems.reduce((sum,t) => sum + t.minutes,0))}</span><span className="mini-progress"><i style={{width:`${n/groupItems.length*100}%`}}/></span></button>;})}<button className="add-project" onClick={() => {if(patch({path:plan.path,track:plan.track}))navigate('/roadmap');}}><Plus size={16}/> ĐIỀU CHỈNH ROADMAP</button><div className="weekly-quote"><span className="eyebrow">YOUR PACE IS ENOUGH</span><p>A little, <em>often.</em></p><span>Chọn ít việc hơn nếu tuần này bận.<br/>Bạn luôn có thể dời một bước.</span></div></aside><section className="daily-column"><div className="section-heading"><div><span className="eyebrow">THIS WEEK</span><h2>{stageFilter === 'all' ? 'Mỗi ngày, một việc nhỏ.' : stageFilter}</h2></div><button className="secondary" onClick={newTask} disabled={!!closed}><Plus size={16}/>Thêm việc</button></div><div className="day-tabs" aria-label="Lọc ngày"><button className={dayFilter === -1 ? 'active' : ''} aria-pressed={dayFilter === -1} onClick={() => setDayFilter(-1)}>Tất cả</button>{Array.from({length:7},(_,day) => <button key={day} className={dayFilter === day ? 'active' : ''} aria-pressed={dayFilter === day} onClick={() => setDayFilter(day)}>{dateAt(plan.start,week * 7 + day).toLocaleDateString('vi-VN',{weekday:'short'})}<span>{items.filter(t => t.day === day).length}</span></button>)}</div>
          {!visible.length ? <Empty title={items.length ? 'Không có việc khớp ngày/chặng này.' : 'Tuần này còn chỗ trống.'} action={items.length ? <button className="text-button" onClick={() => {setDayFilter(-1);setStageFilter('all');}}>Xem tất cả việc</button> : !closed ? <button className="secondary" onClick={newTask}>Thêm một việc nhỏ</button> : undefined}>{closed ? 'Xem Weeks để đọc kết quả đã lưu.' : 'Chọn một ngày khác hoặc thêm việc bạn muốn làm.'}</Empty> : Array.from({length:7},(_,day) => { const daily = visible.filter(t => t.day === day); return daily.length ? <section className="day-section" key={day}><div className="day-heading"><h3>{dateAt(plan.start,week * 7 + day).toLocaleDateString('vi-VN',{weekday:'long'})}</h3><span>{dateText(dateAt(plan.start,week * 7 + day))} · {minutesText(daily.reduce((n,t) => n + t.minutes,0))}</span></div><div className="daily-tasks">{daily.map(t => <article className={`task-row ${t.completedAt ? 'done' : ''}`} key={t.id}><label className="task-checkbox"><input type="checkbox" aria-label={`Hoàn thành ${t.title}`} checked={!!t.completedAt} disabled={!!closed} onChange={() => patchTask({...t,completedAt:t.completedAt ? undefined : new Date().toISOString()})}/><span aria-hidden="true">{t.completedAt ? <Check size={15}/> : null}</span></label><div className="task-copy"><strong>{t.title}</strong><span>{t.stage} · {minutesText(t.minutes)}</span>{t.notes && <p>{t.notes}</p>}</div><div className="task-actions">{t.url && <External href={t.url} className="source-icon"><BookOpen size={17}/><span className="sr-only">Nguồn cho {t.title}</span></External>}<button className="icon-button" disabled={!!closed} aria-label={`Sửa ${t.title}`} onClick={() => {setEditingNew(false);setEditing({...t});}}><Pencil size={16}/></button></div></article>)}</div></section> : null;})}
        </section></div></>}
      {planTab === 'weeks' && <section className="weeks-view"><div className="section-heading"><div><span className="eyebrow">YOUR WEEKS, COLLECTED</span><h2>Nhìn lại từng tuần.</h2></div><span className="pill">{plan.closed.length} tuần đã kết thúc</span></div>{Array.from({length:weekCount},(_,i) => {const ts=plan.tasks.filter(t=>t.week===i); const c=plan.closed.find(row=>row.week===i); const n=c?.done??ts.filter(t=>t.completedAt).length;const total=c?.total??ts.length;return <button className="week-card" key={i} onClick={() => {setWeek(i);setDayFilter(-1);setStageFilter('all');setPlanTab('plan');}}><div><strong>Tuần {i+1}</strong><span>{dateText(dateAt(plan.start,i*7))} — {dateText(dateAt(plan.start,i*7+6))}</span><small>{c ? 'ĐÃ KẾT THÚC' : 'ĐANG LÊN KẾ HOẠCH'}</small></div><div className="week-spark" aria-hidden="true">{Array.from({length:7},(_,day) => <span key={day}><i style={{height:`${Math.min(30,5+ts.filter(t=>t.day===day&&t.completedAt).length*8)}px`}}/>{dateAt(plan.start,i*7+day).toLocaleDateString('vi-VN',{weekday:'narrow'})}</span>)}</div><div className="week-done"><strong>{n}/{total}</strong><small>VIỆC HOÀN THÀNH</small></div><ArrowUpRight size={20}/></button>;})}</section>}
      {planTab === 'stats' && <section className="stats-view"><span className="eyebrow">NOTICE THE SMALL WINS</span><h2>Tiến độ có thể nhìn thấy.</h2><p className="section-intro">Số liệu từ việc bạn tự đánh dấu hoàn thành; thời lượng là ước lượng của công việc.</p><div className="stats-summary"><div><strong>{plan.tasks.filter(t=>t.completedAt).length}</strong><span>việc đã hoàn thành</span></div><div><strong>{plan.closed.length}</strong><span>tuần đã kết thúc</span></div><div><strong>{minutesText(plan.tasks.filter(t=>t.completedAt).reduce((n,t)=>n+t.minutes,0))}</strong><span>thời lượng việc hoàn thành</span></div></div><div className="stats-paper"><h3>Tiến độ theo tuần</h3>{Array.from({length:weekCount},(_,i)=>{const ts=plan.tasks.filter(t=>t.week===i);const c=plan.closed.find(row=>row.week===i);const n=c?.done??ts.filter(t=>t.completedAt).length;const total=c?.total??ts.length;return <div className="stat-week" key={i}><span>Tuần {i+1}</span><div className="progress-track"><span style={{width:`${total?n/total*100:0}%`}}/></div><strong>{n}/{total}</strong><small>{c?'Đã lưu':'Đang học'}</small></div>;})}</div><button className="text-button" onClick={()=>navigate('/profile')}>Xem nhịp học theo ngày tại Profile <ArrowRight size={16}/></button></section>}
    </div>;
  }

  function Profile() {
    const activity = state.plans.flatMap(p=>p.tasks.map(t=>({id:`${p.id}/${t.id}`,moduleId:t.stageId,title:t.title,minutes:t.minutes,sourceId:'',week:t.week,completed:!!t.completedAt,notes:t.notes,completedAt:t.completedAt})));
    return <div className="page"><Heading eyebrow="YOUR PROFILE" title="Your learning" emphasis="rhythm">Một nơi để nhìn lại những bước nhỏ và điều chỉnh thông tin học tập.</Heading><div className="profile-layout"><form className="profile-paper" onSubmit={e=>{e.preventDefault();if(patch({name:profileName.trim(),major:profileMajor}))setToast('Đã lưu hồ sơ học tập.');}}><span className="eyebrow">A LITTLE ABOUT YOU</span><h2>Hồ sơ học tập</h2><label>Tên hiển thị<input maxLength={60} value={profileName} onChange={e=>setProfileName(e.target.value)} placeholder="Bạn muốn được gọi là gì?"/></label><label>Ngành đang theo học<select value={profileMajor} onChange={e=>setProfileMajor(e.target.value)}><option value="">Chưa chọn ngành</option>{faculties.map(f=><optgroup key={f.id} label={f.name}>{f.majors.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</optgroup>)}</select></label><p className="small-note">Ngành học ưu tiên gợi ý khám phá, không khóa lựa chọn hướng của bạn.</p><button type="submit" className="primary">Lưu hồ sơ <Check size={16}/></button></form><section className="profile-overview"><span className="eyebrow">YOUR LEARNING SPACE</span><h2>{state.name ? `Hi, ${state.name}.` : 'Một góc học tập của bạn.'}</h2><div className="profile-current"><span className="pill">{majorLabel(state.major)}</span><h3>{plan?.name || path.name}</h3><p>{plan?.goal || 'Chọn một hướng và tạo kế hoạch đầu tiên.'}</p></div><div className="profile-counts"><strong>{state.plans.length}<span>kế hoạch đã lưu</span></strong><strong>{state.bookmarks.length}<span>mục tiêu bổ trợ</span></strong></div><div className="account-paper"><span className="eyebrow">TAKE YOUR PLANS WITH YOU</span><h3>Học ở đâu, tiếp tục ở đó.</h3><p>Kết nối tài khoản để lưu kế hoạch và hồ sơ giữa các thiết bị.</p><button className="secondary" onClick={()=>setAccount(true)}>Xem đăng nhập Google <ArrowRight size={16}/></button><small>Bản prototype hiện lưu trên trình duyệt; chưa kết nối Google.</small></div></section></div><StudyActivity tasks={activity}/><div className="page-footnote">Nhịp học tổng hợp các việc có ngày hoàn thành trong các kế hoạch của bản xem thử. Không tự tạo lịch sử học tập.</div></div>;
  }

  return <div className="prototype-app"><a className="skip-link" href="#main" onClick={e=>{e.preventDefault();document.getElementById('main')?.focus();}}>Bỏ qua điều hướng</a><div className="review-banner"><span><i/>PROTOTYPE 02 · GIAO DIỆN ĐỂ DUYỆT</span><div className="review-controls"><label>Thử trạng thái<select aria-label="Thử trạng thái giao diện" value={reviewState} onChange={e=>setReviewState(e.target.value)}><option value="ready">Bình thường</option><option value="loading">Đang tải (mẫu)</option><option value="error">Lỗi tải (mẫu)</option></select></label><a href="/">Bản Backend cũ <ArrowUpRight size={13}/></a></div></div><header className="app-header"><NavLink to="/explore" className="brand" onClick={()=>setMenu(false)}><img src="/favicon.svg" alt=""/><span>Major<em>Weave</em><small>EXPLORE. LEARN. GROW.</small></span></NavLink><button className="mobile-menu icon-button" aria-label="Mở điều hướng" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Menu size={23}/></button><nav aria-label="Điều hướng chính" className={menu?'open':''}>{nav.map(item=><NavLink key={item.url} to={item.url} onClick={()=>{setMenu(false);if(item.url==='/profile'){setProfileName(state.name);setProfileMajor(state.major);}}}><item.icon size={17}/>{item.label}</NavLink>)}</nav><button className="account-button" aria-label="Tài khoản khách" onClick={()=>setAccount(true)}><span className="guest-dot"/><span>{state.name || 'Guest'}</span><UserRound size={17}/></button></header>
    {saveError && <div className="save-error" role="alert">{saveError}<button className="text-button" onClick={()=>setSaveError('')}>Đóng thông báo</button></div>}
    <main id="main" tabIndex={-1}>{reviewState === 'loading' ? <div className="page review-loading" role="status" aria-busy="true"><span className="eyebrow">TRẠNG THÁI MẪU ĐỂ DUYỆT</span><h2>Đang chuẩn bị không gian học tập…</h2><div className="skeleton-line"/><div className="skeleton-line short"/><div className="skeleton-cards">{[1,2,3].map(i=><div key={i}/>)}</div><button className="secondary" onClick={()=>setReviewState('ready')}>Xem dữ liệu mẫu</button></div> : reviewState === 'error' ? <div className="page" role="alert"><Empty title="Chưa tải được nội dung." action={<button className="primary" onClick={()=>setReviewState('ready')}>Thử lại với dữ liệu mẫu <ArrowRight size={17}/></button>}>Đây là lỗi giả lập để duyệt giao diện. Các kế hoạch trên trình duyệt vẫn được giữ.</Empty></div> : <Routes><Route path="/explore" element={Explore()}/><Route path="/path" element={PathDetail()}/><Route path="/roadmap" element={MyRoadmap()}/><Route path="/plan" element={MyPlan()}/><Route path="/profile" element={Profile()}/><Route path="*" element={Explore()}/></Routes>}</main>
    <footer className="app-footer"><span>MajorWeave<span className="rust">.</span> One thread at a time.</span><span>Nội dung mẫu để kiểm tra giao diện · <External href="https://beaverplans.com/">Cảm hứng BeaverPlans</External></span></footer>
    {toast && <div className="toast" role="status"><Check size={17}/>{toast}</div>}
    {stageOpen && <Modal title={stageOpen.title} wide onClose={()=>setStageOpen(null)}><div className="modal-body"><div className="outcome"><span className="eyebrow">SAU CHẶNG NÀY</span><p>{stageOpen.outcome}</p></div><div className="section-heading"><h3>Chọn một nguồn phù hợp.</h3><span className="pill">{stageOpen.sources.length} nguồn mẫu</span></div><div className="drawer-sources">{stageOpen.sources.map(s=>SourceCard({s,stage:stageOpen}))}</div><h3>Một chút thực hành</h3><ul className="practice-list">{stageOpen.tasks.map((t,i)=><li key={i}><span>{t.title}</span><small>{minutesText(t.minutes)}</small></li>)}</ul><p className="small-note">{contentNote(state.path)}</p></div><div className="modal-bottom"><label className="inline-check"><input type="checkbox" checked={draft.known.includes(stageOpen.id)} onChange={()=>toggleKnown(stageOpen.id)}/>Tôi đã biết kỹ năng này</label><button className={draft.selected.includes(stageOpen.id)?'secondary':'primary'} onClick={()=>toggleStage(stageOpen.id)}>{draft.selected.includes(stageOpen.id)?<><Check size={16}/>Đã thêm · Bấm để bỏ</>:<><Plus size={16}/>Thêm vào roadmap</>}</button></div></Modal>}
    {rebuild && <Modal title="Thay kế hoạch đang xem?" onClose={()=>setRebuild(false)}><div className="modal-body"><p><strong>{plan?.name}</strong> sẽ được thay bằng <strong>{path.name} · {branch.name}</strong>.</p><p>Các kế hoạch khác được giữ nguyên. Việc tự thêm và chỉnh sửa tiêu đề/thời lượng của kế hoạch này sẽ được thay. Ghi chú và hoàn thành của bài có cùng định danh được giữ khi không đổi hướng/nhánh.</p><p>Lịch sử tuần đã kết thúc của kế hoạch này sẽ được tạo lại trong bản thử.</p><div className="modal-actions"><button className="secondary" onClick={()=>setRebuild(false)}>Giữ kế hoạch hiện tại</button><button className="primary" onClick={()=>createPlan(true)}>Thay kế hoạch</button></div></div></Modal>}
    {editing && plan && <Modal title={editingNew?'Thêm một việc nhỏ.':'Chỉnh một bước nhỏ.'} onClose={()=>setEditing(null)}><form className="modal-body task-form" onSubmit={e=>{e.preventDefault();if(!editing.title.trim()||!Number.isFinite(editing.minutes)||editing.minutes<15)return;const task={...editing,title:editing.title.trim()};const ok=editingNew?patchPlan({tasks:[...plan.tasks,task]}):patchTask(task);if(ok){setWeek(task.week);setEditing(null);setToast('Đã lưu công việc.');}}}><label>Tên công việc<input autoFocus required maxLength={200} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><div className="form-row"><label>Thời lượng (phút)<input required type="number" min={15} max={360} step={15} value={editing.minutes || ''} onChange={e=>setEditing({...editing,minutes:Number(e.target.value)})}/></label><label>Chuyển đến tuần<select aria-label="Chuyển đến tuần" value={editing.week} onChange={e=>setEditing({...editing,week:Number(e.target.value)})}>{Array.from({length:Math.max(week+2,...plan.tasks.map(t=>t.week+2))},(_,i)=><option key={i} value={i} disabled={plan.closed.some(c=>c.week===i)}>Tuần {i+1}</option>)}</select></label></div><label>Ngày học<select aria-label="Ngày học" value={editing.day} onChange={e=>setEditing({...editing,day:Number(e.target.value)})}>{Array.from({length:7},(_,i)=><option key={i} value={i}>{dateAt(plan.start,editing.week*7+i).toLocaleDateString('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit'})}</option>)}</select></label><label>Ghi chú<textarea rows={3} maxLength={1000} value={editing.notes} placeholder="Điều đã hiểu, khó khăn hoặc kết quả…" onChange={e=>setEditing({...editing,notes:e.target.value})}/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setEditing(null)}>Hủy</button><button type="submit" className="primary">Lưu công việc <Check size={16}/></button></div></form></Modal>}
    {endWeek && plan && <Modal title="Khép lại một tuần." onClose={()=>setEndWeek(false)}><div className="modal-body"><p>Tuần {week+1}: <strong>{plan.tasks.filter(t=>t.week===week&&t.completedAt).length}/{plan.tasks.filter(t=>t.week===week).length} việc hoàn thành</strong>. Kết quả này sẽ được giữ trong Weeks và Stats.</p><fieldset className="end-week-options"><legend>Các việc chưa hoàn thành</legend><label><input type="radio" name="end-week" value="move" checked={endingChoice==='move'} onChange={()=>setEndingChoice('move')}/><span><strong>Chuyển sang tuần tiếp theo</strong><small>Giữ công việc và ghi chú; không tạo bản sao.</small></span></label><label><input type="radio" name="end-week" value="drop" checked={endingChoice==='drop'} onChange={()=>setEndingChoice('drop')}/><span><strong>Bỏ khỏi lịch sắp tới</strong><small>Kết quả tổng kết tuần vẫn ghi nhận số việc đã lên lịch.</small></span></label></fieldset><div className="modal-actions"><button className="secondary" onClick={()=>setEndWeek(false)}>Chưa kết thúc</button><button className="primary" onClick={closeWeek}>Lưu và kết thúc tuần</button></div></div></Modal>}
    {account && <Modal title="Bring your plans along." onClose={()=>setAccount(false)}><div className="modal-body account-modal"><img src="/favicon.svg" alt=""/><p>Lưu những điều bạn đang học và tiếp tục trên thiết bị khác.</p><button className="secondary full" disabled>Tiếp tục với Google</button><p className="prototype-content-note">Đây là giao diện đăng nhập để duyệt. Google OAuth và đồng bộ chưa được kết nối; bản thử không tạo tài khoản giả.</p><button className="text-button" onClick={()=>setAccount(false)}>Tiếp tục khám phá với tư cách khách <ArrowRight size={16}/></button></div></Modal>}
  </div>;
}
