const { chromium } = require(process.env.MAJORWEAVE_PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const catalog = JSON.parse(fs.readFileSync('public/catalog.json', 'utf8'));
const reports = [];
const check = (name, result) => { assert.ok(result, name); reports.push(name); };
const majorIds = new Set(catalog.majors.map(m => m.id));
const pathIds = new Set(catalog.paths.map(p => p.id));
check('12 unique base majors across six faculties', majorIds.size === 12 && catalog.faculties.length === 6);
check('40 unique directions', pathIds.size === 16 && catalog.paths.length === 16);
check('Every major has directions or an explicit coverage gap and a UIT source', catalog.majors.every(m => (m.primaryPathIds.length > 0 || m.coverageNote) && m.sourceUrl.startsWith('https://tuyensinh.uit.edu.vn/')));
check('Every direction references valid majors and distinguishes related from primary', catalog.paths.every(p => [...p.majors, ...p.relatedMajors].every(id => majorIds.has(id)) && p.relatedMajors.every(id => !p.majors.includes(id))));
check('Only Backend is presented as fully implemented', catalog.paths.filter(p => p.sample).map(p => p.id).join() === 'backend');
check('Every direction has a concrete roadmap.sh URL', catalog.paths.every(p => p.roadmaps.length > 0 && p.roadmaps.every(r => /^https:\/\/roadmap\.sh\/[a-z-]+$/.test(r.url))));
(async () => {
 const browser = await chromium.launch({ channel: 'msedge', headless: true });
 const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
 const errors = [];
 page.on('pageerror', e => errors.push(e.message));
 try {
  await page.goto('http://127.0.0.1:5173/#/explore');
  await page.locator('.path-card').last().waitFor();
  await page.evaluate(() => document.fonts.ready);
  check('All directions can be explored from the default major', await page.locator('.path-card').count() === 16);
  check('Every card exposes its roadmap links in new tabs', await page.locator('.card-roadmap-links a[target="_blank"]').count() === 17);
  await page.locator('.major-matrix summary').click();
  check('The review matrix has one row per base major', await page.locator('.major-matrix tbody tr').count() === 12);
  await page.getByRole('button', { name: 'Xem hướng của Khoa học Dữ liệu', exact: true }).click();
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('majorweave.prototype.v1')).major === 'data');
  check('Major selection enables related-direction filtering', await page.getByLabel('Chỉ hướng gần / mở rộng từ ngành tôi').isChecked());
  check('Data Science includes Data Scientist', await page.getByRole('heading', { name: 'Data Scientist', exact: true }).isVisible());
  check('The profile records the selected major', await page.getByRole('combobox', { name: 'Ngành đang học', exact: true }).inputValue() === 'data');
  await page.getByLabel('Chỉ hướng gần / mở rộng từ ngành tôi').uncheck();
  await page.waitForFunction(() => document.querySelectorAll('.path-card').length === 16);
  check('Cross-major exploration remains unrestricted', await page.locator('.path-card').count() === 16);
  await page.getByLabel('Khám phá theo khoa').selectOption('ce');
  check('Exploring hardware retains the current Data Science major', await page.getByRole('combobox', { name: 'Ngành đang học', exact: true }).inputValue() === 'data');
  const ic = page.locator('.path-card').filter({ has: page.getByRole('heading', { name: 'Network Engineer', exact: true }) });
  await ic.getByRole('button', { name: 'Xem tổng quan', exact: true }).click();
  check('The overview explains network prerequisites', (await page.getByRole('dialog').innerText()).includes('TCP / IP'));
  check('The overview keeps the correct direction and current major', (await page.getByRole('dialog').innerText()).includes('Network Engineer') && (await page.getByRole('dialog').innerText()).includes('Khoa học Dữ liệu'));
  check('The overview links to the matching roadmap', await page.getByRole('dialog').getByRole('link', { name: 'Network Engineer', exact: true }).getAttribute('href') === 'https://roadmap.sh/network-engineer');
  await page.getByRole('button', { name: 'Tiếp tục khám phá', exact: true }).click();
  await page.getByLabel('Tìm hướng học').fill('XYZ_NO_SUCH_DIRECTION_123');
  await page.locator('.empty-inline').waitFor();
  check('Combined filters provide an empty state', (await page.locator('.empty-inline').innerText()).includes('Chưa có hướng học khớp các bộ lọc.'));
  await page.getByRole('button', { name: 'Xóa bộ lọc hướng học', exact: true }).click();
  await page.getByLabel('Chỉ hướng gần / mở rộng từ ngành tôi').check();
  await page.getByRole('combobox', { name: 'Khoa hiện tại', exact: true }).selectOption('');
  await page.waitForFunction(() => !document.querySelector('.path-catalog-toolbar input[type="checkbox"]').checked);
  check('Skipping a major clears and disables its filter', !await page.getByLabel('Chỉ hướng gần / mở rộng từ ngành tôi').isChecked() && await page.getByLabel('Chỉ hướng gần / mở rộng từ ngành tôi').isDisabled());
  await page.getByRole('combobox', { name: 'Khoa hiện tại', exact: true }).selectOption('ce');
  await page.getByRole('combobox', { name: 'Ngành đang học', exact: true }).selectOption('chip');
  await page.getByLabel('Chỉ hướng gần / mở rộng từ ngành tôi').check();
  await page.waitForFunction(() => document.querySelectorAll('.path-card').length === 0);
  check('Chip Design explains the lack of a matching roadmap', (await page.locator('.coverage-note').innerText()).includes('Chưa tìm thấy roadmap chuyên biệt'));
  await page.getByRole('button', { name: 'Xóa bộ lọc hướng học', exact: true }).click();
  await page.getByRole('combobox', { name: 'Khoa hiện tại', exact: true }).selectOption('se');
  await page.getByLabel('Tìm hướng học').fill('Data Scientist');
  await page.waitForFunction(() => document.querySelectorAll('.path-card').length === 1);
  check('A student from Software Engineering can find Data Scientist', await page.locator('.path-card').count() === 1 && await page.getByRole('heading', { name: 'Data Scientist', exact: true }).isVisible());
  await page.getByLabel('Tìm hướng học').fill('');
  await page.waitForFunction(() => document.querySelectorAll('.path-card').length === 16);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'artifacts/catalog-matrix-desktop.png' });
  await page.locator('.major-matrix summary').click();
  for (const width of [1024, 768, 390, 320]) {
   await page.setViewportSize({ width, height: 900 });
   const size = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth }));
   check(`The expanded catalog fits ${width}px`, size.scroll <= size.width + 1);
   if (width === 390) await page.screenshot({ path: 'artifacts/catalog-mobile.png' });
  }
  await page.goto('http://127.0.0.1:5173/events.html');
  check('There are 28 separately described functional flows', await page.locator('details.flow[id^="ef"]').count() === 28);
  await page.locator('#ef09 summary').click();
  check('Selecting a source has a visible dedicated diagram', await page.locator('#ef09-figure').isVisible());
  check('The page has 30 accessible diagrams including two overviews', await page.locator('svg[role="img"][aria-labelledby]').count() === 30);
  check('Mobile event document does not overflow the page', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await page.setViewportSize({ width: 1340, height: 950 });
  await page.evaluate(() => document.fonts.ready);
  await page.locator('#ef09-figure').screenshot({ path: 'artifacts/event-select-source.png' });
  await page.evaluate(() => document.querySelectorAll('details.flow').forEach(e => { e.open = true; }));
  const overflows = await page.evaluate(() => [...document.querySelectorAll('svg g')].flatMap(g => {
   const rects = [...g.children].filter(e => e.tagName === 'rect');
   const texts = [...g.children].filter(e => e.tagName === 'text');
   if (rects.length !== 1 || !texts.length || +rects[0].getAttribute('height') < 48) return [];
   const r = rects[0].getBBox();
   return texts.filter(t => { const b = t.getBBox(); return b.x < r.x + 4 || b.x + b.width > r.x + r.width - 4 || b.y < r.y || b.y + b.height > r.y + r.height; }).map(t => t.textContent);
  }));
  check('Diagram node labels fit their boxes', overflows.length === 0);
  check('The catalog and event flows have no runtime errors', errors.length === 0);
  fs.writeFileSync('artifacts/catalog-verification.json', JSON.stringify({ passed: reports.length, checks: reports, errors, overflows, date: new Date().toISOString() }, null, 2));
  console.log(`PASS: ${reports.length} catalog and event checks.`);
 } catch (e) { await page.screenshot({ path: 'artifacts/catalog-failure.png', fullPage: true }); console.error(e); process.exitCode = 1; }
 finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
