const { chromium } = require(process.env.MAJORWEAVE_PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const output = path.resolve('artifacts');
  fs.mkdirSync(output, { recursive: true });
  const reports = [];
  const check = (name, result = true) => { assert.ok(result, name); reports.push(name); };
  const saved = () => page.evaluate(() => JSON.parse(localStorage.getItem('majorweave.prototype.v1')));
  const close = () => page.getByRole('button', { name: 'Đóng', exact: true }).click();
  try {
    await page.goto('http://127.0.0.1:5173/#/explore');
    await page.evaluate(() => localStorage.removeItem('majorweave.prototype.v1'));
    await page.reload();
    await page.getByRole('heading', { name: 'One major. Many possible paths.' }).waitFor();
    await page.evaluate(() => document.fonts.ready);
    check('Explore shows 16 directions', await page.locator('.path-card').count() === 16);
    await page.screenshot({ path: path.join(output, 'explore-desktop.png'), fullPage: true });
    await page.screenshot({ path: path.join(output, 'preview-desktop.png'), fullPage: false });
    await page.getByLabel('Khám phá theo khoa').selectOption('ce');
    check('Cross-faculty browse includes Network Engineer', await page.getByRole('heading', { name: 'Network Engineer', exact: true }).isVisible());
    check('Browsing another faculty keeps current major', (await saved()).major === 'software');
    await page.getByLabel('Khám phá theo khoa').selectOption('all');
    await page.getByRole('link', { name: 'Khám phá hướng này' }).click();
    const backendReference = page.getByRole('link', { name: 'Backend trên roadmap.sh', exact: true });
    const nodeReference = page.getByRole('link', { name: 'Node.js trên roadmap.sh', exact: true });
    await backendReference.waitFor();
    check('Backend reference is prominent and opens a new tab', await backendReference.isVisible() && await backendReference.getAttribute('href') === 'https://roadmap.sh/backend' && await backendReference.getAttribute('target') === '_blank');
    check('Node.js reference links to its correct roadmap', await nodeReference.getAttribute('href') === 'https://roadmap.sh/nodejs');
    await page.getByRole('button', { name: /Node.js essentials/ }).click();
    await page.getByRole('dialog').waitFor();
    await page.getByRole('dialog').locator('.resource-card').filter({ hasText: 'W3Schools' }).getByRole('button', { name: 'Chọn nguồn này' }).click();
    check('Selected source is saved', (await saved()).sourceByModule.node === 'w3-node');
    await page.getByLabel('Lọc nguồn học', { exact: true }).selectOption('vi');
    check('Vietnamese filter shows F8 only', await page.getByRole('dialog').locator('.resource-card').count() === 1);
    await page.keyboard.press('Escape');
    check('Escape closes resource drawer', await page.getByRole('dialog').count() === 0);
    await page.getByRole('button', { name: /SQL & data persistence/ }).click();
    check('NoSQL material is not offered as a substitute for SQL', await page.getByRole('dialog').locator('.resource-card').filter({ hasText: 'MongoDB' }).count() === 0);
    await close();
    await page.getByRole('tab', { name: /Nguồn học/ }).click();
    check('Roadmap references remain visible on the resource tab', await backendReference.isVisible());
    check('Node library includes the original sources and new CS foundations', await page.locator('.resource-card').count() === 26 && await page.getByRole('heading', { name: /6.006/ }).isVisible() && await page.getByRole('heading', { name: /Operating Systems: Three/ }).isVisible());
    await page.getByLabel('Tìm nguồn học').fill('không tìm thấy mục này');
    check('Search provides useful empty state', await page.getByText('Chưa có nguồn khớp tìm kiếm.').isVisible());
    await page.getByRole('button', { name: 'Xóa bộ lọc' }).click();
    await page.getByRole('tab', { name: /Chứng nhận/ }).click();
    check('Roadmap references remain visible on the credential tab', await nodeReference.isVisible());
    await page.getByRole('button', { name: 'Lưu Full Stack Open Certificate', exact: true }).click();
    check('Credential can be bookmarked', (await saved()).credentials.includes('fso-cert'));
    await page.getByRole('tab', { name: /Roadmap/ }).click();
    await page.screenshot({ path: path.join(output, 'path-desktop.png'), fullPage: true });
    await page.getByRole('link', { name: 'Tùy chỉnh roadmap', exact: true }).click();
    await page.getByLabel('Mục tiêu của bạn').fill('Xây API quản lý công việc');
    await page.getByLabel('Ngày bắt đầu').fill('2026-10-05');
    await page.getByRole('button', { name: 'Tạo kế hoạch của tôi' }).click();
    await page.getByRole('heading', { name: 'Make room for progress.' }).waitFor();
    let state = await saved();
    check('Known JavaScript is omitted from generated plan', !state.tasks.some(t => t.moduleId === 'js'));
    check('Chosen resource reaches the weekly plan', state.tasks.filter(t => t.moduleId === 'node').every(t => t.sourceId === 'w3-node'));
    for (const week of new Set(state.tasks.map(t => t.week))) check(`Generated week ${week + 1} fits time budget`, state.tasks.filter(t => t.week === week).reduce((sum, t) => sum + t.minutes, 0) <= state.hours * 60);
    const firstTask = state.tasks[0];
    await page.getByRole('checkbox', { name: `Hoàn thành: ${firstTask.title}`, exact: true }).check();
    check('Completion updates saved progress', (await saved()).tasks[0].completed);
    const completedAt = (await saved()).tasks[0].completedAt;
    check('Completion records a real date', Number.isFinite(new Date(completedAt).getTime()));
    check('My Plan links to Profile instead of duplicating the full activity chart', await page.getByRole('link', { name: 'Xem nhịp học', exact: true }).isVisible() && await page.locator('.study-activity').count() === 0);
    await page.getByRole('button', { name: `Sửa: ${firstTask.title}`, exact: true }).click();
    await page.getByLabel('Tên công việc', { exact: true }).fill('Ôn OOP và xây mô hình đầu tiên');
    await page.getByLabel('Chuyển đến', { exact: true }).selectOption('1');
    await page.getByLabel('Ghi chú', { exact: true }).fill('Đã viết class User và Task.');
    await page.getByRole('button', { name: 'Lưu thay đổi', exact: true }).click();
    state = await saved();
    check('Task can move weeks without losing completion', state.tasks[0].week === 1 && state.tasks[0].completed);
    check('Moving a task preserves its real completion date', state.tasks[0].completedAt === completedAt);
    check('Task title and note update', state.tasks[0].title === 'Ôn OOP và xây mô hình đầu tiên' && state.tasks[0].notes.includes('class User'));
    await page.getByRole('button', { name: 'Thêm một việc nhỏ' }).click();
    await page.getByLabel('Việc muốn làm').fill('Ôn lại HTTP methods');
    await page.getByRole('button', { name: 'Thêm việc', exact: true }).click();
    check('Custom task is added to selected week', (await saved()).tasks.some(t => t.moduleId === 'custom' && t.week === 1));
    await page.reload();
    check('Progress survives reload', (await saved()).tasks[0].completed && (await saved()).sourceByModule.node === 'w3-node');
    check('Activity date survives reload', (await saved()).tasks[0].completedAt === completedAt);
    await page.getByRole('button', { name: /Tuần 02/ }).click();
    check('Edited note survives reload', await page.getByText('Đã viết class User và Task.', { exact: true }).isVisible());
    await page.getByRole('checkbox', { name: 'Hoàn thành: Ôn OOP và xây mô hình đầu tiên', exact: true }).uncheck();
    check('Undoing completion removes the recorded date', !(await saved()).tasks[0].completedAt);
    await page.getByRole('checkbox', { name: 'Hoàn thành: Ôn OOP và xây mô hình đầu tiên', exact: true }).check();
    await page.getByRole('button', { name: /Tuần 01/ }).click();
    await page.screenshot({ path: path.join(output, 'plan-desktop.png'), fullPage: true });
    await page.getByRole('link', { name: 'Chỉnh roadmap', exact: true }).click();
    await page.getByRole('button', { name: 'Tạo kế hoạch của tôi' }).click();
    check('Rebuilding asks before replacing edits', await page.getByRole('dialog').getByText('Tạo lại kế hoạch?', { exact: true }).isVisible());
    await page.getByRole('button', { name: 'Giữ kế hoạch hiện tại', exact: true }).click();
    check('Cancel rebuilding retains custom task', (await saved()).tasks.some(t => t.moduleId === 'custom'));
    await page.getByLabel('Mục tiêu của bạn').fill('');
    await page.getByRole('button', { name: 'Tạo kế hoạch của tôi' }).click();
    check('Blank goal blocks generation with a visible error', await page.getByRole('alert').isVisible());
    await page.getByLabel('Mục tiêu của bạn').fill('Xây API quản lý công việc');
    for (const width of [1440, 1024, 768, 390, 320]) {
      await page.setViewportSize({ width, height: 900 });
      for (const route of ['explore', 'path', 'roadmap', 'plan', 'profile']) {
        await page.goto(`http://127.0.0.1:5173/#/${route}`);
        await page.locator('main h1').waitFor();
        const size = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, width: window.innerWidth }));
        check(`${route} has no horizontal overflow at ${width}px`, size.scroll <= size.width + 1);
        if (width === 390) await page.screenshot({ path: path.join(output, `${route}-mobile.png`), fullPage: true });
      }
    }
    await page.goto('http://127.0.0.1:5173/#/path');
    await page.getByRole('button', { name: /Node.js essentials/ }).click();
    const drawerWidth = await page.getByRole('dialog').evaluate(el => el.getBoundingClientRect().width);
    check('Resource drawer fits 320px phone', drawerWidth <= 320);
    await page.screenshot({ path: path.join(output, 'drawer-mobile.png'), fullPage: true });
    await close();
    check('No JavaScript runtime errors', errors.length === 0);
    const linkCount = await page.locator('a[target="_blank"]').count();
    check('External source links remain accessible', linkCount > 0);
    const malformed = await browser.newContext();
    const malformedPage = await malformed.newPage();
    await malformedPage.goto('http://127.0.0.1:5173');
    await malformedPage.evaluate(() => localStorage.setItem('majorweave.prototype.v1', '{broken'));
    await malformedPage.reload();
    check('Corrupt saved data safely restores defaults', await malformedPage.getByRole('heading', { name: 'One major. Many possible paths.' }).isVisible());
    await malformed.close();
    fs.writeFileSync(path.join(output, 'verification.json'), JSON.stringify({ passed: reports.length, checks: reports, errors, date: new Date().toISOString() }, null, 2));
    console.log(`PASS: ${reports.length} checks. Screenshots and report saved in artifacts/.`);
  } catch (error) {
    await page.screenshot({ path: path.join(output, 'failure.png'), fullPage: true });
    console.error(error);
    process.exitCode = 1;
  } finally {
    await browser.close();
  }
})();
