import assert from 'node:assert/strict';
import { build } from 'esbuild';
const result = await build({entryPoints:['src/persistence/migration-source.ts'],bundle:true,platform:'node',format:'esm',write:false});
const {inspectLegacyV1,readLegacyV1,LEGACY_V1_KEY}=await import(`data:text/javascript;base64,${Buffer.from(result.outputFiles[0].text).toString('base64')}`);
const fixture=()=>({version:1,stack:'node',profileName:'Huy QA',planMeta:{stack:'node',goal:'Plan cũ',hours:5,startDate:'2026-10-05'},major:'software',browseFaculty:'all',level:'basic',preferFree:true,language:'all',selected:['js','unknown-stage'],known:[],sourceByModule:{js:'unknown-source'},goal:'Nháp mới',hours:2,startDate:'2026-10-05',tasks:[{id:'unknown-work',moduleId:'unknown-stage',title:'Việc tự sửa',minutes:1500,sourceId:'unknown-source',week:1001,completed:true,notes:'Gốc'}],credentials:['unknown-credential']});
async function good(raw){const r=await inspectLegacyV1(raw);assert.equal(r.ok,true,JSON.stringify(r));return r.value;}
let pass=0,fail=0;
async function test(name,run){try{await run();pass++;console.log(`PASS ${name}`);}catch(e){fail++;console.error(`FAIL ${name}: ${e.message}`);}}
await test('Không có nguồn: null, không defaults',async()=>assert.equal(await good(null),null));
await test('Raw/unknown work/source/credential và phút/tuần giữ nguyên',async()=>{const f=fixture(),raw=JSON.stringify(f),s=await good(raw);assert.equal(s.raw,raw);assert.deepEqual(s.state,f);});
await test('Done thiếu timestamp: cảnh báo, không bịa ngày',async()=>{const s=await good(JSON.stringify(fixture()));assert.ok(s.warnings.some(x=>x.code==='LEGACY_UNKNOWN_COMPLETION_DATE'));assert.equal(s.state.tasks[0].completedAt,undefined);});
await test('Timestamp thực giữ nguyên',async()=>{const f=fixture();f.tasks[0].completedAt='2026-10-07T23:00:00+07:00';assert.equal((await good(JSON.stringify(f))).state.tasks[0].completedAt,f.tasks[0].completedAt);});
await test('SHA256 ổn định theo raw, đổi khi raw đổi',async()=>{const raw=JSON.stringify(fixture()),a=await good(raw),b=await good(raw),c=await good(raw+' ');assert.match(a.fingerprint,/^legacy-v1:sha256:[a-f0-9]{64}$/);assert.equal(a.fingerprint,b.fingerprint);assert.notEqual(a.fingerprint,c.fingerprint);});
await test('JSON lỗi không thay defaults',async()=>{const r=await inspectLegacyV1('{bad');assert.equal(r.ok,false);assert.equal(r.issues[0].code,'LEGACY_JSON');});
await test('Version tương lai bị từ chối',async()=>{const r=await inspectLegacyV1(JSON.stringify({...fixture(),version:99}));assert.equal(r.ok,false);assert.equal(r.code,'unsupported_version');});
await test('Null/mảng/object thiếu trường/empty bị từ chối',async()=>{for(const raw of ['null','[]','{}',''])assert.equal((await inspectLegacyV1(raw)).ok,false);});
await test('Task lỗi: từ chối cả nguồn, không lọc',async()=>{const f=fixture();f.tasks.push({...f.tasks[0],id:'bad',minutes:-1});assert.equal((await inspectLegacyV1(JSON.stringify(f))).ok,false);});
await test('ID task trùng bị từ chối',async()=>{const f=fixture();f.tasks.push({...f.tasks[0]});assert.equal((await inspectLegacyV1(JSON.stringify(f))).ok,false);});
await test('Ngày sai và timestamp thiếu timezone bị từ chối',async()=>{const f=fixture();f.startDate='2026-02-30';assert.equal((await inspectLegacyV1(JSON.stringify(f))).ok,false);f.startDate='2026-10-05';f.tasks[0].completedAt='2026-10-07T10:00:00';assert.equal((await inspectLegacyV1(JSON.stringify(f))).ok,false);});
await test('PlanMeta độc lập với draft',async()=>{const f=fixture();f.stack='python';const s=await good(JSON.stringify(f));assert.equal(s.state.stack,'python');assert.equal(s.state.planMeta.stack,'node');});
await test('PlanMeta chưa có: giữ nguyên, cảnh báo',async()=>{const f=fixture();delete f.planMeta;const s=await good(JSON.stringify(f));assert.equal(s.state.planMeta,undefined);assert.ok(s.warnings.some(x=>x.code==='LEGACY_NO_PLAN_META'));});
await test('Extra fields không bị xóa',async()=>{const f=fixture();f.extraHistory={keep:true};assert.deepEqual((await good(JSON.stringify(f))).state.extraHistory,f.extraHistory);});
await test('Reader chỉ đọc đúng key v1',async()=>{const keys=[];const r=await readLegacyV1(k=>{keys.push(k);return JSON.stringify(fixture());});assert.equal(r.ok,true);assert.deepEqual(keys,[LEGACY_V1_KEY]);});
await test('Reader throw trả storage, không defaults',async()=>{const r=await readLegacyV1(()=>{throw Error('denied');});assert.equal(r.ok,false);assert.equal(r.code,'storage');});

const previewBuild=await build({stdin:{contents:"export * from './src/persistence/migration-preview'; export {backendPack,legacyWorkMap,legacyStageMap} from './src/content/paths/backend';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const {previewLegacyV1,backendPack,legacyWorkMap,legacyStageMap}=await import(`data:text/javascript;base64,${Buffer.from(previewBuild.outputFiles[0].text).toString('base64')}`);
let seq=1;
const context=()=>({now:'2026-10-09T03:30:00Z',timeZone:'Asia/Ho_Chi_Minh',nextId:()=>`00000000-0000-4000-8000-${String(seq++).padStart(12,'0')}`});
const migrationFixture=()=>{
 const stage=backendPack.stages.find(s=>s.id===legacyStageMap.node.js),work=stage.work[0];
 return {...fixture(),selected:['js'],known:[],sourceByModule:{js:stage.defaultResourceId.replace(/^resource\./,'')},credentials:[],tasks:[{id:'js-0',moduleId:'js',title:work.title,minutes:work.minutes,sourceId:stage.defaultResourceId.replace(/^resource\./,''),week:3,completed:true,notes:'Ghi chú gốc'}]};
};
const preview=async(f,opts=context())=>{const r=await previewLegacyV1(JSON.stringify(f),opts);assert.equal(r.ok,true,JSON.stringify(r));return r.value;};
await test('Preview khớp template: maps thật, segment nguyên bài và không chia lại',async()=>{const f=migrationFixture(),p=await preview(f),t=p.plan.current.tasks[0];assert.equal(t.workId,legacyWorkMap.node['js-0']);assert.equal(t.customized,false);assert.deepEqual(t.segment,{fromMinute:0,toMinute:f.tasks[0].minutes});assert.equal(t.weekIndex,3);assert.equal(t.title,f.tasks[0].title);assert.equal(t.notes,'Ghi chú gốc');assert.equal(p.summary.taskCount,1);assert.deepEqual(p.blockingIssues,[]);});
await test('Title/phút sửa: customized, segment null, không reset template',async()=>{const f=migrationFixture();f.tasks[0].title='Tên đã sửa';f.tasks[0].minutes=1500;const t=(await preview(f)).plan.current.tasks[0];assert.equal(t.customized,true);assert.equal(t.segment,null);assert.equal(t.minutes,1500);assert.equal(t.title,'Tên đã sửa');assert.equal(t.workId,legacyWorkMap.node['js-0']);});
await test('Unknown module/work giữ nguyên title/phút/tuần/notes',async()=>{const f=migrationFixture();f.tasks[0]={...f.tasks[0],id:'own-work',moduleId:'my-stage',title:'Bài tự thêm',minutes:333,week:8};const p=await preview(f),t=p.plan.current.tasks[0];assert.equal(t.workId,null);assert.equal(t.segment,null);assert.equal(t.customized,true);assert.equal(t.title,'Bài tự thêm');assert.equal(t.minutes,333);assert.equal(t.weekIndex,8);assert.ok(p.warnings.some(i=>i.code==='MIGRATION_UNKNOWN_STAGE'));});
await test('Nguồn thiếu không loại bỏ task, giữ ID nguồn trong notes/raw',async()=>{const f=migrationFixture();f.tasks[0].sourceId='missing-source';const p=await preview(f),t=p.plan.current.tasks[0];assert.equal(t.source,null);assert.ok(t.notes.includes('missing-source'));assert.equal(p.summary.missingSourceCount,1);assert.equal(p.plan.current.tasks.length,1);assert.equal(p.raw,JSON.stringify(f));});
await test('Done thiếu timestamp: completion null ngày/timezone',async()=>{const c=(await preview(migrationFixture())).plan.completions[0];assert.equal(c.completedAt,null);assert.equal(c.localDate,null);assert.equal(c.timeZone,null);});
await test('Timestamp thực giữ, ngày tính theo timezone preview',async()=>{const f=migrationFixture();f.tasks[0].completedAt='2026-10-07T23:30:00Z';const c=(await preview(f)).plan.completions[0];assert.equal(c.completedAt,f.tasks[0].completedAt);assert.equal(c.localDate,'2026-10-08');assert.equal(c.timeZone,'Asia/Ho_Chi_Minh');});
await test('Plan khác draft giữ track/mục tiêu/quỹ giờ riêng',async()=>{const f=migrationFixture();f.stack='python';f.selected=['python'];f.sourceByModule={};const p=await preview(f);assert.equal(p.plan.trackId,'backend.node');assert.equal(p.draft.trackId,'backend.python');assert.equal(p.plan.current.goal,'Plan cũ');assert.equal(p.draft.goal,'Nháp mới');assert.equal(p.plan.current.hoursPerWeek,5);assert.equal(p.draft.hoursPerWeek,2);});
await test('PlanMeta thiếu: chặn plan cho tới khi chọn rõ bối cảnh',async()=>{const f=migrationFixture();delete f.planMeta;const p=await preview(f);assert.equal(p.plan,null);assert.ok(p.blockingIssues.some(i=>i.code==='MIGRATION_PLAN_META_REQUIRED'));const q=await preview(f,{...context(),missingPlanMeta:{stack:'node',goal:'Đã chọn rõ',hours:5,startDate:'2026-10-05'}});assert.equal(q.plan.current.goal,'Đã chọn rõ');});
await test('Không có tasks: không dựng plan mặc định',async()=>{const f=migrationFixture();f.tasks=[];f.planMeta=null;assert.equal((await preview(f)).plan,null);});
await test('Ngày không Thứ Hai giữ nguyên và cảnh báo chặn, không tự dời lịch',async()=>{const f=migrationFixture();f.planMeta.startDate='2026-10-06';const p=await preview(f);assert.equal(p.plan.current.startDate,'2026-10-06');assert.ok(p.blockingIssues.some(i=>i.field==='planMeta.startDate'));});
await test('Nháp thiếu prerequisite không được tự thêm/đánh dấu biết',async()=>{const f=migrationFixture();f.selected=['express'];const p=await preview(f);assert.deepEqual(p.draft.selectedStageIds,[legacyStageMap.node.express]);assert.ok(p.blockingIssues.some(i=>i.code==='MIGRATION_DRAFT_PREREQUISITE'));});
await test('Unmapped selection/source/credential có inventory và raw',async()=>{const f=migrationFixture();f.selected.push('unknown-stage');f.sourceByModule['unknown-stage']='unknown-source';f.credentials=['unknown-cert'];const p=await preview(f);assert.ok(p.unresolved.selected.includes('unknown-stage'));assert.equal(p.unresolved.sources['unknown-stage'],'unknown-source');assert.deepEqual(p.unresolved.credentials,['unknown-cert']);assert.equal(p.raw,JSON.stringify(f));});
await test('ID factory lỗi/trùng và clock/timezone lỗi trả validation',async()=>{const raw=JSON.stringify(migrationFixture());for(const opts of [{...context(),nextId:()=>{throw Error('fail');}},{...context(),nextId:()=> '00000000-0000-4000-8000-000000000001'},{...context(),now:'bad'},{...context(),timeZone:'bad-zone'}])assert.equal((await previewLegacyV1(raw,opts)).ok,false);});
await test('Preview không sửa input, sửa output không ảnh hưởng preview kế tiếp',async()=>{const f=migrationFixture(),before=structuredClone(f),p=await preview(f);p.plan.current.tasks[0].title='Caller tamper';assert.deepEqual(f,before);assert.equal((await preview(f)).plan.current.tasks[0].title,f.tasks[0].title);});

const controllerBuild=await build({stdin:{contents:"export {createLegacyMigration} from './src/persistence/migration'; export {emptyWorkspace,validateRoadmapWorkspace} from './src/persistence/roadmap-store';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const {createLegacyMigration,emptyWorkspace,validateRoadmapWorkspace}=await import(`data:text/javascript;base64,${Buffer.from(controllerBuild.outputFiles[0].text).toString('base64')}`);
// Memory port proves controller behavior only. It does not prove native IndexedDB or semantic validation.
function harness(){
 const h={raw:JSON.stringify(migrationFixture()),disk:emptyWorkspace('Asia/Ho_Chi_Minh'),saves:0,loads:0,failSave:false,readThrows:false,gate:null,afterCommit:null};
 h.persistence={loadWorkspace:async()=>{h.loads++;return {ok:true,value:structuredClone(h.disk)};},saveWorkspace:async(candidate,revision)=>{
  h.saves++;if(h.gate)await h.gate;
  if(h.failSave)return {ok:false,code:'storage',issues:[{code:'QA_SAVE',field:'workspace',message:'Injected failure'}]};
  if(revision!==h.disk.revision)return {ok:false,code:'conflict',issues:[{code:'REVISION_CONFLICT',field:'revision',message:'Stale'}]};
  h.disk=structuredClone({...candidate,revision:revision+1});if(h.afterCommit)h.afterCommit();return {ok:true,value:structuredClone(h.disk)};
 }};
 h.deps={persistence:h.persistence,readLegacy:key=>{assert.equal(key,LEGACY_V1_KEY);if(h.readThrows)throw Error('read');return h.raw;},validate:validateRoadmapWorkspace,context};
 h.controller=createLegacyMigration(h.deps);return h;
}
async function prepared(h,choices){const r=await h.controller.prepare(choices);assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.value.kind,'preview');return r.value;}
async function committed(h,ticket){const r=await h.controller.confirm(ticket);assert.equal(r.ok,true,JSON.stringify(r));return r.value;}
await test('Prepare không ghi; caller sửa candidate không đổi bản riêng',async()=>{const h=harness(),p=await prepared(h);p.candidate.plans[0].current.tasks[0].title='Tampered';assert.equal(h.saves,0);assert.notEqual(h.controller.getProposal().plans[0].current.tasks[0].title,'Tampered');});
await test('Cancel không ghi và vô hiệu ticket',async()=>{const h=harness(),p=await prepared(h);assert.equal(h.controller.cancel(p.ticket).ok,true);assert.equal((await h.controller.confirm(p.ticket)).ok,false);assert.equal(h.saves,0);assert.equal(h.controller.getProposal(),null);});
await test('Confirm lưu plan và fingerprint cùng revision; giữ nguồn/profile',async()=>{const h=harness(),raw=h.raw,profile=structuredClone(h.disk.profile),p=await prepared(h),r=await committed(h,p.ticket);assert.equal(h.disk.revision,1);assert.equal(h.disk.plans.length,1);assert.equal(h.disk.imports.length,1);assert.deepEqual(h.disk.profile,profile);assert.equal(h.raw,raw);assert.equal(r.sourceRaw,raw);assert.equal(r.sourceStateAfterCommit,'unchanged');});
await test('Fingerprint đã nhập không tạo plan hoặc save thứ hai',async()=>{const h=harness(),p=await prepared(h);await committed(h,p.ticket);const r=await h.controller.prepare();assert.equal(r.ok,true);assert.equal(r.value.kind,'already-imported');assert.equal(h.saves,1);assert.equal(h.disk.plans.length,1);});
await test('Hai controller: tab sau nhận marker đã nhập, không ghi trùng',async()=>{const h=harness(),b=createLegacyMigration(h.deps),a=await prepared(h),p=await b.prepare();assert.equal(p.ok,true);await committed(h,a.ticket);const r=await b.confirm(p.value.ticket);assert.equal(r.ok,true);assert.equal(h.saves,1);assert.equal(h.disk.plans.length,1);});
await test('Lỗi save giữ IDs; retry chỉ tạo một plan',async()=>{const h=harness(),p=await prepared(h),proposal=h.controller.getProposal();h.failSave=true;assert.equal((await h.controller.confirm(p.ticket)).ok,false);assert.deepEqual(h.controller.getProposal(),proposal);assert.equal(h.disk.revision,0);h.failSave=false;await committed(h,p.ticket);assert.equal(h.disk.plans[0].id,proposal.plans[0].id);assert.equal(h.disk.imports.length,1);});
await test('Save pending không success sớm; chặn confirm/cancel/prepare',async()=>{const h=harness(),p=await prepared(h);let release;h.gate=new Promise(r=>release=r);let finished=false;const pending=h.controller.confirm(p.ticket).then(r=>{finished=true;return r;});while(h.saves===0)await new Promise(r=>setImmediate(r));assert.equal(finished,false);assert.equal(h.disk.imports.length,0);assert.equal((await h.controller.confirm(p.ticket)).ok,false);assert.equal(h.controller.cancel(p.ticket).ok,false);assert.equal((await h.controller.prepare()).ok,false);release();assert.equal((await pending).ok,true);});
await test('Workspace đổi revision: giữ đề xuất, không ghi đè',async()=>{const h=harness(),p=await prepared(h),proposal=h.controller.getProposal();h.disk.revision=1;h.disk.profile.displayName='Other tab';const r=await h.controller.confirm(p.ticket);assert.equal(r.ok,false);assert.equal(r.code,'conflict');assert.equal(h.saves,0);assert.equal(h.disk.profile.displayName,'Other tab');assert.deepEqual(h.controller.getProposal(),proposal);});
await test('Nguồn đổi sau preview chặn confirm',async()=>{const h=harness(),p=await prepared(h);h.raw+=' ';const r=await h.controller.confirm(p.ticket);assert.equal(r.ok,false);assert.equal(r.issues[0].code,'MIGRATION_SOURCE_CHANGED');assert.equal(h.saves,0);});
await test('Nguồn đổi khi prepare: không phát ticket cũ',async()=>{const h=harness();h.deps.persistence.loadWorkspace=async()=>{h.raw+=' ';return {ok:true,value:structuredClone(h.disk)};};const r=await h.controller.prepare();assert.equal(r.ok,false);assert.equal(r.issues[0].code,'MIGRATION_SOURCE_CHANGED');assert.equal(h.controller.getProposal(),null);});
await test('Nguồn đổi khi commit: báo changed, giữ raw đã chuyển',async()=>{const h=harness(),raw=h.raw,p=await prepared(h);h.afterCommit=()=>h.raw+=' ';const r=await committed(h,p.ticket);assert.equal(r.sourceStateAfterCommit,'changed');assert.equal(r.sourceRaw,raw);assert.equal(h.disk.imports.length,1);});
await test('Đọc nguồn lỗi sau commit: báo unreadable, không giả rollback',async()=>{const h=harness(),p=await prepared(h);h.afterCommit=()=>h.readThrows=true;const r=await committed(h,p.ticket);assert.equal(r.sourceStateAfterCommit,'unreadable');assert.equal(h.disk.revision,1);});
await test('Workspace có dữ liệu yêu cầu append rõ; giữ active/history/draft',async()=>{const h=harness(),p=await prepared(h);await committed(h,p.ticket);const old=structuredClone(h.disk);const f=JSON.parse(h.raw);f.tasks[0].notes+=' revised';h.raw=JSON.stringify(f);assert.equal((await h.controller.prepare()).ok,false);assert.equal((await h.controller.prepare({mode:'append'})).ok,false);const q=await prepared(h,{mode:'append',importDraft:false});await committed(h,q.ticket);assert.equal(h.disk.plans.length,2);assert.equal(h.disk.activePlanId,old.activePlanId);assert.deepEqual(h.disk.plans[0],old.plans[0]);assert.deepEqual(h.disk.drafts,old.drafts);assert.deepEqual(h.disk.profile,old.profile);});
await test('Factory trùng ID workspace bị chặn trước save',async()=>{const h=harness(),p=await prepared(h);await committed(h,p.ticket);h.raw+=' ';h.deps.context=()=>({...context(),nextId:()=>h.disk.plans[0].id});assert.equal((await h.controller.prepare({mode:'append',importDraft:false})).ok,false);assert.equal(h.saves,1);});
await test('Unmapped draft/credential chặn; bỏ nhập phải chọn rõ, nguồn còn nguyên',async()=>{const h=harness(),f=JSON.parse(h.raw);f.selected.push('unknown');f.credentials=['unknown'];h.raw=JSON.stringify(f);assert.equal((await h.controller.prepare()).ok,false);const p=await prepared(h,{importDraft:false,importCredentials:false});await committed(h,p.ticket);assert.deepEqual(h.disk.drafts,{});assert.deepEqual(h.disk.savedCredentialIds,[]);assert.equal(h.raw,JSON.stringify(f));});
await test('Profile/preferences chỉ nhập khi chọn rõ',async()=>{const h=harness(),p=await prepared(h,{importProfile:true,importPreferences:true});await committed(h,p.ticket);assert.equal(h.disk.profile.displayName,'Huy QA');assert.equal(h.disk.preferences.preferFree,true);});
await test('Validator throw được trả lỗi, không ghi',async()=>{const h=harness();h.deps.validate=()=>{throw Error('validator');};const r=await h.controller.prepare();assert.equal(r.ok,false);assert.equal(r.issues[0].code,'MIGRATION_VALIDATOR');assert.equal(h.saves,0);});
await test('Không nguồn hoặc reader lỗi không tạo defaults',async()=>{const h=harness();h.raw=null;assert.equal((await h.controller.prepare()).ok,false);h.readThrows=true;assert.equal((await h.controller.prepare()).code,'storage');assert.equal(h.saves,0);});
await test('Preview mới vô hiệu ticket trước đó',async()=>{const h=harness(),a=await prepared(h),b=await prepared(h);assert.notEqual(a.ticket,b.ticket);assert.equal((await h.controller.confirm(a.ticket)).ok,false);await committed(h,b.ticket);assert.equal(h.saves,1);});
const backupBuild=await build({stdin:{contents:"export * from './src/persistence/backup';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const {exportBackup,parseBackup,previewBackupImport,createBackupImport}=await import(`data:text/javascript;base64,${Buffer.from(backupBuild.outputFiles[0].text).toString('base64')}`);
const shapeValidators={workspace:validateRoadmapWorkspace,backup:value=>{
 if(!value||value.format!=='majorweave-backup'||value.formatVersion!==1||typeof value.exportedAt!=='string'||!Number.isFinite(Date.parse(value.exportedAt)))return {ok:false,code:'validation',issues:[{code:'QA_ENVELOPE',field:'backup',message:'Invalid envelope'}]};
 const w=validateRoadmapWorkspace(value.workspace);return w.ok?{ok:true,value:structuredClone(value)}:w;
}};
async function backupFixture(){const h=harness(),p=await prepared(h);await committed(h,p.ticket);return structuredClone(h.disk);}
const exportJSON=w=>{const r=exportBackup(w,{exportedAt:'2026-10-09T04:30:00Z',unsaved:false},shapeValidators);assert.equal(r.ok,true,JSON.stringify(r));return r.value.json;};
function importer(h){return createBackupImport({persistence:h.persistence,validators:shapeValidators,nextId:context().nextId});}
const prepareImport=async(c,raw,choices)=>{const r=await c.prepare(raw,choices);assert.equal(r.ok,true,JSON.stringify(r));return r.value;};
await test('Backup round trip giữ toàn workspace và không sửa đầu vào',async()=>{const w=await backupFixture(),before=structuredClone(w),r=parseBackup(exportJSON(w),shapeValidators);assert.equal(r.ok,true);assert.deepEqual(r.value.workspace,w);assert.deepEqual(w,before);});
await test('Export bản chưa lưu dùng snapshot cung cấp, có nhãn rõ',async()=>{const w=await backupFixture();w.plans[0].current.tasks[0].notes='Chưa lưu';const r=exportBackup(w,{exportedAt:'2026-10-09T04:30:00Z',unsaved:true},shapeValidators);assert.equal(r.ok,true);assert.equal(r.value.containsUnsavedChanges,true);assert.equal(r.value.file.workspace.plans[0].current.tasks[0].notes,'Chưa lưu');});
await test('Backup JSON/format/version hỏng bị từ chối',async()=>{for(const raw of ['{bad','null','[]','{}','{"format":"other","formatVersion":1}'])assert.equal(parseBackup(raw,shapeValidators).ok,false);const r=parseBackup('{"format":"majorweave-backup","formatVersion":99}',shapeValidators);assert.equal(r.code,'unsupported_version');});
await test('Export clock lỗi và workspace lỗi không dựng defaults',async()=>{assert.equal(exportBackup(emptyWorkspace('UTC'),{exportedAt:'2026-02-30T00:00:00Z',unsaved:false},shapeValidators).ok,false);assert.equal(exportBackup({},{exportedAt:'2026-10-09T04:30:00Z',unsaved:false},shapeValidators).ok,false);});
await test('Import dùng revision thiết bị, giữ profile/preferences/mục tiêu mặc định',async()=>{const w=await backupFixture();w.revision=77;w.profile.displayName='File profile';w.savedCredentialIds=['credential.custom'];const h=harness();h.disk.revision=3;h.disk.profile.displayName='Thiết bị';const c=importer(h),p=await prepareImport(c,exportJSON(w));assert.equal(p.fileRevision,77);assert.equal(p.candidate.revision,3);assert.deepEqual(p.candidate.profile,h.disk.profile);assert.deepEqual(p.candidate.preferences,h.disk.preferences);assert.deepEqual(p.candidate.savedCredentialIds,[]);assert.deepEqual(p.candidate.drafts,{});const r=await c.confirm(p.ticket);assert.equal(r.ok,true);assert.equal(r.value.revision,4);});
await test('Duplicate mặc định skip, không ghi hay tăng revision',async()=>{const w=await backupFixture(),h=harness();h.disk=structuredClone(w);const c=importer(h),p=await prepareImport(c,exportJSON(w));assert.deepEqual(p.skippedPlanIds,[w.plans[0].id]);assert.equal((await c.confirm(p.ticket)).ok,true);assert.equal(h.saves,0);assert.deepEqual(h.disk,w);});
await test('Copy remap current/history/closed snapshots/completion và marker',async()=>{const w=await backupFixture(),plan=w.plans[0];plan.history=[structuredClone(plan.current)];plan.history[0].id=context().nextId();const t=structuredClone(plan.current.tasks[0]);plan.current.closedWeeks=[{weekIndex:3,closedAt:'2026-10-09T04:00:00Z',tasks:[t],total:1,done:1,estimatedCompletedMinutes:t.minutes}];const raw=exportJSON(w),before=structuredClone(w),r=previewBackupImport(raw,w,{planActions:{[plan.id]:'copy'}},context().nextId,shapeValidators);assert.equal(r.ok,true,JSON.stringify(r));const copy=r.value.candidate.plans[1];assert.notEqual(copy.id,plan.id);assert.notEqual(copy.current.id,plan.current.id);assert.notEqual(copy.history[0].id,plan.history[0].id);assert.notEqual(copy.current.tasks[0].id,t.id);assert.notEqual(copy.completions[0].id,plan.completions[0].id);assert.equal(copy.completions[0].taskId,copy.current.tasks[0].id);assert.equal(copy.current.tasks[0].completionId,copy.completions[0].id);assert.equal(copy.history[0].tasks[0].id,copy.current.tasks[0].id);assert.equal(copy.current.closedWeeks[0].tasks[0].completionId,copy.completions[0].id);assert.equal(copy.current.tasks[0].source.id,t.source.id);assert.equal(copy.current.tasks[0].workId,t.workId);assert.equal(copy.current.tasks[0].notes,t.notes);assert.deepEqual(w,before);const q=previewBackupImport(raw,emptyWorkspace('UTC'),{planActions:{[plan.id]:'copy'}},context().nextId,shapeValidators);assert.equal(q.ok,true);assert.deepEqual(q.value.candidate.imports[0].planIds,[q.value.addedPlanIds[0]]);});
await test('Nested ID collision yêu cầu copy rõ, không tự đổi ID',async()=>{const w=await backupFixture(),other=structuredClone(w);other.plans[0].id=context().nextId();other.activePlanId=other.plans[0].id;other.imports=[];assert.equal(previewBackupImport(exportJSON(other),w,{},context().nextId,shapeValidators).ok,false);const r=previewBackupImport(exportJSON(other),w,{planActions:{[other.plans[0].id]:'copy'}},context().nextId,shapeValidators);assert.equal(r.ok,true);});
await test('Factory copy UUID lỗi/trùng bị từ chối',async()=>{const w=await backupFixture();for(const nextId of [()=>w.plans[0].id,()=> 'bad',()=>{throw Error('id');}])assert.equal(previewBackupImport(exportJSON(w),w,{planActions:{[w.plans[0].id]:'copy'}},nextId,shapeValidators).ok,false);});
await test('Nhập profile/preferences/draft/credential phải chọn rõ; draft hiện có giữ',async()=>{const w=await backupFixture();w.profile.displayName='File';w.preferences.preferFree=false;w.savedCredentialIds=['credential.saved'];const base=emptyWorkspace('UTC');base.drafts=structuredClone(w.drafts);base.drafts['backend.node'].goal='Device draft';const r=previewBackupImport(exportJSON(w),base,{importProfile:true,importPreferences:true,importDrafts:true,importCredentials:true},context().nextId,shapeValidators);assert.equal(r.ok,true);assert.equal(r.value.candidate.profile.displayName,'File');assert.equal(r.value.candidate.preferences.preferFree,false);assert.deepEqual(r.value.candidate.savedCredentialIds,['credential.saved']);assert.equal(r.value.candidate.drafts['backend.node'].goal,'Device draft');assert.deepEqual(r.value.skippedDraftTrackIds,['backend.node']);});
await test('Import cancel không ghi; ticket hết hiệu lực',async()=>{const w=await backupFixture(),h=harness(),c=importer(h),p=await prepareImport(c,exportJSON(w));assert.equal(c.cancel(p.ticket).ok,true);assert.equal((await c.confirm(p.ticket)).ok,false);assert.equal(h.saves,0);});
await test('Import caller tamper không thay candidate riêng',async()=>{const w=await backupFixture(),h=harness(),c=importer(h),p=await prepareImport(c,exportJSON(w)),title=p.candidate.plans[0].current.tasks[0].title;p.candidate.plans[0].current.tasks[0].title='Tamper';assert.equal((await c.confirm(p.ticket)).ok,true);assert.equal(h.disk.plans[0].current.tasks[0].title,title);});
await test('Import storage failure giữ bản copy/IDs để retry và xuất',async()=>{const w=await backupFixture(),h=harness(),c=importer(h),p=await prepareImport(c,exportJSON(w),{planActions:{[w.plans[0].id]:'copy'}}),candidate=c.getProposal();h.failSave=true;assert.equal((await c.confirm(p.ticket)).ok,false);assert.deepEqual(c.getProposal(),candidate);assert.equal(exportBackup(candidate,{exportedAt:'2026-10-09T04:30:00Z',unsaved:true},shapeValidators).ok,true);h.failSave=false;assert.equal((await c.confirm(p.ticket)).ok,true);assert.equal(h.disk.plans[0].id,candidate.plans[0].id);});
await test('Import revision conflict giữ bản đề xuất, không ghi đè',async()=>{const w=await backupFixture(),h=harness(),c=importer(h),p=await prepareImport(c,exportJSON(w)),candidate=c.getProposal();h.disk.revision++;h.disk.profile.displayName='Other';const r=await c.confirm(p.ticket);assert.equal(r.ok,false);assert.equal(r.code,'conflict');assert.deepEqual(c.getProposal(),candidate);assert.equal(h.saves,0);});
await test('Import pending chặn double submit và cancel; không success sớm',async()=>{const w=await backupFixture(),h=harness(),c=importer(h),p=await prepareImport(c,exportJSON(w));let release;h.gate=new Promise(r=>release=r);let done=false;const pending=c.confirm(p.ticket).then(r=>{done=true;return r;});while(h.saves===0)await new Promise(r=>setImmediate(r));assert.equal(done,false);assert.equal(h.disk.plans.length,0);assert.equal((await c.confirm(p.ticket)).ok,false);assert.equal(c.cancel(p.ticket).ok,false);assert.equal((await c.prepare(exportJSON(w))).ok,false);release();assert.equal((await pending).ok,true);});
await test('Backup validator throw và lựa chọn sai không ghi',async()=>{const w=await backupFixture();assert.equal(parseBackup(exportJSON(w),{...shapeValidators,backup:()=>{throw Error('validator');}}).ok,false);assert.equal(previewBackupImport(exportJSON(w),w,{planActions:{missing:'copy'}},context().nextId,shapeValidators).ok,false);});
console.log(`${pass} PASS / ${fail} FAIL — source + preview + migration/import controllers (memory port); native/semantic/UI có minh chứng riêng.`);
if(fail)process.exitCode=1;
