import { contentPacks } from '../../content';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, X, Server, LayoutTemplate, Gamepad2, ChartNoAxesCombined, Database, Brain, ShieldCheck, Cpu, Cloud, PenTool, BriefcaseBusiness, Search, GraduationCap, ChevronDown, Leaf } from 'lucide-react';
import { majorName } from '../../data';
import { faculties, paths } from '../../content/catalog';
import { catalogCheckedAt, catalogScopeNote, majorCoverageNotes, majorProfiles, majorPaths, relationRank } from '../../content/catalog';
import { ArrowDownRight as ArrowDownRightIcon } from 'lucide-react';
import { useApp } from '../../app/context';
import { Badge, External, RoadmapLinks, Dialog } from '../../components/ui';
const iconMap = { server: Server, layout: LayoutTemplate, game: Gamepad2, chart: ChartNoAxesCombined, database: Database, brain: Brain, shield: ShieldCheck, chip: Cpu, cloud: Cloud, pen: PenTool, business: BriefcaseBusiness };
export function Explore() {
  const { state, update } = useApp();
  const [preview, setPreview] = useState<(typeof paths)[number] | null>(null);
  const [pathQuery, setPathQuery] = useState('');
  const [pathCategory, setPathCategory] = useState('all');
  const [nearOnly, setNearOnly] = useState(false);
  useEffect(() => { if (!state.major) setNearOnly(false); }, [state.major]);
  const currentFaculty = faculties.find(f => f.majors.some(m => m.id === state.major));
  const browseMajors = faculties.find(f => f.id === state.browseFaculty)?.majors.map(m => m.id);
  const categoryNames: Record<string, string> = { SOFTWARE: 'Phần mềm', DATA: 'Dữ liệu', AI: 'Trí tuệ nhân tạo', BUSINESS: 'Nghiệp vụ & kinh doanh', INFRASTRUCTURE: 'Hạ tầng', SECURITY: 'An toàn thông tin', HARDWARE: 'Phần cứng', DESIGN: 'Thiết kế & truyền thông', RESEARCH: 'Nghiên cứu' };
  const visiblePaths = paths.filter(p => !browseMajors || [...p.majors, ...p.relatedMajors].some(m => browseMajors.includes(m))).filter(p => !nearOnly || relationRank(p, state.major) > 0).filter(p => pathCategory === 'all' || p.category === pathCategory).filter(p => `${p.name} ${p.summary} ${p.tags.join(' ')} ${p.foundations}`.toLocaleLowerCase().includes(pathQuery.trim().toLocaleLowerCase())).sort((a, b) => relationRank(b, state.major) - relationRank(a, state.major));
  const availablePaths = contentPacks.map(pack => pack.pathId);
  const clearFilters = () => { setPathQuery(''); setPathCategory('all'); setNearOnly(false); update({ browseFaculty: 'all' }); };
  return <div className="page explore-page">
    <div className="eyebrow page-eyebrow"><span className="little-line" /> YOUR NEXT CHAPTER</div>
    <section className="explore-hero"><div><h1>One major.<br />Many <em>possible paths.</em></h1><p>Ngành học là điểm bắt đầu. Khám phá những hướng bạn tò mò,<br className="desktop-break" /> chọn cách học và dành chỗ cho tiến bộ mỗi tuần.</p><Link className="text-link" to="/path?id=backend">Thử hành trình Backend <ArrowUpRight size={18} /></Link></div><div className="hero-sketch" aria-label="Khám phá, học và thực hành"><div className="sketch-top"><span>YOUR NEXT STEP</span><span>↗</span></div><svg viewBox="0 0 280 132" aria-hidden="true"><path d="M30 105 C60 108 92 20 131 40 S186 118 251 28" fill="none" stroke="currentColor" strokeWidth="1.5" strokeDasharray="4 6" /><circle cx="31" cy="103" r="7" fill="#fbfaf6" stroke="currentColor" /><circle cx="130" cy="40" r="7" fill="#eadfd1" stroke="currentColor" /><circle cx="250" cy="29" r="9" fill="#a74127" /><path d="m247 29 2 2 4-4" stroke="#fbfaf6" fill="none" /></svg><div className="sketch-caption"><span>Explore</span><span>Learn</span><span>Build</span></div><p>You don't need the whole map.<br /><em>Just a place to start.</em></p></div></section>
    <section className="profile-strip" aria-label="Hồ sơ ngành hiện tại"><div className="profile-intro"><span className="small-icon"><GraduationCap size={21} /></span><div><strong>Bạn đang học ngành nào?</strong><p>Dùng để ưu tiên gợi ý. Mọi hướng vẫn mở để khám phá.</p></div></div><div className="profile-fields"><label>Khoa hiện tại<select value={currentFaculty?.id || ''} onChange={e => update({ major: faculties.find(f => f.id === e.target.value)?.majors[0].id || '' })}><option value="">Chưa chọn / Bỏ qua</option>{faculties.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Ngành đang học<select aria-label="Ngành đang học" value={state.major} onChange={e => update({ major: e.target.value })}><option value="">Chưa chọn ngành</option>{(currentFaculty?.majors || []).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div></section>
    {majorCoverageNotes[state.major] && <div className="soft-note coverage-note"><strong>Phạm vi ngành đang học</strong><p>{majorCoverageNotes[state.major]}</p></div>}
    <details className="major-matrix"><summary><span>12 ngành · {paths.length} hướng khám phá</span><strong>Xem bảng ngành → hướng học</strong><ChevronDown size={18} /></summary><div className="matrix-intro"><p><strong>Gần nền tảng ngành:</strong> có nhiều kiến thức chung. <strong>Mở rộng:</strong> cần bổ sung nền tảng chuyên môn. Mối liên hệ là gợi ý do nhóm biên soạn, không phải kết luận về khả năng của từng sinh viên hoặc danh sách chuyên ngành chính thức.</p><p>{catalogScopeNote}</p><small>Đối chiếu ngành và roadmap: {catalogCheckedAt}. Gộp các biến thể chương trình về ngành gốc.</small></div><div className="matrix-scroll"><table><thead><tr><th>Khoa / ngành</th><th>Gần nền tảng ngành</th><th>Hướng mở rộng</th></tr></thead><tbody>{faculties.flatMap(f => f.majors.map(m => { const related = majorPaths(m.id); return <tr key={m.id}><th><span>{f.name}</span><button onClick={() => { update({ major: m.id, browseFaculty: 'all' }); setNearOnly(true); setPathQuery(''); setPathCategory('all'); }} aria-label={`Xem hướng của ${m.name}`}>{m.name}<ArrowDownRightIcon /></button><External href={majorProfiles[m.id].sourceUrl}>Thông tin ngành tại UIT</External></th><td>{related.primary.map(p => p.name).join(' · ') || majorCoverageNotes[m.id] || 'Chưa có hướng gần nền tảng trong phạm vi đã chọn.'}</td><td>{related.related.map(p => p.name).join(' · ') || 'Mọi hướng khác vẫn có thể khám phá; xem nền tảng cần bổ sung.'}</td></tr>; }))}</tbody></table></div></details>
    <div className="section-heading"><div><span className="eyebrow">A WORLD OF POSSIBILITIES</span><h2>Find your direction<span className="rust-text">.</span></h2></div><label className="browse-select"><span>Khám phá theo khoa</span><select value={state.browseFaculty} onChange={e => update({ browseFaculty: e.target.value })}><option value="all">Tất cả các khoa</option>{faculties.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div>
    <div className="path-catalog-toolbar"><label className="search-field"><Search size={17} /><input aria-label="Tìm hướng học" placeholder="Tìm Backend, Data Scientist, UI/UX…" value={pathQuery} onChange={e => setPathQuery(e.target.value)} /></label><label className="category-select">Nhóm hướng học<select aria-label="Nhóm hướng học" value={pathCategory} onChange={e => setPathCategory(e.target.value)}><option value="all">Tất cả nhóm</option>{Object.entries(categoryNames).filter(([id]) => paths.some(p => p.category === id)).map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={nearOnly} disabled={!state.major} onChange={e => setNearOnly(e.target.checked)} />Chỉ hướng gần / mở rộng từ ngành tôi</label></div>
    <div className="catalog-caption"><span>{visiblePaths.length} hướng học <span>·</span> Bạn có thể chọn khác ngành đang học</span><span className="sample-label"><span className="status-dot" /> {availablePaths.length} hướng có lộ trình chi tiết</span></div>
    <div className="path-grid">{visiblePaths.map(path => { const Icon = iconMap[path.icon as keyof typeof iconMap]; const isReady = availablePaths.includes(path.id); return <article key={path.id} className={`path-card ${path.sample ? 'featured' : ''}`}><div className="card-top"><span className={`path-icon ${path.sample ? 'rust-icon' : ''}`}><Icon size={25} strokeWidth={1.45} /></span>{path.sample ? <Badge tone="rust-badge">Bản trải nghiệm</Badge> : isReady ? <Badge tone="green-badge">Đã có lộ trình</Badge> : relationRank(path, state.major) === 2 ? <Badge>Gần nền tảng ngành</Badge> : relationRank(path, state.major) === 1 ? <Badge tone="green-badge">Hướng mở rộng</Badge> : <span className="eyebrow">{categoryNames[path.category]}</span>}</div><h3>{path.name}</h3><p>{path.summary}</p><div className="tag-list">{path.tags.map(tag => <span key={tag}>{tag}</span>)}</div><RoadmapLinks links={path.roadmaps} compact />{isReady ? <Link className="card-action" to={`/path?id=${path.id}`}>Khám phá hướng này <ArrowUpRight size={18} /></Link> : <button className="card-action" onClick={() => setPreview(path)}>Xem tổng quan <ArrowUpRight size={18} /></button>}</article>; })}</div>
    {!visiblePaths.length && <div className="empty-inline">{nearOnly && majorCoverageNotes[state.major] ? majorCoverageNotes[state.major] : 'Chưa có hướng học khớp các bộ lọc.'}<button className="text-link" onClick={clearFilters}>Xóa bộ lọc hướng học <ArrowRight size={15} /></button></div>}
    <div className="explore-note"><Leaf size={17} /><p>Các gợi ý giúp bạn khám phá hướng tự học. Nền tảng thực tế của bạn sẽ được điều chỉnh ở bước tạo roadmap.</p></div>
    {preview && <Dialog title={preview.name} eyebrow="EXPLORE A DIRECTION" onClose={() => setPreview(null)}><div className="dialog-body path-overview-body"><p>{preview.summary}</p><div className="tag-list">{preview.tags.map(t => <span key={t}>{t}</span>)}</div><h4>Nền tảng cần chuẩn bị</h4><p>{preview.foundations}</p><RoadmapLinks links={preview.roadmaps} /><h4>Ngành có nhiều nền tảng chung</h4><p>{preview.majors.map(majorName).join(' · ')}</p>{preview.relatedMajors.length > 0 && <><h4>Ngành có thể mở rộng sang hướng này</h4><p>{preview.relatedMajors.map(majorName).join(' · ')}</p></>}{state.major && <div className="soft-note"><strong>Ngành hiện tại: {majorName(state.major)}</strong><p>{majorProfiles[state.major].foundation} Bạn có thể đối chiếu với phần nền tảng của hướng này và học thêm các kiến thức còn thiếu.</p><External href={majorProfiles[state.major].sourceUrl}>Xem thông tin ngành tại UIT</External></div>}<div className="soft-note">Hướng này đang có phần tổng quan để bạn kiểm tra. Các hướng có lộ trình chi tiết được đánh dấu trong danh mục.</div><button className="secondary-button" onClick={() => setPreview(null)}>Tiếp tục khám phá <ArrowRight size={17} /></button></div></Dialog>}
  </div>;
}
