// src/content/paths/mobile.ts
// ContentPack cho hướng Mobile Developer — 4 track: Android, iOS, Flutter, React Native.
// reviewStatus='draft': biên soạn lần đầu, chờ Hải nghiệm thu.
// checkedAt=null: nguồn chưa được mở và xác minh — cần rà từng URL trước khi đẩy 'ready'.
// Ghi chú iOS: nội dung để học Swift/SwiftUI; không yêu cầu website MajorWeave chạy Swift.

import type { ContentPack } from '../../domain/contracts';

export const mobilePack: ContentPack = {
  schemaVersion: 1,
  contentVersion: '2026-10-05.initial',
  pathId: 'mobile',
  reviewStatus: 'draft',

  // ─── Resources ────────────────────────────────────────────────────────────
  // Nguồn xếp trước tracks/stages để tham chiếu rõ ràng hơn khi đọc.
  resources: [
    // ── Git chung ──────────────────────────────────────────────────────────
    {
      id: 'resource.mobile.git-docs',
      title: 'Git Documentation',
      provider: 'Git SCM',
      url: 'https://git-scm.com/doc',
      language: 'en', format: 'article', cost: 'free', level: 'introductory',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },

    // ── Kotlin / Android ───────────────────────────────────────────────────
    {
      id: 'resource.mobile.kotlinlang-docs',
      title: 'Kotlin Documentation',
      provider: 'JetBrains',
      url: 'https://kotlinlang.org/docs/home.html',
      language: 'en', format: 'article', cost: 'free', level: 'introductory',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.kotlin-koans',
      title: 'Kotlin Koans',
      provider: 'JetBrains',
      url: 'https://kotlinlang.org/docs/koans.html',
      language: 'en', format: 'exercise', cost: 'free', level: 'introductory',
      accessNote: 'Miễn phí, làm online hoặc trong IDE.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.android-fundamentals',
      title: 'Android Basics with Compose (Google Codelab)',
      provider: 'Google',
      url: 'https://developer.android.com/courses/android-basics-compose/course',
      language: 'en', format: 'course', cost: 'free', level: 'introductory',
      accessNote: 'Miễn phí; cần Android Studio.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.android-developers',
      title: 'Android Developer Guides',
      provider: 'Google',
      url: 'https://developer.android.com/guide',
      language: 'en', format: 'article', cost: 'free', level: 'mixed',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.compose-pathway',
      title: 'Jetpack Compose Pathway',
      provider: 'Google',
      url: 'https://developer.android.com/courses/pathways/compose',
      language: 'en', format: 'course', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí; cần Android Studio Hedgehog trở lên.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.compose-docs',
      title: 'Jetpack Compose Documentation',
      provider: 'Google',
      url: 'https://developer.android.com/jetpack/compose/documentation',
      language: 'en', format: 'article', cost: 'free', level: 'mixed',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.android-architecture',
      title: 'Guide to App Architecture',
      provider: 'Google',
      url: 'https://developer.android.com/topic/architecture',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.room-docs',
      title: 'Room Persistence Library',
      provider: 'Google',
      url: 'https://developer.android.com/training/data-storage/room',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.retrofit-docs',
      title: 'Retrofit Documentation',
      provider: 'Square',
      url: 'https://square.github.io/retrofit/',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.kotlin-coroutines-docs',
      title: 'Kotlin Coroutines Guide',
      provider: 'JetBrains',
      url: 'https://kotlinlang.org/docs/coroutines-guide.html',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.android-testing',
      title: 'Testing Android Apps (Codelab)',
      provider: 'Google',
      url: 'https://developer.android.com/codelabs/android-testing',
      language: 'en', format: 'lab', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, làm codelab trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.play-console-docs',
      title: 'Google Play Console Help',
      provider: 'Google',
      url: 'https://support.google.com/googleplay/android-developer',
      language: 'en', format: 'article', cost: 'free', level: 'mixed',
      accessNote: 'Tài liệu miễn phí. Tài khoản Play Console cần phí đăng ký một lần ~$25 USD.',
      checkedAt: null,
    },

    // ── Swift / iOS ────────────────────────────────────────────────────────
    {
      id: 'resource.mobile.swift-docs',
      title: 'The Swift Programming Language',
      provider: 'Apple',
      url: 'https://docs.swift.org/swift-book/documentation/the-swift-programming-language/',
      language: 'en', format: 'article', cost: 'free', level: 'introductory',
      accessNote: 'Miễn phí. Cần macOS để dùng Xcode đầy đủ.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.swift-tour',
      title: 'A Swift Tour (Swift Playgrounds)',
      provider: 'Apple',
      url: 'https://docs.swift.org/swift-book/documentation/the-swift-programming-language/guidedtour/',
      language: 'en', format: 'exercise', cost: 'free', level: 'introductory',
      accessNote: 'Miễn phí, chạy trong Swift Playgrounds hoặc Xcode.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.swiftui-tutorials',
      title: 'SwiftUI Tutorials',
      provider: 'Apple',
      url: 'https://developer.apple.com/tutorials/swiftui',
      language: 'en', format: 'course', cost: 'free', level: 'introductory',
      accessNote: 'Miễn phí. Cần Xcode trên macOS.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.swiftui-docs',
      title: 'SwiftUI Documentation',
      provider: 'Apple',
      url: 'https://developer.apple.com/documentation/swiftui',
      language: 'en', format: 'article', cost: 'free', level: 'mixed',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.swiftdata-docs',
      title: 'SwiftData Documentation',
      provider: 'Apple',
      url: 'https://developer.apple.com/documentation/swiftdata',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí. Yêu cầu iOS 17+ / macOS 14+.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.swiftui-combine',
      title: 'Combine Framework Documentation',
      provider: 'Apple',
      url: 'https://developer.apple.com/documentation/combine',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.urlsession-docs',
      title: 'URLSession Documentation',
      provider: 'Apple',
      url: 'https://developer.apple.com/documentation/foundation/urlsession',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.swift-concurrency-docs',
      title: 'Swift Concurrency (async/await)',
      provider: 'Apple',
      url: 'https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency/',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.xctest-docs',
      title: 'XCTest Documentation',
      provider: 'Apple',
      url: 'https://developer.apple.com/documentation/xctest',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí. Cần Xcode.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.appstore-connect-docs',
      title: 'App Store Connect Help',
      provider: 'Apple',
      url: 'https://developer.apple.com/help/app-store-connect/',
      language: 'en', format: 'article', cost: 'unknown', level: 'mixed',
      accessNote: 'Tài liệu miễn phí. Phát hành App Store cần Apple Developer Program ~$99 USD/năm.',
      checkedAt: null,
    },

    // ── Flutter / Dart ─────────────────────────────────────────────────────
    {
      id: 'resource.mobile.flutter-docs',
      title: 'Flutter Documentation',
      provider: 'Google',
      url: 'https://docs.flutter.dev',
      language: 'en', format: 'article', cost: 'free', level: 'introductory',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.dart-tour',
      title: 'Dart Language Tour',
      provider: 'Google / Dart team',
      url: 'https://dart.dev/language',
      language: 'en', format: 'article', cost: 'free', level: 'introductory',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.flutter-widget-catalog',
      title: 'Flutter Widget Catalog',
      provider: 'Google',
      url: 'https://docs.flutter.dev/ui/widgets',
      language: 'en', format: 'article', cost: 'free', level: 'mixed',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.flutter-codelabs',
      title: 'Flutter Codelabs',
      provider: 'Google',
      url: 'https://docs.flutter.dev/codelabs',
      language: 'en', format: 'lab', cost: 'free', level: 'introductory',
      accessNote: 'Miễn phí, làm codelab trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.riverpod-docs',
      title: 'Riverpod Documentation',
      provider: 'Remi Rousselet',
      url: 'https://riverpod.dev/docs/introduction/getting_started',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.flutter-bloc-docs',
      title: 'Bloc Library Documentation',
      provider: 'Felix Angelov / bloclibrary.dev',
      url: 'https://bloclibrary.dev',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.dio-docs',
      title: 'Dio Package (pub.dev)',
      provider: 'cfug',
      url: 'https://pub.dev/packages/dio',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên pub.dev.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.hive-docs',
      title: 'Hive NoSQL Database (pub.dev)',
      provider: 'hivedb',
      url: 'https://pub.dev/packages/hive',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên pub.dev.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.flutter-testing-docs',
      title: 'Flutter Testing Overview',
      provider: 'Google',
      url: 'https://docs.flutter.dev/testing/overview',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.github-actions-flutter',
      title: 'Flutter CI/CD with GitHub Actions',
      provider: 'Google / Flutter team',
      url: 'https://docs.flutter.dev/deployment/cd',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí. GitHub Actions free tier giới hạn số phút/tháng.',
      checkedAt: null,
    },

    // ── React Native ───────────────────────────────────────────────────────
    {
      id: 'resource.mobile.rn-docs',
      title: 'React Native Documentation',
      provider: 'Meta',
      url: 'https://reactnative.dev/docs/getting-started',
      language: 'en', format: 'article', cost: 'free', level: 'introductory',
      accessNote: 'Miễn phí. Cần Android Studio hoặc Xcode tùy nền tảng.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.expo-docs',
      title: 'Expo Documentation',
      provider: 'Expo',
      url: 'https://docs.expo.dev',
      language: 'en', format: 'article', cost: 'free', level: 'introductory',
      accessNote: 'Expo Go miễn phí; EAS Build có gói free giới hạn build/tháng.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.rn-core-components',
      title: 'React Native Core Components and APIs',
      provider: 'Meta',
      url: 'https://reactnative.dev/docs/components-and-apis',
      language: 'en', format: 'article', cost: 'free', level: 'introductory',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.react-navigation-docs',
      title: 'React Navigation Documentation',
      provider: 'React Navigation',
      url: 'https://reactnavigation.org/docs/getting-started',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.zustand-docs',
      title: 'Zustand Documentation',
      provider: 'pmndrs',
      url: 'https://docs.pmnd.rs/zustand/getting-started/introduction',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.redux-toolkit-docs',
      title: 'Redux Toolkit Documentation',
      provider: 'Redux',
      url: 'https://redux-toolkit.js.org/introduction/getting-started',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.rn-testing-docs',
      title: 'React Native Testing Library',
      provider: 'callstack',
      url: 'https://callstack.github.io/react-native-testing-library/',
      language: 'en', format: 'article', cost: 'free', level: 'intermediate',
      accessNote: 'Miễn phí, đọc trên web.',
      checkedAt: null,
    },
    {
      id: 'resource.mobile.eas-build-docs',
      title: 'EAS Build Documentation',
      provider: 'Expo',
      url: 'https://docs.expo.dev/build/introduction/',
      language: 'en', format: 'article', cost: 'mixed', level: 'intermediate',
      accessNote: 'Free tier giới hạn build/tháng; gói trả phí từ $29/tháng.',
      checkedAt: null,
    },
  ],

  // ─── Stages ───────────────────────────────────────────────────────────────
  stages: [

    // ── Chặng chung (dùng trong nhiều track) ──────────────────────────────
    {
      id: 'mobile.shared.git',
      title: 'Git và GitHub cơ bản',
      phase: 'foundation',
      description: 'Commit, branch, merge, pull request và giải quyết conflict.',
      outcome: 'Quản lý được lịch sử code cá nhân và đóng góp vào repo nhóm qua pull request.',
      prerequisiteIds: [],
      resourceIds: ['resource.mobile.git-docs'],
      defaultResourceId: 'resource.mobile.git-docs',
      optional: false,
      work: [
        {
          id: 'mobile.shared.git.w01',
          revision: 1,
          title: 'Init, commit, branch, merge và pull request',
          minutes: 60,
          acceptance: [
            'Tạo được repo, commit nhiều lần và merge branch không conflict.',
            'Mở được pull request trên GitHub và review diff.',
          ],
        },
      ],
    },
    {
      id: 'mobile.shared.kotlin-basics',
      title: 'Kotlin cơ bản',
      phase: 'foundation',
      description: 'Biến, hàm, điều kiện, vòng lặp, null safety, collection và extension function trong Kotlin.',
      outcome: 'Viết được chương trình Kotlin đơn giản có xử lý null và collection.',
      prerequisiteIds: [],
      resourceIds: ['resource.mobile.kotlinlang-docs', 'resource.mobile.kotlin-koans'],
      defaultResourceId: 'resource.mobile.kotlinlang-docs',
      optional: false,
      work: [
        {
          id: 'mobile.shared.kotlin-basics.w01',
          revision: 1,
          title: 'Biến, kiểu, hàm và null safety',
          minutes: 90,
          acceptance: [
            'Khai báo được var/val, kiểu nguyên thuỷ và String.',
            'Xử lý null bằng ?. và ?: không gây NullPointerException.',
          ],
        },
        {
          id: 'mobile.shared.kotlin-basics.w02',
          revision: 1,
          title: 'Collection, lambda và extension function',
          minutes: 90,
          acceptance: [
            'Dùng được map, filter, forEach trên List và Map.',
            'Viết được extension function đơn giản cho String.',
          ],
        },
      ],
    },

    // ── Android ────────────────────────────────────────────────────────────
    {
      id: 'mobile.android.setup',
      title: 'Cài đặt Android Studio và cấu trúc dự án',
      phase: 'foundation',
      description: 'Cài Android Studio, tạo project, hiểu Gradle, AVD emulator và cấu trúc thư mục.',
      outcome: 'Chạy được app Hello World trên emulator và thiết bị thực.',
      prerequisiteIds: ['mobile.shared.kotlin-basics'],
      resourceIds: ['resource.mobile.android-fundamentals', 'resource.mobile.android-developers'],
      defaultResourceId: 'resource.mobile.android-fundamentals',
      optional: false,
      work: [
        {
          id: 'mobile.android.setup.w01',
          revision: 1,
          title: 'Cài Android Studio và chạy emulator',
          minutes: 60,
          acceptance: [
            'Android Studio khởi động, AVD chạy được, app mẫu hiện trên emulator.',
            'Hiểu được vai trò của build.gradle và AndroidManifest.xml.',
          ],
        },
      ],
    },
    {
      id: 'mobile.android.ui',
      title: 'UI với Jetpack Compose',
      phase: 'build',
      description: 'Composable function, State, Column/Row/LazyColumn, theme và Material 3.',
      outcome: 'Xây được màn hình danh sách và chi tiết với theme nhất quán.',
      prerequisiteIds: ['mobile.android.setup'],
      resourceIds: ['resource.mobile.compose-pathway', 'resource.mobile.compose-docs'],
      defaultResourceId: 'resource.mobile.compose-pathway',
      optional: false,
      work: [
        {
          id: 'mobile.android.ui.w01',
          revision: 1,
          title: 'Composable cơ bản và quản lý State',
          minutes: 90,
          acceptance: [
            'Tạo được Composable hiển thị danh sách động từ List.',
            'State thay đổi làm UI recompose đúng.',
          ],
        },
        {
          id: 'mobile.android.ui.w02',
          revision: 1,
          title: 'LazyColumn, navigation và Material 3',
          minutes: 90,
          acceptance: [
            'LazyColumn cuộn được danh sách 50+ item không jank.',
            'Điều hướng từ danh sách sang chi tiết và back.',
          ],
        },
      ],
    },
    {
      id: 'mobile.android.architecture',
      title: 'Architecture: ViewModel, Room và Repository',
      phase: 'build',
      description: 'MVVM, ViewModel, StateFlow, Room database và Repository pattern.',
      outcome: 'Dữ liệu tồn tại sau khi xoay màn hình và tắt mở app; logic tách khỏi UI.',
      prerequisiteIds: ['mobile.android.ui'],
      resourceIds: ['resource.mobile.android-architecture', 'resource.mobile.room-docs'],
      defaultResourceId: 'resource.mobile.android-architecture',
      optional: false,
      work: [
        {
          id: 'mobile.android.architecture.w01',
          revision: 1,
          title: 'ViewModel và StateFlow',
          minutes: 90,
          acceptance: [
            'UI observe StateFlow; dữ liệu sống sót qua rotation.',
          ],
        },
        {
          id: 'mobile.android.architecture.w02',
          revision: 1,
          title: 'Room, DAO và Repository pattern',
          minutes: 90,
          acceptance: [
            'CRUD qua Room DAO; Repository là nguồn dữ liệu duy nhất của ViewModel.',
          ],
        },
      ],
    },
    {
      id: 'mobile.android.network',
      title: 'Gọi API với Retrofit và Coroutine',
      phase: 'build',
      description: 'Retrofit, Gson/Moshi, Kotlin Coroutine, xử lý lỗi và trạng thái loading.',
      outcome: 'App lấy được dữ liệu từ REST API, hiển thị loading và lỗi hợp lý.',
      prerequisiteIds: ['mobile.android.architecture'],
      resourceIds: ['resource.mobile.retrofit-docs', 'resource.mobile.kotlin-coroutines-docs'],
      defaultResourceId: 'resource.mobile.retrofit-docs',
      optional: false,
      work: [
        {
          id: 'mobile.android.network.w01',
          revision: 1,
          title: 'Retrofit + Coroutine, xử lý loading và error state',
          minutes: 90,
          acceptance: [
            'App hiển thị spinner khi đang tải.',
            'Hiển thị danh sách khi thành công và thông báo lỗi khi thất bại.',
          ],
        },
      ],
    },
    {
      id: 'mobile.android.publish',
      title: 'Kiểm thử và phát hành lên Google Play',
      phase: 'ship',
      description: 'Unit test với JUnit, UI test với Compose Testing, build release AAB và quy trình Play Console.',
      outcome: 'App có test cơ bản, build release được ký và sẵn sàng đăng ký Play Console.',
      prerequisiteIds: ['mobile.android.network'],
      resourceIds: ['resource.mobile.android-testing', 'resource.mobile.play-console-docs'],
      defaultResourceId: 'resource.mobile.android-testing',
      optional: false,
      work: [
        {
          id: 'mobile.android.publish.w01',
          revision: 1,
          title: 'Unit test ViewModel và UI test với Compose Testing',
          minutes: 90,
          acceptance: [
            'Ít nhất 3 unit test cho ViewModel và 2 UI test cho Composable chính đều pass.',
          ],
        },
        {
          id: 'mobile.android.publish.w02',
          revision: 1,
          title: 'Build release AAB và cấu hình Play Console',
          minutes: 60,
          acceptance: [
            'AAB build thành công có chữ ký; upload được lên Internal Testing track.',
          ],
        },
      ],
    },

    // ── iOS ────────────────────────────────────────────────────────────────
    {
      id: 'mobile.ios.setup',
      title: 'Xcode và Swift cơ bản',
      phase: 'foundation',
      description: 'Swift: biến, optional, struct, enum, protocol và Xcode IDE. Cần máy macOS để dùng Xcode.',
      outcome: 'Chạy được app Swift trên iOS Simulator, hiểu optional binding và protocol.',
      prerequisiteIds: ['mobile.shared.git'],
      resourceIds: ['resource.mobile.swift-docs', 'resource.mobile.swift-tour'],
      defaultResourceId: 'resource.mobile.swift-docs',
      optional: false,
      work: [
        {
          id: 'mobile.ios.setup.w01',
          revision: 1,
          title: 'Swift: optional, struct, enum và protocol',
          minutes: 90,
          acceptance: [
            'Viết được struct có computed property và conform một protocol tự định nghĩa.',
            'App Hello World chạy trên iOS Simulator.',
          ],
        },
      ],
    },
    {
      id: 'mobile.ios.ui',
      title: 'UI với SwiftUI',
      phase: 'build',
      description: 'View, @State, @Binding, List, NavigationStack và modifier chaining.',
      outcome: 'Xây được màn hình danh sách và chi tiết bằng SwiftUI.',
      prerequisiteIds: ['mobile.ios.setup'],
      resourceIds: ['resource.mobile.swiftui-tutorials', 'resource.mobile.swiftui-docs'],
      defaultResourceId: 'resource.mobile.swiftui-tutorials',
      optional: false,
      work: [
        {
          id: 'mobile.ios.ui.w01',
          revision: 1,
          title: 'SwiftUI cơ bản: View, @State và List',
          minutes: 90,
          acceptance: [
            'List render được mảng dữ liệu; @State cập nhật UI khi thay đổi.',
          ],
        },
        {
          id: 'mobile.ios.ui.w02',
          revision: 1,
          title: 'NavigationStack và chi tiết item',
          minutes: 90,
          acceptance: [
            'Tap vào item trong List điều hướng sang DetailView và back hoạt động.',
          ],
        },
      ],
    },
    {
      id: 'mobile.ios.architecture',
      title: 'Quản lý dữ liệu với @Observable và SwiftData',
      phase: 'build',
      description: 'MVVM với @Observable, SwiftData để lưu dữ liệu cục bộ.',
      outcome: 'Dữ liệu bền vững qua lần mở app; ViewModel tách logic khỏi View.',
      prerequisiteIds: ['mobile.ios.ui'],
      resourceIds: ['resource.mobile.swiftdata-docs', 'resource.mobile.swiftui-combine'],
      defaultResourceId: 'resource.mobile.swiftdata-docs',
      optional: false,
      work: [
        {
          id: 'mobile.ios.architecture.w01',
          revision: 1,
          title: '@Observable ViewModel và SwiftData Model',
          minutes: 90,
          acceptance: [
            'Thêm/xóa item lưu vào SwiftData, tồn tại sau khi tắt và mở lại app.',
          ],
        },
      ],
    },
    {
      id: 'mobile.ios.network',
      title: 'Gọi API với URLSession và async/await',
      phase: 'build',
      description: 'URLSession, Codable, async/await và xử lý lỗi theo kiểu.',
      outcome: 'App fetch được JSON từ public API, decode và hiển thị danh sách.',
      prerequisiteIds: ['mobile.ios.architecture'],
      resourceIds: ['resource.mobile.urlsession-docs', 'resource.mobile.swift-concurrency-docs'],
      defaultResourceId: 'resource.mobile.urlsession-docs',
      optional: false,
      work: [
        {
          id: 'mobile.ios.network.w01',
          revision: 1,
          title: 'URLSession + Codable + async/await, xử lý lỗi',
          minutes: 90,
          acceptance: [
            'Fetch JSON, decode thành struct Codable và hiển thị trên List.',
            'Lỗi network hiển thị Alert thay vì crash.',
          ],
        },
      ],
    },
    {
      id: 'mobile.ios.publish',
      title: 'Kiểm thử và phát hành lên App Store',
      phase: 'ship',
      description: 'XCTest, TestFlight, App Store Connect và quy trình review của Apple.',
      outcome: 'App có unit test, upload được lên TestFlight, cấu hình App Store Connect.',
      prerequisiteIds: ['mobile.ios.network'],
      resourceIds: ['resource.mobile.xctest-docs', 'resource.mobile.appstore-connect-docs'],
      defaultResourceId: 'resource.mobile.xctest-docs',
      optional: false,
      work: [
        {
          id: 'mobile.ios.publish.w01',
          revision: 1,
          title: 'XCTest unit test cho ViewModel',
          minutes: 75,
          acceptance: [
            'Ít nhất 3 test case kiểm tra logic ViewModel, không phụ thuộc UI.',
          ],
        },
        {
          id: 'mobile.ios.publish.w02',
          revision: 1,
          title: 'Archive và upload lên TestFlight',
          minutes: 60,
          acceptance: [
            'Build archive thành công; có thể cài qua TestFlight link nội bộ.',
            '(Nếu chưa có Apple Developer account: archive IPA local là đủ cho bài này.)',
          ],
        },
      ],
    },

    // ── Flutter ────────────────────────────────────────────────────────────
    {
      id: 'mobile.flutter.setup',
      title: 'Cài đặt Flutter/Dart và cấu trúc dự án',
      phase: 'foundation',
      description: 'Dart: type system, null safety, async/await, Stream. Flutter SDK và flutter doctor.',
      outcome: 'Chạy được Flutter app trên Android emulator hoặc iOS simulator.',
      prerequisiteIds: ['mobile.shared.git'],
      resourceIds: ['resource.mobile.flutter-docs', 'resource.mobile.dart-tour'],
      defaultResourceId: 'resource.mobile.flutter-docs',
      optional: false,
      work: [
        {
          id: 'mobile.flutter.setup.w01',
          revision: 1,
          title: 'Dart: null safety, async/await và Stream',
          minutes: 90,
          acceptance: [
            'Viết được Future và Stream trong Dart không có lỗi null safety.',
          ],
        },
        {
          id: 'mobile.flutter.setup.w02',
          revision: 1,
          title: 'Cài Flutter SDK và chạy Counter app',
          minutes: 60,
          acceptance: [
            'flutter doctor không có lỗi nghiêm trọng.',
            'Counter app chạy được trên emulator và hot reload hoạt động.',
          ],
        },
      ],
    },
    {
      id: 'mobile.flutter.ui',
      title: 'Widget cơ bản và layout',
      phase: 'build',
      description: 'StatelessWidget, StatefulWidget, Column/Row/ListView, Theme và MediaQuery.',
      outcome: 'Xây được màn hình responsive dùng đúng loại widget và theme.',
      prerequisiteIds: ['mobile.flutter.setup'],
      resourceIds: ['resource.mobile.flutter-codelabs', 'resource.mobile.flutter-widget-catalog'],
      defaultResourceId: 'resource.mobile.flutter-codelabs',
      optional: false,
      work: [
        {
          id: 'mobile.flutter.ui.w01',
          revision: 1,
          title: 'StatefulWidget, setState và ListView',
          minutes: 90,
          acceptance: [
            'ListView hiển thị danh sách động.',
            'setState cập nhật đúng item được chọn mà không rebuild toàn bộ.',
          ],
        },
      ],
    },
    {
      id: 'mobile.flutter.state',
      title: 'Quản lý state với Riverpod',
      phase: 'build',
      description: 'Riverpod StateNotifierProvider; tách UI khỏi business logic.',
      outcome: 'State được quản lý ngoài Widget; UI chỉ observe và render.',
      prerequisiteIds: ['mobile.flutter.ui'],
      resourceIds: ['resource.mobile.riverpod-docs', 'resource.mobile.flutter-bloc-docs'],
      defaultResourceId: 'resource.mobile.riverpod-docs',
      optional: false,
      work: [
        {
          id: 'mobile.flutter.state.w01',
          revision: 1,
          title: 'Riverpod StateNotifierProvider cho Todo list',
          minutes: 90,
          acceptance: [
            'Todo list dùng Riverpod; Widget không chứa logic nghiệp vụ.',
            'Thêm/xóa/đánh dấu xong cập nhật UI đúng.',
          ],
        },
      ],
    },
    {
      id: 'mobile.flutter.network',
      title: 'Gọi API và lưu trữ cục bộ với Hive',
      phase: 'build',
      description: 'Dio, json_serializable và Hive để cache offline.',
      outcome: 'App đồng bộ dữ liệu từ API và lưu cục bộ khi offline.',
      prerequisiteIds: ['mobile.flutter.state'],
      resourceIds: ['resource.mobile.dio-docs', 'resource.mobile.hive-docs'],
      defaultResourceId: 'resource.mobile.dio-docs',
      optional: false,
      work: [
        {
          id: 'mobile.flutter.network.w01',
          revision: 1,
          title: 'Dio + json_serializable + Hive offline cache',
          minutes: 90,
          acceptance: [
            'Fetch API, lưu vào Hive.',
            'Tắt mạng vẫn đọc được cache không lỗi.',
          ],
        },
      ],
    },
    {
      id: 'mobile.flutter.publish',
      title: 'Kiểm thử và phát hành đa nền tảng',
      phase: 'ship',
      description: 'Widget test, integration test, build APK/AAB và CI với GitHub Actions.',
      outcome: 'App có test cơ bản, build được cho Android, CI chạy tự động.',
      prerequisiteIds: ['mobile.flutter.network'],
      resourceIds: ['resource.mobile.flutter-testing-docs', 'resource.mobile.github-actions-flutter'],
      defaultResourceId: 'resource.mobile.flutter-testing-docs',
      optional: false,
      work: [
        {
          id: 'mobile.flutter.publish.w01',
          revision: 1,
          title: 'Widget test và integration test cơ bản',
          minutes: 90,
          acceptance: [
            'Ít nhất 2 widget test và 1 integration test chạy qua flutter test.',
          ],
        },
        {
          id: 'mobile.flutter.publish.w02',
          revision: 1,
          title: 'Build APK và cấu hình GitHub Actions',
          minutes: 75,
          acceptance: [
            'GitHub Actions tự chạy flutter test và flutter build apk khi push.',
          ],
        },
      ],
    },

    // ── React Native ───────────────────────────────────────────────────────
    {
      id: 'mobile.rn.setup',
      title: 'Cài đặt React Native / Expo và TypeScript',
      phase: 'foundation',
      description: 'React Native CLI hoặc Expo, TypeScript cơ bản, Metro bundler và cấu trúc dự án.',
      outcome: 'Chạy được RN app trên Android emulator; TypeScript compile không lỗi.',
      prerequisiteIds: ['mobile.shared.git'],
      resourceIds: ['resource.mobile.rn-docs', 'resource.mobile.expo-docs'],
      defaultResourceId: 'resource.mobile.expo-docs',
      optional: false,
      work: [
        {
          id: 'mobile.rn.setup.w01',
          revision: 1,
          title: 'Khởi tạo dự án Expo với TypeScript strict mode',
          minutes: 75,
          acceptance: [
            'Expo Go hiển thị "Hello World" trên thiết bị thực hoặc emulator.',
            'tsconfig.json cấu hình strict mode, không có lỗi TypeScript.',
          ],
        },
      ],
    },
    {
      id: 'mobile.rn.ui',
      title: 'Core Components và StyleSheet',
      phase: 'build',
      description: 'View, Text, Image, FlatList, TouchableOpacity, StyleSheet và Flexbox.',
      outcome: 'Xây được màn hình danh sách và form nhập liệu với keyboard handling.',
      prerequisiteIds: ['mobile.rn.setup'],
      resourceIds: ['resource.mobile.rn-core-components', 'resource.mobile.rn-docs'],
      defaultResourceId: 'resource.mobile.rn-core-components',
      optional: false,
      work: [
        {
          id: 'mobile.rn.ui.w01',
          revision: 1,
          title: 'FlatList, StyleSheet và Flexbox layout',
          minutes: 90,
          acceptance: [
            'FlatList render 50+ item với separator, cuộn mượt.',
            'Layout không bị overflow trên nhiều kích thước màn hình.',
          ],
        },
      ],
    },
    {
      id: 'mobile.rn.navigation',
      title: 'Navigation với React Navigation',
      phase: 'build',
      description: 'Stack, Tab và Drawer navigator; type-safe params với TypeScript.',
      outcome: 'App có nhiều tab, điều hướng stack type-safe từ danh sách sang chi tiết.',
      prerequisiteIds: ['mobile.rn.ui'],
      resourceIds: ['resource.mobile.react-navigation-docs'],
      defaultResourceId: 'resource.mobile.react-navigation-docs',
      optional: false,
      work: [
        {
          id: 'mobile.rn.navigation.w01',
          revision: 1,
          title: 'BottomTabNavigator + StackNavigator type-safe',
          minutes: 90,
          acceptance: [
            'Params được định kiểu TypeScript; báo lỗi khi truyền sai tham số điều hướng.',
            'Back button hoạt động đúng trên Android và iOS.',
          ],
        },
      ],
    },
    {
      id: 'mobile.rn.state',
      title: 'Quản lý state với Zustand và React Query',
      phase: 'build',
      description: 'Zustand store cho local state; React Query cho server state và cache.',
      outcome: 'State global nhất quán giữa các màn hình; server state được cache và refetch.',
      prerequisiteIds: ['mobile.rn.navigation'],
      resourceIds: ['resource.mobile.zustand-docs', 'resource.mobile.redux-toolkit-docs'],
      defaultResourceId: 'resource.mobile.zustand-docs',
      optional: false,
      work: [
        {
          id: 'mobile.rn.state.w01',
          revision: 1,
          title: 'Zustand store và React Query integration',
          minutes: 90,
          acceptance: [
            'Thêm item ở màn hình A hiện ngay ở màn hình B không cần reload.',
            'React Query cache dữ liệu API và refetch khi app focus lại.',
          ],
        },
      ],
    },
    {
      id: 'mobile.rn.publish',
      title: 'Kiểm thử và phát hành với EAS Build',
      phase: 'ship',
      description: 'Jest + React Native Testing Library, EAS Build và OTA update với Expo.',
      outcome: 'App có test, build được bằng EAS và phân phối qua store hoặc OTA.',
      prerequisiteIds: ['mobile.rn.state'],
      resourceIds: ['resource.mobile.rn-testing-docs', 'resource.mobile.eas-build-docs'],
      defaultResourceId: 'resource.mobile.rn-testing-docs',
      optional: false,
      work: [
        {
          id: 'mobile.rn.publish.w01',
          revision: 1,
          title: 'Jest + RNTL unit test và EAS Build cấu hình',
          minutes: 90,
          acceptance: [
            'Ít nhất 3 test component chạy qua jest.',
            'eas build --profile preview tạo được artifact thành công.',
          ],
        },
      ],
    },
  ],

  // ─── Credentials ─────────────────────────────────────────────────────────
  credentials: [
    {
      id: 'credential.mobile.associate-android-developer',
      name: 'Associate Android Developer (AAD)',
      provider: 'Google',
      kind: 'exam_certificate',
      url: 'https://developers.google.com/certification/associate-android-developer',
      cost: 'paid',
      prerequisites: 'Thành thạo Android development với Kotlin và Jetpack.',
      requirements: 'Thi thực hành code trong thời gian giới hạn; phí khoảng $149 USD. Kiểm tra trang chính thức để cập nhật phí.',
      checkedAt: null,
    },
    // Ghi chú: iOS không có chứng chỉ lập trình chính thức từ Apple tính đến lần biên soạn.
    // Flutter và React Native không có chứng chỉ nền tảng chính thức; portfolio là đầu ra chính.
  ],

  // ─── Tracks ───────────────────────────────────────────────────────────────
  tracks: [
    {
      id: 'mobile.android',
      pathId: 'mobile',
      label: 'Android / Kotlin',
      stageIds: [
        'mobile.shared.git',
        'mobile.shared.kotlin-basics',
        'mobile.android.setup',
        'mobile.android.ui',
        'mobile.android.architecture',
        'mobile.android.network',
        'mobile.android.publish',
      ],
      credentialIds: ['credential.mobile.associate-android-developer'],
      roadmapLinks: [
        { label: 'Android Developer Roadmap', url: 'https://roadmap.sh/android' },
      ],
      portfolio: {
        title: 'App quản lý ghi chú cá nhân (Android)',
        acceptance: [
          'CRUD ghi chú lưu bằng Room, hiển thị bằng Jetpack Compose.',
          'Fetch được dữ liệu bổ sung từ ít nhất một REST API.',
          'Có ≥3 unit test và ≥2 UI test chạy pass.',
          'Build release AAB ký thành công, có hướng dẫn cài đặt.',
        ],
      },
    },
    {
      id: 'mobile.ios',
      pathId: 'mobile',
      label: 'iOS / Swift',
      stageIds: [
        'mobile.shared.git',
        'mobile.ios.setup',
        'mobile.ios.ui',
        'mobile.ios.architecture',
        'mobile.ios.network',
        'mobile.ios.publish',
      ],
      credentialIds: [],
      roadmapLinks: [
        { label: 'iOS Developer Roadmap', url: 'https://roadmap.sh/ios' },
      ],
      portfolio: {
        title: 'App quản lý tác vụ (iOS / SwiftUI)',
        acceptance: [
          'CRUD tác vụ lưu bằng SwiftData, hiển thị bằng SwiftUI.',
          'Fetch được ít nhất một API bằng URLSession async/await.',
          'Có ≥3 XCTest unit test chạy pass.',
          'Archive IPA thành công (TestFlight nếu có Apple Developer account).',
        ],
      },
    },
    {
      id: 'mobile.flutter',
      pathId: 'mobile',
      label: 'Flutter / Dart',
      stageIds: [
        'mobile.shared.git',
        'mobile.flutter.setup',
        'mobile.flutter.ui',
        'mobile.flutter.state',
        'mobile.flutter.network',
        'mobile.flutter.publish',
      ],
      credentialIds: [],
      roadmapLinks: [
        { label: 'Flutter Roadmap', url: 'https://roadmap.sh/flutter' },
      ],
      portfolio: {
        title: 'App tin tức đa nền tảng (Android + iOS)',
        acceptance: [
          'Fetch danh sách bài viết từ public API, hiển thị và lưu offline bằng Hive.',
          'State quản lý bằng Riverpod.',
          'Build được APK không lỗi.',
          'Có ≥2 widget test chạy pass qua flutter test.',
        ],
      },
    },
    {
      id: 'mobile.react-native',
      pathId: 'mobile',
      label: 'React Native / TypeScript',
      stageIds: [
        'mobile.shared.git',
        'mobile.rn.setup',
        'mobile.rn.ui',
        'mobile.rn.navigation',
        'mobile.rn.state',
        'mobile.rn.publish',
      ],
      credentialIds: [],
      roadmapLinks: [
        { label: 'React Native Roadmap', url: 'https://roadmap.sh/react-native' },
      ],
      portfolio: {
        title: 'App theo dõi thói quen (React Native)',
        acceptance: [
          'CRUD thói quen lưu cục bộ bằng AsyncStorage hoặc MMKV.',
          'Tab navigation ≥2 tab, stack navigation type-safe.',
          'Server state đồng bộ qua React Query.',
          'Có ≥3 test component RNTL chạy pass; EAS Build tạo được artifact.',
        ],
      },
    },
  ],
};
