export const checkedAt = '03/10/2026';

export type BackendStack = 'node' | 'python' | 'java';
export const stacks = {
  node: { name: 'Node.js', language: 'JavaScript', framework: 'Express', languageModule: 'js', runtimeModule: 'node', apiModule: 'express', testModule: 'test', roadmap: 'https://roadmap.sh/nodejs' },
  python: { name: 'Python', language: 'Python', framework: 'FastAPI', languageModule: 'python', runtimeModule: 'python-runtime', apiModule: 'fastapi', testModule: 'pytest', roadmap: 'https://roadmap.sh/python' },
  java: { name: 'Java', language: 'Java', framework: 'Spring Boot', languageModule: 'java', runtimeModule: 'java-runtime', apiModule: 'spring', testModule: 'junit', roadmap: 'https://roadmap.sh/java' },
} as const;

import { faculties } from './catalog';
export { faculties } from './catalog';
export const majorName = (id: string) => faculties.flatMap(f => f.majors).find(m => m.id === id)?.name || 'Chưa chọn ngành';

export { paths } from './catalog';

export type Resource = {
  id: string; title: string; provider: string; url: string; language: 'vi' | 'en';
  format: 'Video' | 'Bài đọc' | 'Khóa học' | 'Thực hành'; cost: 'free' | 'mixed';
  modules: string[]; note: string; certificate?: boolean; stacks?: BackendStack[];
};
// Summaries and module assignments are authored for this prototype. External content is linked, never rehosted.
const originalResources: Resource[] = [
  { id: 'f8-js', title: 'JavaScript cơ bản', provider: 'F8', url: 'https://f8.edu.vn/courses/javascript-co-ban', language: 'vi', format: 'Video', cost: 'free', modules: ['js'], note: 'Bắt đầu với biến, hàm, mảng và đối tượng bằng tiếng Việt.' },
  { id: 'fcc', title: 'JavaScript & Backend learning paths', provider: 'freeCodeCamp', url: 'https://www.freecodecamp.org/learn/', language: 'en', format: 'Thực hành', cost: 'free', modules: ['js', 'node', 'express', 'sql'], note: 'Chọn phần học tương ứng trong danh mục; luyện qua bài tập và dự án.', certificate: true },
  { id: 'exercism', title: 'Luyện lập trình qua bài tập', provider: 'Exercism', url: 'https://exercism.org/', language: 'en', format: 'Thực hành', cost: 'free', modules: ['js'], note: 'Chọn JavaScript track để củng cố nền tảng bằng bài tập nhỏ.' },
  { id: 'progit', title: 'Pro Git · Git basics', provider: 'Git', url: 'https://git-scm.com/book/en/v2', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['git'], note: 'Ưu tiên các mục Git Basics và Git Branching.' },
  { id: 'http-mdn', title: 'Overview of HTTP', provider: 'MDN', url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['http'], note: 'Tìm hiểu request, response và cách trình duyệt giao tiếp với server.' },
  { id: 'mdn-server', title: 'Server-side website programming', provider: 'MDN', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['http'], note: 'Nhìn tổng thể nhiệm vụ của ứng dụng phía máy chủ.' },
  { id: 'f8-node', title: 'Node & ExpressJS', provider: 'F8', url: 'https://f8.edu.vn/courses/nodejs', language: 'vi', format: 'Video', cost: 'free', modules: ['node', 'express'], note: 'Khóa tiếng Việt để làm quen với Node.js và Express.' },
  { id: 'w3-node', title: 'Node.js Tutorial', provider: 'W3Schools', url: 'https://www.w3schools.com/nodejs/', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['node', 'express'], note: 'Các bài ngắn và ví dụ để thử từng khái niệm.' },
  { id: 'node-learn', title: 'Learn Node.js', provider: 'Node.js', url: 'https://nodejs.org/learn', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['node', 'test'], note: 'Tài liệu chính thức; xem Getting Started, HTTP và Testing.' },
  { id: 'mdn-express', title: 'Express / Node.js introduction', provider: 'MDN', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Server-side/Express_Nodejs/Introduction', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['express', 'auth'], note: 'Hiểu routing, middleware và cấu trúc ứng dụng Express.' },
  { id: 'odin', title: 'NodeJS course', provider: 'The Odin Project', url: 'https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs', language: 'en', format: 'Khóa học', cost: 'free', modules: ['node', 'express', 'sql', 'auth', 'test'], note: 'Học qua bài học và dự án; chọn bài phù hợp với chặng hiện tại.' },
  { id: 'fso', title: 'Full Stack Open', provider: 'University of Helsinki', url: 'https://fullstackopen.com/en/about/', language: 'en', format: 'Khóa học', cost: 'free', modules: ['express', 'test', 'deploy'], note: 'Dành cho người đã có nền tảng; xem phần Backend, testing và deployment.', certificate: true },
  { id: 'w3-sql', title: 'SQL Tutorial', provider: 'W3Schools', url: 'https://www.w3schools.com/sql/', language: 'en', format: 'Thực hành', cost: 'free', modules: ['sql'], note: 'Luyện SELECT, INSERT, UPDATE, DELETE và JOIN qua ví dụ.' },
  { id: 'postgres', title: 'PostgreSQL Tutorial', provider: 'PostgreSQL', url: 'https://www.postgresql.org/docs/current/tutorial.html', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['sql'], note: 'Tài liệu chính thức để bắt đầu với cơ sở dữ liệu quan hệ.' },
  { id: 'mongo', title: 'MongoDB University', provider: 'MongoDB', url: 'https://learn.mongodb.com/', language: 'en', format: 'Khóa học', cost: 'mixed', modules: [], note: 'Mở rộng sang NoSQL sau SQL; có khóa tự học miễn phí và chương trình trả phí. Đây là nguồn bổ sung, không thay cho bài học SQL.' },
  { id: 'portswigger', title: 'Authentication vulnerabilities', provider: 'PortSwigger', url: 'https://portswigger.net/web-security/authentication', language: 'en', format: 'Thực hành', cost: 'free', modules: ['auth'], note: 'Bài học và lab về rủi ro trong xác thực ứng dụng.' },
  { id: 'docker', title: 'Get started with Docker', provider: 'Docker', url: 'https://docs.docker.com/get-started/', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['deploy'], note: 'Bước mở rộng để đóng gói và chạy ứng dụng bằng container.' },
  { id: 'aws', title: 'AWS Skill Builder', provider: 'AWS', url: 'https://aws.amazon.com/training/digital/', language: 'en', format: 'Khóa học', cost: 'mixed', modules: ['deploy'], note: 'Khám phá triển khai trên AWS; có nội dung miễn phí và gói trả phí.' },
  { id: 'boot', title: 'Backend learning path', provider: 'Boot.dev', url: 'https://www.boot.dev/', language: 'en', format: 'Thực hành', cost: 'mixed', modules: ['http', 'sql'], note: 'Một lộ trình Backend bổ sung; tương tác đầy đủ cần gói thành viên sau phần dùng thử.' },
];

export const resources: Resource[] = [
  ...originalResources.map(r => ({ ...r, ...(['f8-js', 'fcc', 'exercism', 'f8-node', 'w3-node', 'node-learn', 'mdn-express', 'odin', 'fso'].includes(r.id) ? { stacks: ['node'] as BackendStack[] } : {}) })),
  { id: 'oop-js', title: 'Classes in JavaScript', provider: 'MDN', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Advanced_JavaScript_objects/Classes_in_JavaScript', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['oop'], stacks: ['node'], note: 'Học class, đối tượng và đóng gói; dùng để tổ chức một mô hình công việc nhỏ.' },
  { id: 'mit-dsa', title: '6.006 · Introduction to Algorithms', provider: 'MIT OpenCourseWare', url: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/', language: 'en', format: 'Khóa học', cost: 'free', modules: ['dsa'], note: 'Bài giảng và bài tập về cấu trúc dữ liệu, thuật toán, độ phức tạp. Cần nền tảng lập trình và toán; chặng mẫu chỉ chọn các bài nhập môn, không học hết khóa.' },
  { id: 'mdn-network', title: 'How does the Internet work?', provider: 'MDN', url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Howto/Web_mechanics/How_does_the_Internet_work', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['network'], note: 'Khởi đầu với mạng, địa chỉ IP, máy chủ và tên miền trước khi đọc tài liệu mạng chuyên sâu.' },
  { id: 'stanford-network', title: 'CS144 · Computer Networking', provider: 'Stanford', url: 'https://cs144.github.io/', language: 'en', format: 'Khóa học', cost: 'free', modules: ['network'], note: 'Tài liệu môn mạng để học sâu về TCP/IP. Các lab cần nền tảng C++ và hệ thống; không yêu cầu làm hết lab cho API đầu tiên.' },
  { id: 'ostep', title: 'Operating Systems: Three Easy Pieces', provider: 'University of Wisconsin–Madison', url: 'https://pages.cs.wisc.edu/~remzi/OSTEP/', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['os'], note: 'Các chương đọc miễn phí về process, memory, concurrency và file. Đọc phần khái niệm trước; bài lập trình hệ thống cần thêm C/Unix. Sách in và bản PDF đóng gói có thể trả phí.' },
  { id: 'mit-systems', title: '6.033 · Computer System Engineering', provider: 'MIT OpenCourseWare', url: 'https://ocw.mit.edu/courses/6-033-computer-system-engineering-spring-2018/', language: 'en', format: 'Khóa học', cost: 'free', modules: ['systems', 'design'], note: 'Đọc chọn lọc về client–server, tính mô-đun, hiệu năng và độ tin cậy. Khóa đầy đủ có mạng, OS và hệ phân tán; nên có nền tảng trước khi học sâu.' },
  { id: 'system-design', title: 'System Design roadmap', provider: 'roadmap.sh', url: 'https://roadmap.sh/system-design', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['design'], note: 'Bản đồ tham khảo cho chặng mở rộng: cache, cân bằng tải, scale và đánh đổi thiết kế. Chọn một chủ đề sau khi đã xây được API.' },
  { id: 'python-docs', title: 'The Python Tutorial', provider: 'Python', url: 'https://docs.python.org/3/tutorial/', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['python', 'python-runtime'], stacks: ['python'], note: 'Tài liệu chính thức cho người đã có hiểu biết lập trình; xem cấu trúc dữ liệu, module, exception và môi trường ảo.' },
  { id: 'python-mooc', title: 'Python Programming MOOC 2026', provider: 'University of Helsinki', url: 'https://programming-26.mooc.fi/', language: 'en', format: 'Khóa học', cost: 'free', modules: ['python', 'oop'], stacks: ['python'], note: 'Khóa từ nhập môn đến lập trình nâng cao, có bài tập. Chọn bài phù hợp; phần OOP nằm ở phần nâng cao.' },
  { id: 'python-oop', title: 'Python Tutorial · Classes', provider: 'Python', url: 'https://docs.python.org/3/tutorial/classes.html', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['oop'], stacks: ['python'], note: 'Class, instance, kế thừa và cách tổ chức đối tượng bằng Python.' },
  { id: 'fastapi', title: 'FastAPI · Tutorial', provider: 'FastAPI', url: 'https://fastapi.tiangolo.com/tutorial/', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['fastapi'], stacks: ['python'], note: 'Tạo route, request model, validation và API có tài liệu tương tác.' },
  { id: 'fastapi-sql', title: 'FastAPI · SQL databases', provider: 'FastAPI', url: 'https://fastapi.tiangolo.com/tutorial/sql-databases/', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['sql'], stacks: ['python'], note: 'Bổ sung sau các bài SQL: kết nối API với cơ sở dữ liệu bằng SQLModel.' },
  { id: 'fastapi-auth', title: 'FastAPI · OAuth2 and JWT', provider: 'FastAPI', url: 'https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['auth'], stacks: ['python'], note: 'Học hash mật khẩu, bearer token và lấy người dùng hiện tại; bổ sung kiểm tra quyền sở hữu công việc.' },
  { id: 'pytest', title: 'pytest · Get Started', provider: 'pytest', url: 'https://docs.pytest.org/en/stable/getting-started.html', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['pytest'], stacks: ['python'], note: 'Làm quen assert và test trong Python trước khi kiểm thử API.' },
  { id: 'fastapi-testing', title: 'FastAPI · Testing', provider: 'FastAPI', url: 'https://fastapi.tiangolo.com/tutorial/testing/', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['pytest'], stacks: ['python'], note: 'Kiểm thử route bằng TestClient và pytest; kiểm tra cả dữ liệu lỗi và truy cập sai quyền.' },
  { id: 'java-mooc', title: 'Java Programming I & II', provider: 'University of Helsinki', url: 'https://java-programming.mooc.fi/', language: 'en', format: 'Khóa học', cost: 'free', modules: ['java', 'oop'], stacks: ['java'], certificate: true, note: 'Bài học và bài tập Java/OOP. Đây là khóa legacy, không còn cập nhật hoặc cấp tín chỉ ECTS; trang khóa vẫn hướng dẫn nhận chứng nhận hoàn thành.' },
  { id: 'spring-build', title: 'Spring Boot · Build systems', provider: 'Spring', url: 'https://docs.spring.io/spring-boot/reference/using/build-systems.html', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['java-runtime'], stacks: ['java'], note: 'Chọn Maven hoặc Gradle, quản lý dependency và chạy một ứng dụng Spring Boot.' },
  { id: 'spring-rest', title: 'Building a RESTful Web Service', provider: 'Spring', url: 'https://spring.io/guides/gs/rest-service/', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['spring'], stacks: ['java'], note: 'Tạo controller và trả về JSON; mở rộng ví dụ thành API CRUD công việc.' },
  { id: 'spring-jpa', title: 'Accessing Data with JPA', provider: 'Spring', url: 'https://spring.io/guides/gs/accessing-data-jpa/', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['sql'], stacks: ['java'], note: 'Bổ sung sau SQL: entity, repository và lưu dữ liệu bằng Spring Data JPA.' },
  { id: 'spring-security', title: 'Securing a Web Application', provider: 'Spring', url: 'https://spring.io/guides/gs/securing-web/', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['auth'], stacks: ['java'], note: 'Làm quen Spring Security qua ứng dụng web; áp dụng kiểm tra đăng nhập và quyền cho API. Đây không phải hướng dẫn JWT đầy đủ.' },
  { id: 'spring-test', title: 'Testing the Web Layer', provider: 'Spring', url: 'https://spring.io/guides/gs/testing-web/', language: 'en', format: 'Bài đọc', cost: 'free', modules: ['junit'], stacks: ['java'], note: 'JUnit và MockMvc để kiểm thử controller, response và các tình huống API.' },
];
export const resourcesForStack = (stack: BackendStack) => resources.filter(r => !r.stacks || r.stacks.includes(stack));
export const sourcesForModule = (id: string, stack: BackendStack) => resourcesForStack(stack).filter(r => r.modules.includes(id));

export type Module = { id: string; title: string; phase: string; description: string; outcome: string; source: string; tasks: { title: string; minutes: number }[]; stacks?: BackendStack[]; optional?: boolean; roadmap?: string };
const originalModules: Module[] = [
  { id: 'js', title: 'JavaScript foundations', phase: 'FOUNDATION', description: 'Hàm, mảng, đối tượng và xử lý bất đồng bộ.', outcome: 'Viết được chương trình nhỏ và sử dụng Promise / async-await.', source: 'f8-js', tasks: [{ title: 'Ôn hàm, mảng và đối tượng trong JavaScript', minutes: 90 }, { title: 'Thực hành Promise và async / await', minutes: 90 }, { title: 'Làm bài tập xử lý danh sách công việc', minutes: 60 }] },
  { id: 'git', title: 'Git & your workspace', phase: 'FOUNDATION', description: 'Lưu thay đổi và tổ chức dự án từ bước đầu tiên.', outcome: 'Có repository cho dự án và biết commit, branch, push.', source: 'progit', tasks: [{ title: 'Thiết lập Git và repository cho dự án', minutes: 60 }, { title: 'Thực hành commit, branch và push', minutes: 60 }] },
  { id: 'http', title: 'HTTP & the web', phase: 'FOUNDATION', description: 'Request, response, method và status code.', outcome: 'Giải thích được một request và response của API.', source: 'http-mdn', tasks: [{ title: 'Đọc về request, response và HTTP methods', minutes: 60 }, { title: 'Quan sát một API bằng công cụ của trình duyệt', minutes: 60 }] },
  { id: 'node', title: 'Node.js essentials', phase: 'BUILD', description: 'Chạy JavaScript phía máy chủ, module và npm.', outcome: 'Tạo được máy chủ HTTP trả về dữ liệu JSON.', source: 'f8-node', tasks: [{ title: 'Cài Node.js và chạy chương trình đầu tiên', minutes: 60 }, { title: 'Thử module và quản lý gói bằng npm', minutes: 90 }, { title: 'Tạo máy chủ trả về danh sách công việc', minutes: 90 }] },
  { id: 'express', title: 'Build your first API', phase: 'BUILD', description: 'Routing, middleware và API thêm, sửa, xóa.', outcome: 'API có các thao tác CRUD và xử lý dữ liệu đầu vào.', source: 'f8-node', tasks: [{ title: 'Tạo Express app và các route đầu tiên', minutes: 90 }, { title: 'Viết API thêm, sửa và xóa công việc', minutes: 120 }, { title: 'Kiểm tra đầu vào và xử lý lỗi', minutes: 90 }] },
  { id: 'sql', title: 'SQL & data persistence', phase: 'BUILD', description: 'Bảng, truy vấn và lưu dữ liệu của ứng dụng.', outcome: 'Lưu và truy vấn công việc trong cơ sở dữ liệu SQL.', source: 'w3-sql', tasks: [{ title: 'Luyện SELECT, INSERT, UPDATE và DELETE', minutes: 90 }, { title: 'Thiết kế bảng users và tasks', minutes: 90 }, { title: 'Kết nối API với cơ sở dữ liệu', minutes: 120 }] },
  { id: 'auth', title: 'Authentication & safety', phase: 'SHIP', description: 'Đăng nhập, quyền truy cập và các lỗi thường gặp.', outcome: 'Bảo vệ route và giữ việc của mỗi người dùng riêng biệt.', source: 'mdn-express', tasks: [{ title: 'Tìm hiểu đăng nhập và kiểm tra quyền', minutes: 90 }, { title: 'Thêm xác thực và bảo vệ API công việc', minutes: 120 }, { title: 'Kiểm tra các tình huống truy cập sai quyền', minutes: 60 }] },
  { id: 'test', title: 'Test what you build', phase: 'SHIP', description: 'Kiểm tra trường hợp đúng, sai và dữ liệu thiếu.', outcome: 'Có kiểm thử cho CRUD, đầu vào và quyền truy cập.', source: 'node-learn', tasks: [{ title: 'Viết kiểm thử cho API CRUD', minutes: 90 }, { title: 'Kiểm thử dữ liệu lỗi và quyền truy cập', minutes: 90 }] },
  { id: 'deploy', title: 'Ship a small project', phase: 'SHIP', description: 'Cấu hình, đưa ứng dụng lên mạng và viết README.', outcome: 'Có API chạy được và tài liệu để người khác thử.', source: 'fso', tasks: [{ title: 'Chuẩn bị cấu hình và biến môi trường', minutes: 60 }, { title: 'Triển khai API và kiểm tra đường dẫn', minutes: 120 }, { title: 'Viết README và ghi lại điều đã học', minutes: 90 }] },
];

const foundationModules: Module[] = [
  { id: 'oop', title: 'Object-Oriented Programming', phase: 'FOUNDATION', description: 'Nhập môn class, đối tượng, đóng gói và trách nhiệm của từng thành phần.', outcome: 'Tạo mô hình User / Task bằng ngôn ngữ đang chọn và giải thích cách tổ chức mã.', source: 'oop-js', tasks: [{ title: 'Ôn class, đối tượng và đóng gói', minutes: 90 }, { title: 'Mô hình hóa User và Task bằng OOP', minutes: 90 }] },
  { id: 'dsa', title: 'Data Structures & Algorithms', phase: 'FOUNDATION', description: 'Nhập môn Big O, mảng, hash map, stack / queue và tìm kiếm.', outcome: 'Chọn cấu trúc dữ liệu cho danh sách công việc và so sánh độ phức tạp của hai cách tìm kiếm.', source: 'mit-dsa', roadmap: 'https://roadmap.sh/datastructures-and-algorithms', tasks: [{ title: 'Đọc nhập môn Big O và phân tích một vòng lặp', minutes: 90 }, { title: 'Thực hành mảng, hash map, stack và queue', minutes: 90 }, { title: 'So sánh tìm kiếm tuyến tính và nhị phân', minutes: 90 }] },
  { id: 'network', title: 'Computer Networking', phase: 'FOUNDATION', description: 'Nhập môn IP, DNS, port, TCP và TLS trong một lần gọi API.', outcome: 'Mô tả được đường đi từ tên miền đến máy chủ và phân biệt TCP với HTTP.', source: 'mdn-network', tasks: [{ title: 'Tìm hiểu IP, DNS và port khi mở một website', minutes: 60 }, { title: 'Đọc về TCP và TLS; vẽ đường đi của request', minutes: 60 }, { title: 'Thử tra DNS và gửi request đến API', minutes: 60 }] },
  { id: 'os', title: 'Operating Systems & Linux', phase: 'FOUNDATION', description: 'Nhập môn process, thread, memory, file và quyền truy cập.', outcome: 'Giải thích được tiến trình máy chủ và thao tác với file / process trên môi trường Linux.', source: 'ostep', tasks: [{ title: 'Đọc các khái niệm process, thread và memory', minutes: 90 }, { title: 'Tìm hiểu file, I/O và quyền truy cập', minutes: 90 }, { title: 'Thực hành lệnh file và quan sát process trên Linux', minutes: 60 }] },
  { id: 'systems', title: 'Computer Systems · first principles', phase: 'FOUNDATION', description: 'Các lớp của hệ thống: chương trình, OS, mạng và lưu trữ.', outcome: 'Vẽ được các thành phần của API đầu tiên, chỉ ra nơi xử lý, lưu dữ liệu và các điểm có thể lỗi.', source: 'mit-systems', roadmap: 'https://roadmap.sh/computer-science', tasks: [{ title: 'Đọc chọn lọc về client–server và tính mô-đun', minutes: 90 }, { title: 'Vẽ luồng dữ liệu và điểm có thể lỗi của API công việc', minutes: 90 }] },
  { id: 'design', title: 'System Design · next steps', phase: 'EXPAND', optional: true, description: 'Mở rộng sau API đầu tiên: cache, scale, cân bằng tải và đánh đổi.', outcome: 'Phác thảo một phương án mở rộng API và giải thích một đánh đổi thiết kế.', source: 'system-design', roadmap: 'https://roadmap.sh/system-design', tasks: [{ title: 'Tìm hiểu cache, cân bằng tải và khả năng mở rộng', minutes: 90 }, { title: 'Phác thảo thiết kế mở rộng và ghi lại đánh đổi', minutes: 90 }] },
];
const branchModules: Module[] = [
  { id: 'python', title: 'Python foundations', phase: 'FOUNDATION', stacks: ['python'], description: 'Hàm, list, dict, exception và module trong Python.', outcome: 'Viết chương trình quản lý danh sách công việc bằng Python.', source: 'python-mooc', tasks: [{ title: 'Ôn hàm, list và dict trong Python', minutes: 90 }, { title: 'Thực hành exception và module', minutes: 90 }, { title: 'Làm bài tập quản lý danh sách công việc bằng Python', minutes: 60 }] },
  { id: 'python-runtime', title: 'Python environment & packages', phase: 'BUILD', stacks: ['python'], description: 'Môi trường ảo, pip và dependency của dự án.', outcome: 'Chạy dự án Python trong môi trường riêng và ghi lại dependency.', source: 'python-docs', tasks: [{ title: 'Cài Python, tạo môi trường ảo và chạy chương trình', minutes: 60 }, { title: 'Cài gói bằng pip và ghi lại dependency', minutes: 60 }] },
  { id: 'fastapi', title: 'Build an API with FastAPI', phase: 'BUILD', stacks: ['python'], description: 'Route, request model, validation và API CRUD.', outcome: 'Có API công việc và tài liệu OpenAPI để thử request.', source: 'fastapi', tasks: [{ title: 'Tạo FastAPI app và route trả về JSON', minutes: 90 }, { title: 'Viết API thêm, sửa và xóa công việc với FastAPI', minutes: 120 }, { title: 'Kiểm tra request model và xử lý lỗi', minutes: 90 }] },
  { id: 'pytest', title: 'Test your Python API', phase: 'SHIP', stacks: ['python'], description: 'pytest và TestClient cho API FastAPI.', outcome: 'Có kiểm thử CRUD, đầu vào và quyền truy cập bằng Python.', source: 'fastapi-testing', tasks: [{ title: 'Làm quen pytest và TestClient', minutes: 90 }, { title: 'Kiểm thử CRUD, dữ liệu lỗi và quyền truy cập', minutes: 90 }] },
  { id: 'java', title: 'Java foundations', phase: 'FOUNDATION', stacks: ['java'], description: 'Kiểu dữ liệu, hàm, collections và exception trong Java.', outcome: 'Viết chương trình quản lý danh sách công việc bằng Java.', source: 'java-mooc', tasks: [{ title: 'Ôn kiểu dữ liệu, vòng lặp và phương thức Java', minutes: 90 }, { title: 'Thực hành collections và exception', minutes: 90 }, { title: 'Làm bài tập quản lý danh sách công việc bằng Java', minutes: 60 }] },
  { id: 'java-runtime', title: 'JDK & Maven / Gradle', phase: 'BUILD', stacks: ['java'], description: 'JDK, dependency và cách chạy ứng dụng Spring Boot.', outcome: 'Build và chạy được ứng dụng Java với một công cụ quản lý dependency.', source: 'spring-build', tasks: [{ title: 'Chuẩn bị JDK và tạo dự án Spring Boot', minutes: 60 }, { title: 'Thử build, dependency và chạy dự án bằng Maven hoặc Gradle', minutes: 90 }] },
  { id: 'spring', title: 'Build an API with Spring Boot', phase: 'BUILD', stacks: ['java'], description: 'Controller, service, request / response và API CRUD.', outcome: 'API công việc trả về JSON, chia controller / service và kiểm tra đầu vào.', source: 'spring-rest', tasks: [{ title: 'Tạo controller và route trả về JSON', minutes: 90 }, { title: 'Viết API CRUD công việc và lớp service', minutes: 120 }, { title: 'Kiểm tra đầu vào và xử lý exception', minutes: 90 }] },
  { id: 'junit', title: 'Test your Java API', phase: 'SHIP', stacks: ['java'], description: 'JUnit và MockMvc cho các tình huống API.', outcome: 'Có kiểm thử CRUD, đầu vào và quyền truy cập bằng Java.', source: 'spring-test', tasks: [{ title: 'Làm quen JUnit và MockMvc', minutes: 90 }, { title: 'Kiểm thử CRUD, dữ liệu lỗi và quyền truy cập', minutes: 90 }] },
];
export const modules: Module[] = [
  ...originalModules.map(m => ({ ...m, ...(['js', 'node', 'express', 'test'].includes(m.id) ? { stacks: ['node'] as BackendStack[] } : {}) })),
  ...foundationModules, ...branchModules,
];
export function modulesForStack(stack: BackendStack) {
  const branch = stacks[stack];
  const order = [branch.languageModule, 'oop', 'dsa', 'git', 'network', 'os', 'systems', 'http', branch.runtimeModule, branch.apiModule, 'sql', 'auth', branch.testModule, 'deploy', 'design'];
  return order.map(id => modules.find(m => m.id === id)!);
}
export const defaultSelected = (stack: BackendStack) => modulesForStack(stack).filter(m => !m.optional).map(m => m.id);
export function defaultSource(module: Module, stack: BackendStack) {
  const overrides: Partial<Record<BackendStack, Record<string, string>>> = {
    python: { oop: 'python-oop', auth: 'fastapi-auth', deploy: 'docker' },
    java: { oop: 'java-mooc', auth: 'spring-security', deploy: 'docker' },
  };
  return overrides[stack]?.[module.id] || module.source;
}
export function sourceForModule(id: string, stack: BackendStack, sourceByModule: Record<string, string>) {
  const m = modules.find(m => m.id === id)!;
  return sourcesForModule(id, stack).find(r => r.id === sourceByModule[id])?.id || defaultSource(m, stack);
}

export const credentials = [
  { id: 'fso-cert', name: 'Full Stack Open Certificate', provider: 'University of Helsinki', type: 'Chứng nhận khóa học', price: 'Miễn phí', stage: 'Sau nền tảng', stacks: ['node'] as BackendStack[], note: 'Hoàn thành đủ bài tập theo quy định của chương trình. Khóa học rộng hơn lộ trình mẫu này.', url: 'https://fullstackopen.com/en/part0/general_info/' },
  { id: 'fcc-cert', name: 'freeCodeCamp Certifications', provider: 'freeCodeCamp', type: 'Chứng nhận chương trình', price: 'Miễn phí', stage: 'Theo chương trình', note: 'Chọn chương trình phù hợp với kỹ năng cần bổ sung trong danh mục hiện hành và hoàn thành yêu cầu của nền tảng.', url: 'https://www.freecodecamp.org/learn/' },
  { id: 'mongo-cert', name: 'MongoDB Associate Developer', provider: 'MongoDB', type: 'Chứng chỉ thi', price: 'Xem phí chính thức', stage: 'Khi chọn MongoDB', note: 'Bổ trợ cho nhánh dùng MongoDB. Nên học và thực hành MongoDB trước khi thi.', url: 'https://learn.mongodb.com/pages/mongodb-associate-developer-exam' },
  { id: 'aws-cert', name: 'AWS Developer · Associate', provider: 'AWS', type: 'Chứng chỉ thi', price: 'Xem phí chính thức', stage: 'Khi học AWS', note: 'Dành cho phát triển ứng dụng trên AWS. Hãng khuyến nghị ít nhất một năm kinh nghiệm thực hành AWS.', url: 'https://aws.amazon.com/certification/certified-developer-associate/' },
  { id: 'gcp-cert', name: 'Professional Cloud Developer', provider: 'Google Cloud', type: 'Chứng chỉ thi', price: 'Xem phí chính thức', stage: 'Khi học Google Cloud', note: 'Chọn khi đã có nền tảng và kinh nghiệm phát triển ứng dụng trên Google Cloud.', url: 'https://cloud.google.com/learn/certification/cloud-developer' },
  { id: 'ms-skills', name: 'Microsoft Applied Skills', provider: 'Microsoft', type: 'Chứng nhận thực hành', price: 'Xem điều kiện chính thức', stage: 'Khi học Azure', note: 'Chọn bài đánh giá phù hợp với kỹ năng và dịch vụ Azure bạn muốn phát triển.', url: 'https://learn.microsoft.com/en-us/credentials/applied-skills' },
  { id: 'cs50p-cert', name: 'CS50P · Python Certificate', provider: 'Harvard CS50', type: 'Chứng nhận khóa học', price: 'Miễn phí', stage: 'Nền tảng Python', stacks: ['python'] as BackendStack[], note: 'Đáp ứng yêu cầu bài tập và dự án cuối khóa CS50P. Đây là chứng nhận lập trình Python, không phải chứng chỉ Backend hoặc bản verified trả phí của edX.', url: 'https://cs50.harvard.edu/python/certificate/' },
  { id: 'java-mooc-cert', name: 'Java Programming I / II Certificate', provider: 'University of Helsinki', type: 'Chứng nhận khóa học', price: 'Miễn phí', stage: 'Nền tảng Java', stacks: ['java'] as BackendStack[], note: 'Trang khóa legacy hướng dẫn chứng nhận riêng cho từng phần. Khóa không còn cập nhật hoặc cấp tín chỉ ECTS; kiểm tra yêu cầu trên trang trước khi bắt đầu.', url: 'https://java-programming.mooc.fi/' },
];
export const credentialsForStack = (stack: BackendStack) => credentials.filter(c => !c.stacks || c.stacks.includes(stack));
