import React, { createContext, useContext, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { HashRouter, NavLink, Routes, Route, Navigate, useLocation, useNavigate, Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, ArrowLeft, Check, X, Plus, Compass, Route as RouteIcon, CalendarDays, BookOpen, Server, LayoutTemplate, Gamepad2, ChartNoAxesCombined, Database, Brain, ShieldCheck, Cpu, Cloud, PenTool, BriefcaseBusiness, Sprout, CheckCheck, ExternalLink, Search, Clock3, GraduationCap, Bookmark, ChevronDown, ChevronUp, ChevronLeft, ChevronRight, Pencil, Leaf, CircleHelp, UserRound } from 'lucide-react';
import { checkedAt, faculties, paths, majorName, modules, resources, credentials, stacks, modulesForStack, resourcesForStack, sourcesForModule, sourceForModule, credentialsForStack, type BackendStack, type Resource, type Module } from './data';
import { catalogCheckedAt, catalogScopeNote, majorCoverageNotes, majorProfiles, majorPaths, relationRank } from './catalog';
import { ArrowDownRight as ArrowDownRightIcon } from 'lucide-react';
import { defaults, generatePlan, hoursText, loadState, STORAGE_KEY, weekDate, shortDate, stackPatch, type State, type Task } from './state';
import { StackChooser } from './StackChooser';
import { Profile } from './Profile';
import './styles.css';

type AppContext = { state: State; update: (patch: Partial<State>) => void; toast: (message: string) => void; openModule: (id: string) => void };
const Context = createContext<AppContext>(null!);
const useApp = () => useContext(Context);
const iconMap = { server: Server, layout: LayoutTemplate, game: Gamepad2, chart: ChartNoAxesCombined, database: Database, brain: Brain, shield: ShieldCheck, chip: Cpu, cloud: Cloud, pen: PenTool, business: BriefcaseBusiness };
const providerColors: Record<string, string> = { 'F8': 'rust', 'freeCodeCamp': 'ink', 'W3Schools': 'green', 'MDN': 'ink', 'Node.js': 'green', 'The Odin Project': 'ochre', 'University of Helsinki': 'blue', 'MongoDB': 'green', 'Git': 'rust', 'PostgreSQL': 'blue', 'AWS': 'ochre', 'Docker': 'blue', 'PortSwigger': 'rust', 'Boot.dev': 'blue', 'Exercism': 'ochre' };
function ProviderMark({ name }: { name: string }) { return <span className={`provider-mark ${providerColors[name] || 'ink'}`} aria-hidden="true">{name === 'freeCodeCamp' ? '</>' : name === 'University of Helsinki' ? 'UH' : name === 'The Odin Project' ? 'O' : name === 'W3Schools' ? 'W3' : name.slice(0, 2)}</span>; }
function Badge({ children, tone = '' }: { children: React.ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span>; }
function External({ href, children, className = '' }: { href: string; children: React.ReactNode; className?: string }) { return <a href={href} className={className} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={14} aria-hidden="true" /></a>; }

function RoadmapLinks({ links, compact = false }: { links: { label: string; url: string }[]; compact?: boolean }) {
  return <div className={compact ? 'card-roadmap-links' : 'overview-roadmap-links'} aria-label="Roadmap trên roadmap.sh">{!compact && <h4>Roadmap tham khảo trên roadmap.sh</h4>}{links.map(link => <External key={link.url} href={link.url}>{compact ? 'Roadmap · ' : ''}{link.label}</External>)}</div>;
}

function Dialog({ title, eyebrow, children, onClose, className = '' }: { title: string; eyebrow?: string; children: React.ReactNode; onClose: () => void; className?: string }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const d = ref.current!; const previous = document.activeElement; d.showModal(); document.body.style.overflow = 'hidden'; return () => { d.close(); document.body.style.overflow = ''; if (previous instanceof HTMLElement && previous.isConnected) previous.focus(); }; }, []);
  return <dialog ref={ref} className={className} aria-labelledby="dialog-title" onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === e.currentTarget) { const box = ref.current!.getBoundingClientRect(); if (e.clientX < box.left || e.clientX > box.right || e.clientY < box.top || e.clientY > box.bottom) onClose(); } }}>
    <div className="dialog-head"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h2 id="dialog-title">{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Đóng"><X size={20} /></button></div>{children}
  </dialog>;
}

function App() {
  const [state, setState] = useState<State>(loadState);
  const [message, setMessage] = useState('');
  const [storageOkay, setStorageOkay] = useState(true);
  const [moduleId, setModuleId] = useState<string | null>(null);
  const [showAbout, setShowAbout] = useState(false);
  const location = useLocation();
  const update = (patch: Partial<State>) => setState(s => ({ ...s, ...patch }));
  const toast = (m: string) => setMessage(m);
  useEffect(() => { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); setStorageOkay(true); } catch { setStorageOkay(false); } }, [state]);
  useEffect(() => { if (!message) return; const timer = setTimeout(() => setMessage(''), 3500); return () => clearTimeout(timer); }, [message]);
  useEffect(() => { window.scrollTo({ top: 0 }); document.title = `MajorWeave — ${location.pathname === '/profile' ? 'Profile' : location.pathname === '/plan' ? 'My plan' : location.pathname === '/roadmap' ? 'My roadmap' : location.pathname === '/path' ? 'Backend Developer' : 'Explore paths'}`; }, [location.pathname]);
  const steps = [{ to: '/explore', label: 'Explore', desc: 'Khám phá hướng học', icon: Compass }, { to: '/path', label: 'Path detail', desc: 'Kỹ năng & nguồn học', icon: BookOpen }, { to: '/roadmap', label: 'My roadmap', desc: 'Lộ trình của bạn', icon: RouteIcon }, { to: '/plan', label: 'My plan', desc: 'Một tuần một bước', icon: CalendarDays }, { to: '/profile', label: 'Profile', desc: 'Hồ sơ & nhịp học', icon: UserRound }];
  const finished = state.tasks.filter(t => t.completed).length;
  const currentStack = state.tasks.length && state.planMeta ? state.planMeta.stack : state.stack;
  return <Context.Provider value={{ state, update, toast, openModule: setModuleId }}><div className="app-shell">
    <aside className="sidebar">
      <Link className="brand" to="/explore"><img src="/favicon.svg" alt="" /><span>Major<span className="brand-italic">Weave</span><small>EXPLORE. LEARN. GROW.</small></span></Link>
      <div className="sidebar-label">YOUR JOURNEY</div>
      <nav aria-label="Các trang chính">{steps.map((step, i) => <NavLink key={step.to} to={step.to} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><step.icon size={19} strokeWidth={1.6} /><span><strong>{step.label}</strong><small>{step.desc}</small></span><span className="nav-number">0{i + 1}</span></NavLink>)}</nav>
      <div className="sidebar-project"><span className="eyebrow">CURRENT PATH</span><div><span className="project-dot" />Backend · {stacks[currentStack].name}</div><p>{state.tasks.length ? `${finished}/${state.tasks.length} việc đã hoàn thành` : 'Bắt đầu từ một dự án nhỏ.'}</p>{state.tasks.length > 0 && <div className="progress-track"><span style={{ width: `${finished / state.tasks.length * 100}%` }} /></div>}</div>
      <div className="sidebar-bottom"><div className="tiny-seed"><Sprout size={23} strokeWidth={1.4} /><p>A little progress,<br /><em>every week.</em></p></div><button className="quiet-button" onClick={() => setShowAbout(true)}><CircleHelp size={15} /> Về bản thử này</button></div>
    </aside>
    <div className="workspace"><header className="topbar"><span className="topbar-context">UIT STUDENT SPACE <span>/</span> {steps.find(s => s.to === location.pathname)?.label || 'Explore'}</span><div className="topbar-right"><span className="save-state"><span className={storageOkay ? 'status-dot' : 'status-dot warning'} />{storageOkay ? 'Đã lưu' : 'Chưa lưu được'}</span><Link className="avatar" to="/profile" aria-label="Mở hồ sơ học tập">{state.profileName.trim().charAt(0).toUpperCase() || <UserRound size={15} />}</Link></div></header>
      <main id="main-content"><Routes><Route path="/explore" element={<Explore />} /><Route path="/path" element={<PathDetail />} /><Route path="/roadmap" element={<MyRoadmap />} /><Route path="/plan" element={<MyPlan />} /><Route path="/profile" element={<Profile state={state} update={update} toast={toast} />} /><Route path="*" element={<Navigate to="/explore" replace />} /></Routes></main>
      <footer className="app-footer"><span>MajorWeave <span className="footer-dot">·</span> Explore paths. Build your plan.</span><External className="event-flow-link" href="/events.html">Luồng sự kiện minh họa</External><span>Bản thử 01 <span className="footer-dot">·</span> Backend / {stacks[state.stack].name}</span></footer>
    </div>
  </div>{moduleId && <ModuleDrawer module={modules.find(m => m.id === moduleId)!} onClose={() => setModuleId(null)} />}
    {showAbout && <Dialog title="A small beginning." eyebrow="MAJORWEAVE · PROTOTYPE 01" onClose={() => setShowAbout(false)}><div className="dialog-body"><p>Bản thử có ba nhánh Backend: Node.js / Express, Python / FastAPI và Java / Spring Boot. Bạn có thể chọn nguồn học, chỉnh roadmap, tạo kế hoạch tuần và lưu tiến độ.</p><p>Các hướng khác hiện có phần tổng quan. Danh sách ngành được gộp theo ngành gốc; liên hệ với hướng học là gợi ý để khám phá.</p><p>Dữ liệu của bạn được lưu trên trình duyệt này. Sau khi học ở nguồn bên ngoài, bạn tự đánh dấu hoàn thành tại My plan.</p><div className="source-note">Nguồn học được đối chiếu ngày {checkedAt}. Thời gian học là ước lượng do nhóm biên soạn cho một dự án nhỏ.</div><div className="about-links"><External href="https://tuyensinh.uit.edu.vn/nganh-dao-tao/">Ngành đào tạo UIT</External><External href="https://roadmap.sh/backend">Tham khảo roadmap.sh</External><External href="https://beaverplans.com/">Cảm hứng giao diện Beaver Plans</External></div></div></Dialog>}
    <div className={`toast ${message ? 'visible' : ''}`} role="status" aria-live="polite">{message && <><Check size={16} />{message}</>}</div>
  </Context.Provider>;
}

function Explore() {
  const { state, update } = useApp();
  const [preview, setPreview] = useState<(typeof paths)[number] | null>(null);
  const [pathQuery, setPathQuery] = useState('');
  const [pathCategory, setPathCategory] = useState('all');
  const [nearOnly, setNearOnly] = useState(false);
  useEffect(() => { if (!state.major) setNearOnly(false); }, [state.major]);
  const currentFaculty = faculties.find(f => f.majors.some(m => m.id === state.major));
  const browseMajors = faculties.find(f => f.id === state.browseFaculty)?.majors.map(m => m.id);
  const categoryNames: Record<string, string> = { SOFTWARE: 'Phần mềm', DATA: 'Dữ liệu', AI: 'Trí tuệ nhân tạo', BUSINESS: 'Nghiệp vụ & kinh doanh', INFRASTRUCTURE: 'Hạ tầng', SECURITY: 'An toàn thông tin', HARDWARE: 'Phần cứng', DESIGN: 'Thiết kế & truyền thông', RESEARCH: 'Nghiên cứu' };
  const visiblePaths = paths.filter(p => !browseMajors || [...p.majors, ...p.relatedMajors].some(m => browseMajors.includes(m))).filter(p => !nearOnly || relationRank(p, state.major) > 0).filter(p => pathCategory === 'all' || p.category === pathCategory).filter(p => `${p.name} ${p.summary} ${p.tags.join(' ')} ${p.foundations}`.toLocaleLowerCase().includes(pathQuery.trim().toLocaleLowerCase())).sort((a, b) => relationRank(b, state.major) - relationRank(a, state.major));
  const clearFilters = () => { setPathQuery(''); setPathCategory('all'); setNearOnly(false); update({ browseFaculty: 'all' }); };
  return <div className="page explore-page">
    <div className="eyebrow page-eyebrow"><span className="little-line" /> YOUR NEXT CHAPTER</div>
    <section className="explore-hero"><div><h1>One major.<br />Many <em>possible paths.</em></h1><p>Ngành học là điểm bắt đầu. Khám phá những hướng bạn tò mò,<br className="desktop-break" /> chọn cách học và dành chỗ cho tiến bộ mỗi tuần.</p><Link className="text-link" to="/path">Thử hành trình Backend <ArrowUpRight size={18} /></Link></div><div className="hero-sketch" aria-label="Khám phá, học và thực hành"><div className="sketch-top"><span>YOUR NEXT STEP</span><span>↗</span></div><svg viewBox="0 0 280 132" aria-hidden="true"><path d="M30 105 C60 108 92 20 131 40 S186 118 251 28" fill="none" stroke="currentColor" strokeWidth="1.5" strokeDasharray="4 6" /><circle cx="31" cy="103" r="7" fill="#fbfaf6" stroke="currentColor" /><circle cx="130" cy="40" r="7" fill="#eadfd1" stroke="currentColor" /><circle cx="250" cy="29" r="9" fill="#a74127" /><path d="m247 29 2 2 4-4" stroke="#fbfaf6" fill="none" /></svg><div className="sketch-caption"><span>Explore</span><span>Learn</span><span>Build</span></div><p>You don't need the whole map.<br /><em>Just a place to start.</em></p></div></section>
    <section className="profile-strip" aria-label="Hồ sơ ngành hiện tại"><div className="profile-intro"><span className="small-icon"><GraduationCap size={21} /></span><div><strong>Bạn đang học ngành nào?</strong><p>Dùng để ưu tiên gợi ý. Mọi hướng vẫn mở để khám phá.</p></div></div><div className="profile-fields"><label>Khoa hiện tại<select value={currentFaculty?.id || ''} onChange={e => update({ major: faculties.find(f => f.id === e.target.value)?.majors[0].id || '' })}><option value="">Chưa chọn / Bỏ qua</option>{faculties.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Ngành đang học<select aria-label="Ngành đang học" value={state.major} onChange={e => update({ major: e.target.value })}><option value="">Chưa chọn ngành</option>{(currentFaculty?.majors || []).map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div></section>
    {majorCoverageNotes[state.major] && <div className="soft-note coverage-note"><strong>Phạm vi ngành đang học</strong><p>{majorCoverageNotes[state.major]}</p></div>}
    <details className="major-matrix"><summary><span>12 ngành · {paths.length} hướng khám phá</span><strong>Xem bảng ngành → hướng học</strong><ChevronDown size={18} /></summary><div className="matrix-intro"><p><strong>Gần nền tảng ngành:</strong> có nhiều kiến thức chung. <strong>Mở rộng:</strong> cần bổ sung nền tảng chuyên môn. Mối liên hệ là gợi ý do nhóm biên soạn, không phải kết luận về khả năng của từng sinh viên hoặc danh sách chuyên ngành chính thức.</p><p>{catalogScopeNote}</p><small>Đối chiếu ngành và roadmap: {catalogCheckedAt}. Gộp các biến thể chương trình về ngành gốc.</small></div><div className="matrix-scroll"><table><thead><tr><th>Khoa / ngành</th><th>Gần nền tảng ngành</th><th>Hướng mở rộng</th></tr></thead><tbody>{faculties.flatMap(f => f.majors.map(m => { const related = majorPaths(m.id); return <tr key={m.id}><th><span>{f.name}</span><button onClick={() => { update({ major: m.id, browseFaculty: 'all' }); setNearOnly(true); setPathQuery(''); setPathCategory('all'); }} aria-label={`Xem hướng của ${m.name}`}>{m.name}<ArrowDownRightIcon /></button><External href={majorProfiles[m.id].sourceUrl}>Thông tin ngành tại UIT</External></th><td>{related.primary.map(p => p.name).join(' · ') || majorCoverageNotes[m.id] || 'Chưa có hướng gần nền tảng trong phạm vi đã chọn.'}</td><td>{related.related.map(p => p.name).join(' · ') || 'Mọi hướng khác vẫn có thể khám phá; xem nền tảng cần bổ sung.'}</td></tr>; }))}</tbody></table></div></details>
    <div className="section-heading"><div><span className="eyebrow">A WORLD OF POSSIBILITIES</span><h2>Find your direction<span className="rust-text">.</span></h2></div><label className="browse-select"><span>Khám phá theo khoa</span><select value={state.browseFaculty} onChange={e => update({ browseFaculty: e.target.value })}><option value="all">Tất cả các khoa</option>{faculties.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div>
    <div className="path-catalog-toolbar"><label className="search-field"><Search size={17} /><input aria-label="Tìm hướng học" placeholder="Tìm Backend, Data Scientist, UI/UX…" value={pathQuery} onChange={e => setPathQuery(e.target.value)} /></label><label className="category-select">Nhóm hướng học<select aria-label="Nhóm hướng học" value={pathCategory} onChange={e => setPathCategory(e.target.value)}><option value="all">Tất cả nhóm</option>{Object.entries(categoryNames).filter(([id]) => paths.some(p => p.category === id)).map(([id, name]) => <option value={id} key={id}>{name}</option>)}</select></label><label className="checkbox-label"><input type="checkbox" checked={nearOnly} disabled={!state.major} onChange={e => setNearOnly(e.target.checked)} />Chỉ hướng gần / mở rộng từ ngành tôi</label></div>
    <div className="catalog-caption"><span>{visiblePaths.length} hướng học <span>·</span> Bạn có thể chọn khác ngành đang học</span><span className="sample-label"><span className="status-dot" /> Backend có trải nghiệm đầy đủ</span></div>
    <div className="path-grid">{visiblePaths.map(path => { const Icon = iconMap[path.icon as keyof typeof iconMap]; return <article key={path.id} className={`path-card ${path.sample ? 'featured' : ''}`}><div className="card-top"><span className={`path-icon ${path.sample ? 'rust-icon' : ''}`}><Icon size={25} strokeWidth={1.45} /></span>{path.sample ? <Badge tone="rust-badge">Bản trải nghiệm</Badge> : relationRank(path, state.major) === 2 ? <Badge>Gần nền tảng ngành</Badge> : relationRank(path, state.major) === 1 ? <Badge tone="green-badge">Hướng mở rộng</Badge> : <span className="eyebrow">{categoryNames[path.category]}</span>}</div><h3>{path.name}</h3><p>{path.summary}</p><div className="tag-list">{path.tags.map(tag => <span key={tag}>{tag}</span>)}</div><RoadmapLinks links={path.roadmaps} compact />{path.sample ? <Link className="card-action" to="/path">Khám phá hướng này <ArrowUpRight size={18} /></Link> : <button className="card-action" onClick={() => setPreview(path)}>Xem tổng quan <ArrowUpRight size={18} /></button>}</article>; })}</div>
    {!visiblePaths.length && <div className="empty-inline">{nearOnly && majorCoverageNotes[state.major] ? majorCoverageNotes[state.major] : 'Chưa có hướng học khớp các bộ lọc.'}<button className="text-link" onClick={clearFilters}>Xóa bộ lọc hướng học <ArrowRight size={15} /></button></div>}
    <div className="explore-note"><Leaf size={17} /><p>Các gợi ý giúp bạn khám phá hướng tự học. Nền tảng thực tế của bạn sẽ được điều chỉnh ở bước tạo roadmap.</p></div>
    {preview && <Dialog title={preview.name} eyebrow="EXPLORE A DIRECTION" onClose={() => setPreview(null)}><div className="dialog-body path-overview-body"><p>{preview.summary}</p><div className="tag-list">{preview.tags.map(t => <span key={t}>{t}</span>)}</div><h4>Nền tảng cần chuẩn bị</h4><p>{preview.foundations}</p><RoadmapLinks links={preview.roadmaps} /><h4>Ngành có nhiều nền tảng chung</h4><p>{preview.majors.map(majorName).join(' · ')}</p>{preview.relatedMajors.length > 0 && <><h4>Ngành có thể mở rộng sang hướng này</h4><p>{preview.relatedMajors.map(majorName).join(' · ')}</p></>}{state.major && <div className="soft-note"><strong>Ngành hiện tại: {majorName(state.major)}</strong><p>{majorProfiles[state.major].foundation} Bạn có thể đối chiếu với phần nền tảng của hướng này và học thêm các kiến thức còn thiếu.</p><External href={majorProfiles[state.major].sourceUrl}>Xem thông tin ngành tại UIT</External></div>}<div className="soft-note">Hướng này đang có phần tổng quan để bạn kiểm tra. Roadmap và kế hoạch đầy đủ hiện có cho ba nhánh Backend: Node.js, Python và Java.</div><button className="secondary-button" onClick={() => setPreview(null)}>Tiếp tục khám phá <ArrowRight size={17} /></button></div></Dialog>}
  </div>;
}

function ResourceCard({ resource, moduleId }: { resource: Resource; moduleId?: string }) {
  const { state, update, toast } = useApp();
  const selected = moduleId && sourceForModule(moduleId, state.stack, state.sourceByModule) === resource.id;
  return <article className={`resource-card ${selected ? 'chosen' : ''}`}><div className="resource-heading"><ProviderMark name={resource.provider} /><div><span className="eyebrow">{resource.provider}</span><h4><External href={resource.url}>{resource.title}</External></h4></div></div><p>{resource.note}</p><div className="resource-meta"><span>{resource.cost === 'free' ? 'Miễn phí' : 'Có miễn phí & trả phí'}</span><span>{resource.language === 'vi' ? 'Tiếng Việt' : 'Tiếng Anh'}</span><span>{resource.format}</span>{resource.certificate && <span>Có chứng nhận</span>}</div>{moduleId && <button className={`source-choice ${selected ? 'selected' : ''}`} onClick={() => { update({ sourceByModule: { ...state.sourceByModule, [moduleId]: resource.id } }); toast(`Đã chọn nguồn ${resource.provider}`); }}>{selected ? <Check size={15} /> : <Plus size={15} />}{selected ? 'Nguồn đã chọn' : 'Chọn nguồn này'}</button>}</article>;
}

function ModuleDrawer({ module, onClose }: { module: Module; onClose: () => void }) {
  const { state, update, toast } = useApp();
  const [filter, setFilter] = useState('all');
  const selected = state.selected.includes(module.id);
  const known = state.known.includes(module.id);
  const available = sourcesForModule(module.id, state.stack).sort((a, b) => (Number(b.language === state.language) + Number(state.preferFree && b.cost === 'free')) - (Number(a.language === state.language) + Number(state.preferFree && a.cost === 'free')));
  const filtered = available.filter(r => filter === 'all' || (filter === 'free' ? r.cost === 'free' : filter === 'vi' ? r.language === 'vi' : r.certificate));
  return <Dialog title={module.title} eyebrow={`${module.phase} · ${hoursText(module.tasks.reduce((sum, t) => sum + t.minutes, 0))} dự kiến`} onClose={onClose} className="module-drawer"><div className="dialog-body"><p className="lead-description">{module.description}</p><div className="outcome-box"><Sprout size={20} /><div><span className="eyebrow">SAU CHẶNG NÀY</span><p>{module.outcome}</p></div></div><div className="drawer-section-heading"><h3>Nguồn học <span>{available.length}</span></h3><select aria-label="Lọc nguồn học" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Tất cả nguồn</option><option value="free">Miễn phí</option><option value="vi">Tiếng Việt</option><option value="cert">Có chứng nhận</option></select></div><div className="resource-list">{filtered.map(r => <ResourceCard key={r.id} resource={r} moduleId={module.id} />)}{filtered.length === 0 && <div className="empty-inline">Chưa có nguồn khớp bộ lọc cho chặng này.<button className="text-link" onClick={() => setFilter('all')}>Xem tất cả nguồn <ArrowRight size={15} /></button></div>}</div><h3 className="practice-heading">Một chút thực hành</h3>{module.optional && <p className="source-note">Chặng mở rộng sau API đầu tiên; có thể thêm khi bạn sẵn sàng.</p>}{module.roadmap && <External className="text-link module-reference" href={module.roadmap}>Mở roadmap của chủ đề này</External>}<ul className="practice-list">{module.tasks.map(t => <li key={t.title}><span>{t.title}</span><small>{hoursText(t.minutes)}</small></li>)}</ul><p className="source-note">Nguồn đối chiếu {checkedAt}. Chọn một phần phù hợp trong khóa học; thời lượng ở đây là ước lượng cho bài thực hành.</p></div><div className="drawer-footer"><label className="checkbox-label"><input type="checkbox" checked={known} onChange={e => update({ known: e.target.checked ? [...state.known, module.id] : state.known.filter(id => id !== module.id) })} />Tôi đã biết kỹ năng này</label><button className={selected ? 'secondary-button' : 'primary-button'} onClick={() => { update({ selected: selected ? state.selected.filter(id => id !== module.id) : [...state.selected, module.id] }); toast(selected ? 'Đã bỏ chặng khỏi roadmap' : 'Đã thêm chặng vào roadmap'); }}>{selected ? <Check size={17} /> : <Plus size={17} />}{selected ? 'Đã thêm · Bấm để bỏ' : 'Thêm vào roadmap'}</button></div></Dialog>;
}

function PathDetail() {
  const { state, update, openModule, toast } = useApp();
  const [tab, setTab] = useState('roadmap');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const branch = stacks[state.stack];
  const curriculum = modulesForStack(state.stack);
  const library = resourcesForStack(state.stack);
  const awards = credentialsForStack(state.stack);
  const activeCount = state.selected.filter(id => !state.known.includes(id)).length;
  const filtered = library.filter(r => `${r.title} ${r.provider} ${r.note}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).filter(r => filter === 'all' || (filter === 'free' ? r.cost === 'free' : filter === 'vi' ? r.language === 'vi' : r.certificate));
  return <div className="page path-page"><Link className="back-link" to="/explore"><ArrowLeft size={14} /> Explore paths</Link><div className="path-heading"><div><div className="eyebrow">BUILD THE THINGS BEHIND THE SCENES</div><h1>Backend <em>Developer.</em></h1><p>Xây API, xử lý dữ liệu và đưa một ứng dụng nhỏ lên mạng.<br />Kế hoạch thực hành: <strong>{branch.name} · {branch.framework} · SQL</strong></p></div><div className="path-stamp"><Server size={36} strokeWidth={1.1} /><span>BUILD<br />SOMETHING<br /><em>useful.</em></span></div></div>
    <StackChooser value={state.stack} onChange={stack => { update(stackPatch(state, stack)); toast(`Đã chọn ${stacks[stack].name} cho roadmap`); }} />
    {state.tasks.length > 0 && state.planMeta?.stack !== state.stack && <div className="soft-note stack-plan-note">Roadmap đang chọn {branch.name}. My Plan vẫn giữ kế hoạch {stacks[state.planMeta?.stack || 'node'].name}; chỉ đổi khi bạn xác nhận tạo lại tại My Roadmap.</div>}
    <section className="reference-roadmaps" aria-label="Roadmap tham khảo"><div><span className="eyebrow">THE BIGGER PICTURE</span><h2>Roadmap tham khảo</h2><p>Mở bản đồ tổng quan, rồi quay lại chọn chặng muốn học.</p></div><div className="reference-roadmap-links"><External href="https://roadmap.sh/backend" className="secondary-button">Backend trên roadmap.sh</External><External href={branch.roadmap} className="secondary-button">{branch.name} trên roadmap.sh</External>{state.stack === 'java' && <External href="https://roadmap.sh/spring-boot" className="secondary-button">Spring Boot trên roadmap.sh</External>}<small>Liên kết mở ở tab mới.</small></div></section>
    <section className="preference-strip" aria-label="Ưu tiên học"><label>Nền tảng của bạn<select aria-label="Nền tảng của bạn" value={state.level} onChange={e => { const level = e.target.value; update({ level, known: [...state.known.filter(id => !curriculum.some(m => m.id === id)), ...(level === 'beginner' ? [] : level === 'api' ? [branch.languageModule, 'git', 'http', branch.runtimeModule, branch.apiModule] : [branch.languageModule])] }); }}><option value="beginner">Mới bắt đầu</option><option value="basic">Đã biết {branch.language}</option><option value="api">Đã từng làm API</option></select></label><label>Ngôn ngữ tài liệu<select aria-label="Ngôn ngữ tài liệu" value={state.language} onChange={e => update({ language: e.target.value })}><option value="all">Không giới hạn</option><option value="vi">Tiếng Việt</option><option value="en">Tiếng Anh</option></select></label><label className="checkbox-label"><input type="checkbox" checked={state.preferFree} onChange={e => update({ preferFree: e.target.checked })} />Ưu tiên miễn phí</label><span className="subtle-copy">Bạn có thể chỉnh từng kỹ năng đã biết.</span></section>
    {['oop', 'dsa', 'network', 'os', 'systems'].some(id => !state.selected.includes(id)) && <div className="foundation-add-note"><p>Có chặng nền tảng chưa nằm trong My Roadmap. Bạn có thể thêm cùng lúc, rồi đánh dấu những kỹ năng đã biết.</p><button className="secondary-button" onClick={() => { const next = [...state.selected]; for (const id of ['oop', 'dsa', 'network', 'os', 'systems']) { if (next.includes(id)) continue; const position = curriculum.findIndex(m => m.id === id); const before = next.findIndex(current => curriculum.findIndex(m => m.id === current) > position); next.splice(before < 0 ? next.length : before, 0, id); } update({ selected: next }); toast('Đã thêm các chặng nền tảng vào roadmap'); }}><Plus size={16} />Thêm nền tảng vào roadmap</button></div>}
    <div className="curriculum-note"><strong>Nền tảng → xây API → triển khai → mở rộng.</strong><p>OOP, DSA, mạng, OS và nguyên lý hệ thống có bài nhập môn riêng. Các giờ hiển thị chỉ dành cho bài được chọn, không phải thời lượng học hết môn. System Design là chặng mở rộng, chưa thêm sẵn.</p><div className="foundation-reference-links"><External href="https://roadmap.sh/computer-science">Computer Science</External><External href="https://roadmap.sh/datastructures-and-algorithms">DSA</External><External href="https://roadmap.sh/system-design">System Design</External></div></div>
    <div className="tabs" role="tablist" aria-label="Thông tin hướng Backend">{[{ id: 'roadmap', name: 'Roadmap', count: curriculum.length }, { id: 'resources', name: 'Nguồn học', count: library.length }, { id: 'credentials', name: 'Chứng nhận', count: awards.length }].map(t => <button key={t.id} role="tab" id={`tab-${t.id}`} aria-selected={tab === t.id} aria-controls="path-information" className={tab === t.id ? 'active' : ''} onClick={() => setTab(t.id)}>{t.name}<span>{t.count}</span></button>)}</div>
    <div role="tabpanel" id="path-information" aria-labelledby={`tab-${tab}`}>
    {tab === 'roadmap' && <div className="roadmap-layout"><div className="module-timeline">{curriculum.map((m, index) => <button className={`module-node ${state.known.includes(m.id) ? 'known' : ''}`} key={m.id} onClick={() => openModule(m.id)}><span className="node-number">{state.known.includes(m.id) ? <Check size={17} /> : String(index + 1).padStart(2, '0')}</span><div className="node-content"><div className="node-title"><h3>{m.title}</h3>{state.known.includes(m.id) && <Badge tone="green-badge">Đã biết</Badge>}{m.optional && <Badge>Chọn thêm</Badge>}{!state.selected.includes(m.id) && !m.optional && <Badge>Chưa thêm</Badge>}</div><p>{m.description}</p><div className="node-meta"><span>{m.phase}</span><span>{sourcesForModule(m.id, state.stack).length} nguồn học</span><span>{hoursText(m.tasks.reduce((s, t) => s + t.minutes, 0))}</span></div></div><ArrowUpRight size={18} /></button>)}</div><aside className="roadmap-aside"><span className="eyebrow">A PLACE TO START</span><h2>A small API.<br /><em>A real first step.</em></h2><p>Mục tiêu đầu tiên: API quản lý công việc có dữ liệu, đăng nhập và kiểm thử.</p><div className="aside-stats"><div><span>{activeCount}</span><small>chặng muốn học</small></div><div><span>{new Set(library.map(r => r.provider)).size}</span><small>nguồn cung cấp</small></div></div><Link className="primary-button" to="/roadmap">Tùy chỉnh roadmap <ArrowRight size={17} /></Link><p className="aside-tip"><BookOpen size={15} /> Bấm một chặng để chọn nguồn học và xem bài thực hành.</p><External href="https://roadmap.sh/backend" className="text-link">Xem sâu hơn trên roadmap.sh</External></aside></div>}
    {tab === 'resources' && <><div className="resource-toolbar"><label className="search-field"><Search size={17} /><input aria-label="Tìm nguồn học" placeholder="Tìm khóa học, chủ đề, nền tảng…" value={query} onChange={e => setQuery(e.target.value)} /></label><select aria-label="Lọc thư viện" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Tất cả nguồn học</option><option value="free">Miễn phí</option><option value="vi">Tiếng Việt</option><option value="cert">Có chứng nhận</option></select></div><p className="catalog-caption">{filtered.length} tài nguyên · Chọn nguồn cho từng chặng ở tab Roadmap.</p><div className="resource-grid">{filtered.map(r => <ResourceCard resource={r} key={r.id} />)}</div>{!filtered.length && <div className="empty-inline">Chưa có nguồn khớp tìm kiếm.<button className="text-link" onClick={() => { setFilter('all'); setQuery(''); }}>Xóa bộ lọc <ArrowRight size={15} /></button></div>}<p className="source-note">Nguồn đối chiếu {checkedAt}. Liên kết mở trên website của đơn vị cung cấp.</p></>}
    {tab === 'credentials' && <><div className="credentials-intro"><GraduationCap size={25} /><div><h3>Thêm một mục tiêu, khi bạn sẵn sàng.</h3><p>Chứng nhận là lựa chọn bổ trợ. Mỗi chương trình có điều kiện riêng; hoàn thành roadmap mẫu chưa đồng nghĩa đạt chứng nhận.</p></div></div><div className="credential-grid">{awards.map(c => { const saved = state.credentials.includes(c.id); return <article className="credential-card" key={c.id}><div className="card-top"><span className="eyebrow">{c.provider}</span><button className={`icon-button ${saved ? 'bookmarked' : ''}`} aria-label={`${saved ? 'Bỏ lưu' : 'Lưu'} ${c.name}`} onClick={() => { update({ credentials: saved ? state.credentials.filter(id => id !== c.id) : [...state.credentials, c.id] }); toast(saved ? 'Đã bỏ mục tiêu chứng nhận' : 'Đã lưu mục tiêu chứng nhận'); }}><Bookmark size={19} fill={saved ? 'currentColor' : 'none'} /></button></div><h3>{c.name}</h3><div className="tag-list"><span>{c.type}</span><span>{c.price}</span></div><p>{c.note}</p><div className="credential-bottom"><Badge>{c.stage}</Badge><External className="text-link" href={c.url}>Xem điều kiện</External></div></article>; })}</div><p className="source-note">Đối chiếu ngày {checkedAt}. Kiểm tra phí thi và phiên bản hiện hành tại trang chính thức trước khi đăng ký.</p></>}
    </div>
  </div>;
}

function MyRoadmap() {
  const { state, update, openModule, toast } = useApp();
  const navigate = useNavigate();
  const [error, setError] = useState('');
  const [confirmRebuild, setConfirmRebuild] = useState(false);
  const selected = state.selected.map(id => modulesForStack(state.stack).find(m => m.id === id)).filter((m): m is Module => !!m);
  const active = selected.filter(m => !state.known.includes(m.id));
  const minutes = active.reduce((sum, m) => sum + m.tasks.reduce((s, t) => s + t.minutes, 0), 0);
  const weeks = generatePlan({ ...state, tasks: [] });
  const weekCount = weeks.length ? Math.max(...weeks.map(t => t.week)) + 1 : 0;
  const move = (id: string, delta: number) => { const next = [...state.selected]; const index = next.indexOf(id); const dest = index + delta; if (dest < 0 || dest >= next.length) return; [next[index], next[dest]] = [next[dest], next[index]]; update({ selected: next }); };
  const build = () => {
    if (!active.length) { setError('Chọn ít nhất một chặng chưa biết để tạo kế hoạch.'); return; }
    if (!state.goal.trim()) { setError('Bạn hãy đặt một mục tiêu cho kế hoạch.'); return; }
    if (!state.startDate || Number.isNaN(new Date(`${state.startDate}T00:00:00`).getTime())) { setError('Chọn ngày bắt đầu hợp lệ.'); return; }
    update({ tasks: generatePlan(state), planMeta: { stack: state.stack, goal: state.goal, hours: state.hours, startDate: state.startDate } }); toast('Kế hoạch của bạn đã sẵn sàng'); navigate('/plan');
  };
  const requestBuild = () => { setError(''); if (state.tasks.length && active.length && state.goal.trim() && state.startDate) setConfirmRebuild(true); else build(); };
  return <div className="page"><div className="eyebrow page-eyebrow">MAKE IT YOUR OWN</div><div className="page-heading"><div><h1>Your path.<br /><em>Your pace.</em></h1><p>Giữ những điều muốn học, bỏ qua kỹ năng đã biết.<br />Một lộ trình vừa sức bắt đầu từ đây.</p></div><div className="heading-tag"><RouteIcon size={16} /> Backend · {stacks[state.stack].name}</div></div>
    <div className="roadmap-editor"><section className="roadmap-paper"><div className="paper-heading"><div><span className="eyebrow">MY LEARNING PATH</span><h2>Small steps, in order.</h2></div><Link to="/path" className="text-link"><Plus size={16} />Thêm chặng</Link></div><div className="selected-modules">{selected.map((m, index) => { const known = state.known.includes(m.id); return <article key={m.id} className={`selected-module ${known ? 'is-known' : ''}`}><div className="selected-module-top"><span className="list-number">{String(index + 1).padStart(2, '0')}</span><div><button className="module-title-button" onClick={() => openModule(m.id)}>{m.title}<ArrowUpRight size={15} /></button><span className="module-duration">{known ? 'Bỏ qua trong kế hoạch' : `${hoursText(m.tasks.reduce((s, t) => s + t.minutes, 0))} · ${m.tasks.length} việc thực hành`}</span></div><div className="order-buttons"><button aria-label={`Đưa ${m.title} lên`} className="icon-button" disabled={index === 0} onClick={() => move(m.id, -1)}><ChevronUp size={15} /></button><button aria-label={`Đưa ${m.title} xuống`} className="icon-button" disabled={index === selected.length - 1} onClick={() => move(m.id, 1)}><ChevronDown size={15} /></button><button aria-label={`Bỏ ${m.title}`} className="icon-button" onClick={() => { update({ selected: state.selected.filter(id => id !== m.id) }); toast('Đã bỏ chặng khỏi roadmap'); }}><X size={15} /></button></div></div><div className="selected-module-bottom"><label className="checkbox-label"><input type="checkbox" checked={known} onChange={e => update({ known: e.target.checked ? [...state.known, m.id] : state.known.filter(id => id !== m.id) })} />Đã biết</label><label className="source-select"><BookOpen size={14} /><select aria-label={`Nguồn học cho ${m.title}`} value={sourceForModule(m.id, state.stack, state.sourceByModule)} onChange={e => update({ sourceByModule: { ...state.sourceByModule, [m.id]: e.target.value } })}>{sourcesForModule(m.id, state.stack).map(r => <option key={r.id} value={r.id}>{r.provider} · {r.title}</option>)}</select></label></div></article>; })}</div>{selected.length === 0 && <div className="empty-inline">Roadmap đang trống.<Link className="text-link" to="/path">Chọn chặng muốn học <ArrowRight size={15} /></Link></div>}<div className="paper-footnote"><CheckCheck size={16} />Các kỹ năng đã biết được bỏ qua khi tạo kế hoạch.</div></section>
    <aside className="plan-builder"><span className="eyebrow">MAKE A LITTLE ROOM</span><h2>Turn curiosity<br /><em>into a habit.</em></h2><label>Mục tiêu của bạn<input maxLength={120} value={state.goal} onChange={e => update({ goal: e.target.value })} placeholder="Ví dụ: Xây API quản lý công việc" /></label><label className="hours-label">Thời gian mỗi tuần<span><strong>{state.hours}</strong> giờ</span><input type="range" min="2" max="20" step="1" value={state.hours} aria-label="Số giờ học mỗi tuần" onChange={e => update({ hours: Number(e.target.value) })} /><span className="range-labels"><small>2 giờ</small><small>20 giờ</small></span></label><label>Ngày bắt đầu<input type="date" value={state.startDate} onChange={e => update({ startDate: e.target.value })} /></label><div className="plan-estimate"><div><span>{active.length}</span><small>chặng học</small></div><div><span>{hoursText(minutes)}</span><small>thực hành dự kiến</small></div><div><span>{weekCount}</span><small>tuần dự kiến</small></div></div><p className="builder-note">Lịch chia bài học và thực hành theo quỹ thời gian của bạn. Bạn có thể sửa từng việc sau khi tạo.</p>{error && <p role="alert" className="form-error">{error}</p>}<button className="primary-button full-width" onClick={requestBuild}>Tạo kế hoạch của tôi <ArrowRight size={17} /></button><span className="estimate-caption">Đây là kế hoạch cho dự án đầu tiên.<br />Thời gian học thực tế có thể khác.</span></aside></div>
    {confirmRebuild && <Dialog title="Tạo lại kế hoạch?" eyebrow="MY PLAN" onClose={() => setConfirmRebuild(false)}><div className="dialog-body"><p>Kế hoạch sẽ được sắp lại theo roadmap, nguồn học và thời gian mới. Việc đã hoàn thành và ghi chú của các bài còn trong roadmap được giữ lại.</p><p>Các việc tự thêm và chỉnh sửa tiêu đề, thời lượng trong kế hoạch cũ sẽ được thay bằng kế hoạch mới. Khi đổi nhánh, các bài triển khai theo ngôn ngữ cũ sẽ được thay; ngày hoàn thành của bài được giữ lại vẫn giữ nguyên.</p><div className="dialog-actions"><button className="secondary-button" onClick={() => setConfirmRebuild(false)}>Giữ kế hoạch hiện tại</button><button className="primary-button" onClick={build}>Tạo lại kế hoạch <ArrowRight size={16} /></button></div></div></Dialog>}
  </div>;
}

function MyPlan() {
  const { state, update, toast } = useApp();
  const [week, setWeek] = useState(0);
  const [editing, setEditing] = useState<Task | null>(null);
  const [adding, setAdding] = useState(false);
  const [customTitle, setCustomTitle] = useState('');
  const [customMinutes, setCustomMinutes] = useState(60);
  const plan = state.planMeta || { stack: state.stack, goal: state.goal, hours: state.hours, startDate: state.startDate };
  const weekCount = state.tasks.length ? Math.max(...state.tasks.map(t => t.week)) + 1 : 0;
  const visibleWeek = Math.min(week, Math.max(0, weekCount - 1));
  const weekTasks = state.tasks.filter(t => t.week === visibleWeek);
  const completed = state.tasks.filter(t => t.completed).length;
  const totalMinutes = state.tasks.reduce((s, t) => s + t.minutes, 0);
  const doneMinutes = state.tasks.filter(t => t.completed).reduce((s, t) => s + t.minutes, 0);
  const weekMinutes = weekTasks.reduce((s, t) => s + t.minutes, 0);
  const progress = state.tasks.length ? Math.round(completed / state.tasks.length * 100) : 0;
  const start = weekDate(plan.startDate, visibleWeek);
  const end = new Date(start); end.setDate(end.getDate() + 6);
  const patchTask = (task: Task) => update({ tasks: state.tasks.map(t => t.id === task.id ? task : t) });
  const addTask = (e: React.FormEvent) => { e.preventDefault(); if (!customTitle.trim()) return; const id = `custom-${crypto.randomUUID()}`; update({ tasks: [...state.tasks, { id, moduleId: 'custom', title: customTitle.trim(), minutes: customMinutes, sourceId: '', week: visibleWeek, completed: false, notes: '' }] }); setCustomTitle(''); setAdding(false); toast('Đã thêm việc vào tuần này'); };
  if (!state.tasks.length) return <div className="page empty-plan"><div className="eyebrow">MY PLAN</div><CalendarDays size={45} strokeWidth={1} /><h1>A little room<br /><em>for progress.</em></h1><p>Chọn chặng muốn học và quỹ thời gian để bắt đầu kế hoạch tuần.</p><Link to="/roadmap" className="primary-button">Tạo kế hoạch đầu tiên <ArrowRight size={17} /></Link></div>;
  return <div className="page plan-page"><div className="eyebrow page-eyebrow">MY PLAN / BACKEND · {stacks[plan.stack].name.toUpperCase()}</div><div className="page-heading"><div><h1>Make room<br /><em>for progress.</em></h1><p>{plan.goal}</p></div><Link className="secondary-button" to="/roadmap"><Pencil size={15} />Chỉnh roadmap</Link></div>
    <div className="journey-progress"><div><span className="progress-kicker">YOUR FIRST PROJECT</span><strong>{completed}<span> / {state.tasks.length} việc</span></strong></div><div className="journey-progress-bar"><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><span>{progress}% hoàn thành <span>·</span> {hoursText(doneMinutes)} / {hoursText(totalMinutes)} dự kiến</span></div><Sprout size={31} strokeWidth={1.3} /></div>
    <div className="planner-layout"><aside className="week-sidebar"><span className="eyebrow">ONE WEEK AT A TIME</span><div className="week-list">{Array.from({ length: weekCount }, (_, index) => { const tasks = state.tasks.filter(t => t.week === index); const done = tasks.filter(t => t.completed).length; return <button key={index} className={`week-button ${visibleWeek === index ? 'active' : ''}`} onClick={() => setWeek(index)} aria-pressed={visibleWeek === index}><span><strong>Tuần {String(index + 1).padStart(2, '0')}</strong><small>{shortDate(weekDate(plan.startDate, index))}</small></span><span className="week-completion">{done === tasks.length && tasks.length > 0 ? <Check size={15} /> : `${done}/${tasks.length}`}</span></button>; })}</div><div className="week-quote"><Leaf size={20} strokeWidth={1.4} /><p>Consistency over intensity.<br /><em>Một chút, đều đặn.</em></p></div></aside>
    <section className="week-paper"><div className="week-heading"><div><span className="eyebrow">{shortDate(start)} — {shortDate(end)} · {start.getFullYear()}</span><h2>Tuần {String(visibleWeek + 1).padStart(2, '0')}<span className="rust-text">.</span></h2></div><div className="week-controls"><button className="icon-button" aria-label="Tuần trước" disabled={visibleWeek === 0} onClick={() => setWeek(visibleWeek - 1)}><ChevronLeft size={20} /></button><button className="icon-button" aria-label="Tuần tiếp theo" disabled={visibleWeek === weekCount - 1} onClick={() => setWeek(visibleWeek + 1)}><ChevronRight size={20} /></button></div></div><div className="week-summary"><span><Clock3 size={14} />{hoursText(weekMinutes)} / {plan.hours} giờ mỗi tuần</span><span>{weekTasks.filter(t => t.completed).length}/{weekTasks.length} việc đã xong</span></div>{weekMinutes > plan.hours * 60 && <p className="capacity-note">Tuần này vượt quỹ thời gian {hoursText(weekMinutes - plan.hours * 60)}. Bạn có thể chuyển việc sang tuần khác.</p>}
    <div className="task-list">{weekTasks.map(task => { const resource = resources.find(r => r.id === task.sourceId); const module = modules.find(m => m.id === task.moduleId); return <article className={`task-row ${task.completed ? 'completed' : ''}`} key={task.id}><label className="task-checkbox"><input type="checkbox" aria-label={`Hoàn thành: ${task.title}`} checked={task.completed} onChange={e => { patchTask({ ...task, completed: e.target.checked, completedAt: e.target.checked ? new Date().toISOString() : undefined }); toast(e.target.checked ? 'Một bước nữa đã hoàn thành 🌱' : 'Đã đánh dấu việc cần làm'); }} /><span><Check size={14} /></span></label><div className="task-content"><div className="task-topline"><span className="eyebrow">{module?.title || 'Việc của bạn'}</span><span className="task-duration">{hoursText(task.minutes)}</span></div><h3>{task.title}</h3><div className="task-bottom">{resource && <External href={resource.url}><BookOpen size={13} />{resource.provider} · Mở nguồn học</External>}{task.notes && <p className="task-notes">{task.notes}</p>}</div></div><button className="icon-button task-edit" aria-label={`Sửa: ${task.title}`} onClick={() => setEditing({ ...task })}><Pencil size={16} /></button></article>; })}</div>
    {weekTasks.length === 0 && <div className="empty-inline">Tuần này đang trống. Bạn có thể thêm một việc nhỏ.</div>}
    {weekTasks.length > 0 && weekTasks.every(t => t.completed) && <div className="week-done"><CheckCheck size={20} /><span>Tuần này đã xong. Dành một chút thời gian nhìn lại điều bạn học được.</span></div>}
    {adding ? <form className="add-task-form" onSubmit={addTask}><label>Việc muốn làm<input autoFocus maxLength={200} required value={customTitle} onChange={e => setCustomTitle(e.target.value)} placeholder="Ví dụ: Ôn lại bài về HTTP" /></label><label>Thời lượng<select value={customMinutes} onChange={e => setCustomMinutes(Number(e.target.value))}><option value={30}>30 phút</option><option value={60}>1 giờ</option><option value={90}>1.5 giờ</option><option value={120}>2 giờ</option></select></label><div className="dialog-actions"><button type="button" className="quiet-button" onClick={() => setAdding(false)}>Hủy</button><button className="primary-button" type="submit"><Plus size={15} />Thêm việc</button></div></form> : <button className="add-task-button" onClick={() => setAdding(true)}><Plus size={17} />Thêm một việc nhỏ</button>}
    <div className="week-paper-footer"><span>YOUR PACE, YOUR PROGRESS.</span><span><Check size={13} />Dữ liệu lưu trên trình duyệt này</span></div></section></div>
    <section className="plan-rhythm-summary"><div><span className="eyebrow">THIS WEEK, ONE STEP AT A TIME</span><h3>{weekTasks.filter(t => t.completed).length} / {weekTasks.length} việc đã hoàn thành trong tuần được chọn</h3><p>Nhịp học 12 tuần và hồ sơ học tập nằm tại Profile.</p></div><Link className="secondary-button" to="/profile">Xem nhịp học <ArrowRight size={16} /></Link></section>
    {state.credentials.length > 0 && <section className="saved-credentials"><div className="section-heading"><div><span className="eyebrow">FOR LATER</span><h2>Mục tiêu chứng nhận đã lưu</h2></div><Link to="/path" className="text-link">Khám phá thêm <ArrowUpRight size={16} /></Link></div><div className="saved-credential-list">{credentials.filter(c => state.credentials.includes(c.id)).map(c => <External key={c.id} href={c.url}><GraduationCap size={19} /><span>{c.name}<small>{c.type} · {c.provider}</small></span></External>)}</div></section>}
    {editing && <Dialog title="Chỉnh một bước nhỏ." eyebrow="MY PLAN" onClose={() => setEditing(null)}><form className="dialog-body task-edit-form" onSubmit={e => { e.preventDefault(); if (!editing.title.trim()) return; patchTask({ ...editing, title: editing.title.trim() }); setWeek(editing.week); setEditing(null); toast('Đã lưu thay đổi'); }}><label>Tên công việc<input required maxLength={200} value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} /></label><div className="form-row"><label>Thời lượng (phút)<input type="number" min={15} max={1200} step={15} required value={editing.minutes} onChange={e => setEditing({ ...editing, minutes: Number(e.target.value) })} /></label><label>Chuyển đến<select aria-label="Chuyển đến" value={editing.week} onChange={e => setEditing({ ...editing, week: Number(e.target.value) })}>{Array.from({ length: weekCount + 1 }, (_, i) => <option key={i} value={i}>Tuần {i + 1}{i === weekCount ? ' · Tuần mới' : ''}</option>)}</select></label></div><label>Ghi chú<textarea maxLength={1000} rows={3} placeholder="Điều muốn nhớ, khó khăn hoặc kết quả…" value={editing.notes} onChange={e => setEditing({ ...editing, notes: e.target.value })} /></label><div className="dialog-actions"><button type="button" className="secondary-button" onClick={() => setEditing(null)}>Hủy</button><button className="primary-button" type="submit">Lưu thay đổi <Check size={16} /></button></div></form></Dialog>}
  </div>;
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><HashRouter><App /></HashRouter></React.StrictMode>);
