import { useState } from 'react';
import { ArrowRight, Check, Plus, Sprout } from 'lucide-react';
import { checkedAt, sourcesForModule, type Module } from '../../data';
import { hoursText } from '../../state';
import { useApp } from '../../app/context';
import { Dialog, External } from '../../components/ui';
import { ResourceCard } from './ResourceCard';
export function ModuleDrawer({ module, onClose }: { module: Module; onClose: () => void }) {
  const { state, update, toast } = useApp();
  const [filter, setFilter] = useState('all');
  const selected = state.selected.includes(module.id);
  const known = state.known.includes(module.id);
  const available = sourcesForModule(module.id, state.stack).sort((a, b) => (Number(b.language === state.language) + Number(state.preferFree && b.cost === 'free')) - (Number(a.language === state.language) + Number(state.preferFree && a.cost === 'free')));
  const filtered = available.filter(r => filter === 'all' || (filter === 'free' ? r.cost === 'free' : filter === 'vi' ? r.language === 'vi' : r.certificate));
  return <Dialog title={module.title} eyebrow={`${module.phase} · ${hoursText(module.tasks.reduce((sum, t) => sum + t.minutes, 0))} dự kiến`} onClose={onClose} className="module-drawer"><div className="dialog-body"><p className="lead-description">{module.description}</p><div className="outcome-box"><Sprout size={20} /><div><span className="eyebrow">SAU CHẶNG NÀY</span><p>{module.outcome}</p></div></div><div className="drawer-section-heading"><h3>Nguồn học <span>{available.length}</span></h3><select aria-label="Lọc nguồn học" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Tất cả nguồn</option><option value="free">Miễn phí</option><option value="vi">Tiếng Việt</option><option value="cert">Có chứng nhận</option></select></div><div className="resource-list">{filtered.map(r => <ResourceCard key={r.id} resource={r} moduleId={module.id} />)}{filtered.length === 0 && <div className="empty-inline">Chưa có nguồn khớp bộ lọc cho chặng này.<button className="text-link" onClick={() => setFilter('all')}>Xem tất cả nguồn <ArrowRight size={15} /></button></div>}</div><h3 className="practice-heading">Một chút thực hành</h3>{module.optional && <p className="source-note">Chặng mở rộng sau API đầu tiên; có thể thêm khi bạn sẵn sàng.</p>}{module.roadmap && <External className="text-link module-reference" href={module.roadmap}>Mở roadmap của chủ đề này</External>}<ul className="practice-list">{module.tasks.map(t => <li key={t.title}><span>{t.title}</span><small>{hoursText(t.minutes)}</small></li>)}</ul><p className="source-note">Nguồn đối chiếu {checkedAt}. Chọn một phần phù hợp trong khóa học; thời lượng ở đây là ước lượng cho bài thực hành.</p></div><div className="drawer-footer"><label className="checkbox-label"><input type="checkbox" checked={known} onChange={e => update({ known: e.target.checked ? [...state.known, module.id] : state.known.filter(id => id !== module.id) })} />Tôi đã biết kỹ năng này</label><button className={selected ? 'secondary-button' : 'primary-button'} onClick={() => { update({ selected: selected ? state.selected.filter(id => id !== module.id) : [...state.selected, module.id] }); toast(selected ? 'Đã bỏ chặng khỏi roadmap' : 'Đã thêm chặng vào roadmap'); }}>{selected ? <Check size={17} /> : <Plus size={17} />}{selected ? 'Đã thêm · Bấm để bỏ' : 'Thêm vào roadmap'}</button></div></Dialog>;
}
