import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, ArrowLeft, Check, X, Plus, BookOpen, Server, Search, GraduationCap, Bookmark } from 'lucide-react';
import { checkedAt, paths, resources, credentials, stacks, modulesForStack, resourcesForStack, sourcesForModule, credentialsForStack } from '../../data';
import { hoursText, stackPatch } from '../../state';
import { StackChooser } from '../../components/StackChooser';
import { useApp } from '../../app/context';
import { Badge, External } from '../../components/ui';
import { ResourceCard } from './ResourceCard';
export function PathDetail() {
  const { state, update, openModule, toast } = useApp();
  const [tab, setTab] = useState('roadmap');
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const branch = stacks[state.stack];
  const curriculum = modulesForStack(state.stack);
  const library = resourcesForStack(state.stack);
  const awards = credentialsForStack(state.stack);
  const activeCount = state.selected.filter(id => !state.known.includes(id)).length;
  const filtered = library.filter(r => `${r.title} ${r.provider} ${r.note}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).filter(r => filter === 'all' || (filter === 'free' ? r.cost === 'free' : filter === 'vi' ? r.language === 'vi' : r.certificate));
  return <div className="page path-page"><Link className="back-link" to="/explore"><ArrowLeft size={14} /> Explore paths</Link><div className="path-heading"><div><div className="eyebrow">BUILD THE THINGS BEHIND THE SCENES</div><h1>Backend <em>Developer.</em></h1><p>Xây API, xử lý dữ liệu và đưa một ứng dụng nhỏ lên mạng.<br />Kế hoạch thực hành: <strong>{branch.name} · {branch.framework} · SQL</strong></p></div><div className="path-stamp"><Server size={36} strokeWidth={1.1} /><span>BUILD<br />SOMETHING<br /><em>useful.</em></span></div></div>
    <StackChooser value={state.stack} onChange={stack => { update(stackPatch(state, stack)); toast(`Đã chọn ${stacks[stack].name} cho roadmap`); }} />
    {state.tasks.length > 0 && state.planMeta?.stack !== state.stack && <div className="soft-note stack-plan-note">Roadmap đang chọn {branch.name}. My Plan vẫn giữ kế hoạch {stacks[state.planMeta?.stack || 'node'].name}; chỉ đổi khi bạn xác nhận tạo lại tại My Roadmap.</div>}
    <section className="reference-roadmaps" aria-label="Roadmap tham khảo"><div><span className="eyebrow">THE BIGGER PICTURE</span><h2>Roadmap tham khảo</h2><p>Mở bản đồ tổng quan, rồi quay lại chọn chặng muốn học.</p></div><div className="reference-roadmap-links"><External href="https://roadmap.sh/backend" className="secondary-button">Backend trên roadmap.sh</External><External href={branch.roadmap} className="secondary-button">{branch.name} trên roadmap.sh</External>{state.stack === 'java' && <External href="https://roadmap.sh/spring-boot" className="secondary-button">Spring Boot trên roadmap.sh</External>}<small>Liên kết mở ở tab mới.</small></div></section>
    <section className="preference-strip" aria-label="Ưu tiên học"><label>Nền tảng của bạn<select aria-label="Nền tảng của bạn" value={state.level} onChange={e => { const level = e.target.value; update({ level, known: [...state.known.filter(id => !curriculum.some(m => m.id === id)), ...(level === 'beginner' ? [] : level === 'api' ? [branch.languageModule, 'git', 'http', branch.runtimeModule, branch.apiModule] : [branch.languageModule])] }); }}><option value="beginner">Mới bắt đầu</option><option value="basic">Đã biết {branch.language}</option><option value="api">Đã từng làm API</option></select></label><label>Ngôn ngữ tài liệu<select aria-label="Ngôn ngữ tài liệu" value={state.language} onChange={e => update({ language: e.target.value })}><option value="all">Không giới hạn</option><option value="vi">Tiếng Việt</option><option value="en">Tiếng Anh</option></select></label><label className="checkbox-label"><input type="checkbox" checked={state.preferFree} onChange={e => update({ preferFree: e.target.checked })} />Ưu tiên miễn phí</label><span className="subtle-copy">Bạn có thể chỉnh từng kỹ năng đã biết.</span></section>
    {['oop', 'dsa', 'network', 'os', 'systems'].some(id => !state.selected.includes(id)) && <div className="foundation-add-note"><p>Có chặng nền tảng chưa nằm trong My Roadmap. Bạn có thể thêm cùng lúc, rồi đánh dấu những kỹ năng đã biết.</p><button className="secondary-button" onClick={() => { const next = [...state.selected]; for (const id of ['oop', 'dsa', 'network', 'os', 'systems']) { if (next.includes(id)) continue; const position = curriculum.findIndex(m => m.id === id); const before = next.findIndex(current => curriculum.findIndex(m => m.id === current) > position); next.splice(before < 0 ? next.length : before, 0, id); } update({ selected: next }); toast('Đã thêm các chặng nền tảng vào roadmap'); }}><Plus size={16} />Thêm nền tảng vào roadmap</button></div>}
    <div className="curriculum-note"><strong>Nền tảng → xây API → triển khai → mở rộng.</strong><p>OOP, DSA, mạng, OS và nguyên lý hệ thống có bài nhập môn riêng. Các giờ hiển thị chỉ dành cho bài được chọn, không phải thời lượng học hết môn. System Design là chặng mở rộng, chưa thêm sẵn.</p><div className="foundation-reference-links"><External href="https://roadmap.sh/computer-science">Computer Science</External><External href="https://roadmap.sh/datastructures-and-algorithms">DSA</External><External href="https://roadmap.sh/system-design">System Design</External></div></div>
    <div className="tabs" role="tablist" aria-label="Thông tin hướng Backend">{[{ id: 'roadmap', name: 'Roadmap', count: curriculum.length }, { id: 'resources', name: 'Nguồn học', count: library.length }, { id: 'credentials', name: 'Chứng nhận', count: awards.length }].map(t => <button key={t.id} role="tab" id={`tab-${t.id}`} aria-selected={tab === t.id} aria-controls="path-information" className={tab === t.id ? 'active' : ''} onClick={() => setTab(t.id)}>{t.name}<span>{t.count}</span></button>)}</div>
    <div role="tabpanel" id="path-information" aria-labelledby={`tab-${tab}`}>
    {tab === 'roadmap' && <div className="roadmap-layout"><div className="module-timeline">{curriculum.map((m, index) => <button className={`module-node ${state.known.includes(m.id) ? 'known' : ''}`} key={m.id} onClick={() => openModule(m.id)}><span className="node-number">{state.known.includes(m.id) ? <Check size={17} /> : String(index + 1).padStart(2, '0')}</span><div className="node-content"><div className="node-title"><h3>{m.title}</h3>{state.known.includes(m.id) && <Badge tone="green-badge">Đã biết</Badge>}{m.optional && <Badge>Chọn thêm</Badge>}{!state.selected.includes(m.id) && !m.optional && <Badge>Chưa thêm</Badge>}</div><p>{m.description}</p><div className="node-meta"><span>{m.phase}</span><span>{sourcesForModule(m.id, state.stack).length} nguồn học</span><span>{hoursText(m.tasks.reduce((s, t) => s + t.minutes, 0))}</span></div></div><ArrowUpRight size={18} /></button>)}</div><aside className="roadmap-aside"><span className="eyebrow">A PLACE TO START</span><h2>A small API.<br /><em>A real first step.</em></h2><p>Mục tiêu đầu tiên: API quản lý công việc có dữ liệu, đăng nhập và kiểm thử.</p><div className="aside-stats"><div><span>{activeCount}</span><small>chặng muốn học</small></div><div><span>{new Set(library.map(r => r.provider)).size}</span><small>nguồn cung cấp</small></div></div><Link className="primary-button" to="/roadmap">Tùy chỉnh roadmap <ArrowRight size={17} /></Link><p className="aside-tip"><BookOpen size={15} /> Bấm một chặng để chọn nguồn học và xem bài thực hành.</p><External href="https://roadmap.sh/backend" className="text-link">Xem sâu hơn trên roadmap.sh</External></aside></div>}
    {tab === 'resources' && <><div className="resource-toolbar"><label className="search-field"><Search size={17} /><input aria-label="Tìm nguồn học" placeholder="Tìm khóa học, chủ đề, nền tảng…" value={query} onChange={e => setQuery(e.target.value)} /></label><select aria-label="Lọc thư viện" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">Tất cả nguồn học</option><option value="free">Miễn phí</option><option value="vi">Tiếng Việt</option><option value="cert">Có chứng nhận</option></select></div><p className="catalog-caption">{filtered.length} tài nguyên · Chọn nguồn cho từng chặng ở tab Roadmap.</p><div className="resource-grid">{filtered.map(r => <ResourceCard resource={r} key={r.id} />)}</div>{!filtered.length && <div className="empty-inline">Chưa có nguồn khớp tìm kiếm.<button className="text-link" onClick={() => { setFilter('all'); setQuery(''); }}>Xóa bộ lọc <ArrowRight size={15} /></button></div>}<p className="source-note">Nguồn đối chiếu {checkedAt}. Liên kết mở trên website của đơn vị cung cấp.</p></>}
    {tab === 'credentials' && <><div className="credentials-intro"><GraduationCap size={25} /><div><h3>Thêm một mục tiêu, khi bạn sẵn sàng.</h3><p>Chứng nhận là lựa chọn bổ trợ. Mỗi chương trình có điều kiện riêng; hoàn thành roadmap mẫu chưa đồng nghĩa đạt chứng nhận.</p></div></div><div className="credential-grid">{awards.map(c => { const saved = state.credentials.includes(c.id); return <article className="credential-card" key={c.id}><div className="card-top"><span className="eyebrow">{c.provider}</span><button className={`icon-button ${saved ? 'bookmarked' : ''}`} aria-label={`${saved ? 'Bỏ lưu' : 'Lưu'} ${c.name}`} onClick={() => { update({ credentials: saved ? state.credentials.filter(id => id !== c.id) : [...state.credentials, c.id] }); toast(saved ? 'Đã bỏ mục tiêu chứng nhận' : 'Đã lưu mục tiêu chứng nhận'); }}><Bookmark size={19} fill={saved ? 'currentColor' : 'none'} /></button></div><h3>{c.name}</h3><div className="tag-list"><span>{c.type}</span><span>{c.price}</span></div><p>{c.note}</p><div className="credential-bottom"><Badge>{c.stage}</Badge><External className="text-link" href={c.url}>Xem điều kiện</External></div></article>; })}</div><p className="source-note">Đối chiếu ngày {checkedAt}. Kiểm tra phí thi và phiên bản hiện hành tại trang chính thức trước khi đăng ký.</p></>}
    </div>
  </div>;
}
