import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, ArrowRight, Check, Plus, CalendarDays, BookOpen, Sprout, CheckCheck, Clock3, GraduationCap, ChevronLeft, ChevronRight, Pencil, Leaf } from 'lucide-react';
import { modules, resources, credentials, stacks } from '../../data';
import { hoursText, weekDate, shortDate, type Task } from '../../state';
import { useApp } from '../../app/context';
import { External, Dialog } from '../../components/ui';
export function MyPlan() {
  const { state, update, toast } = useApp();
  const [week, setWeek] = useState(0);
  const [editing, setEditing] = useState<Task | null>(null);
  const [adding, setAdding] = useState(false);
  const [customTitle, setCustomTitle] = useState('');
  const [customMinutes, setCustomMinutes] = useState(60);
  const plan = state.planMeta || { stack: state.stack, goal: state.goal, hours: state.hours, startDate: state.startDate };
  const weekCount = state.tasks.length ? Math.max(...state.tasks.map(t => t.week)) + 1 : 0;
  const visibleWeek = Math.min(week, Math.max(0, weekCount - 1));
  const weekTasks = state.tasks.filter(t => t.week === visibleWeek);
  const completed = state.tasks.filter(t => t.completed).length;
  const totalMinutes = state.tasks.reduce((s, t) => s + t.minutes, 0);
  const doneMinutes = state.tasks.filter(t => t.completed).reduce((s, t) => s + t.minutes, 0);
  const weekMinutes = weekTasks.reduce((s, t) => s + t.minutes, 0);
  const progress = state.tasks.length ? Math.round(completed / state.tasks.length * 100) : 0;
  const start = weekDate(plan.startDate, visibleWeek);
  const end = new Date(start); end.setDate(end.getDate() + 6);
  const patchTask = (task: Task) => update({ tasks: state.tasks.map(t => t.id === task.id ? task : t) });
  const addTask = (e: React.FormEvent) => { e.preventDefault(); if (!customTitle.trim()) return; const id = `custom-${crypto.randomUUID()}`; update({ tasks: [...state.tasks, { id, moduleId: 'custom', title: customTitle.trim(), minutes: customMinutes, sourceId: '', week: visibleWeek, completed: false, notes: '' }] }); setCustomTitle(''); setAdding(false); toast('Đã thêm việc vào tuần này'); };
  if (!state.tasks.length) return <div className="page empty-plan"><div className="eyebrow">MY PLAN</div><CalendarDays size={45} strokeWidth={1} /><h1>A little room<br /><em>for progress.</em></h1><p>Chọn chặng muốn học và quỹ thời gian để bắt đầu kế hoạch tuần.</p><Link to="/roadmap" className="primary-button">Tạo kế hoạch đầu tiên <ArrowRight size={17} /></Link></div>;
  return <div className="page plan-page"><div className="eyebrow page-eyebrow">MY PLAN / BACKEND · {stacks[plan.stack].name.toUpperCase()}</div><div className="page-heading"><div><h1>Make room<br /><em>for progress.</em></h1><p>{plan.goal}</p></div><Link className="secondary-button" to="/roadmap"><Pencil size={15} />Chỉnh roadmap</Link></div>
    <div className="journey-progress"><div><span className="progress-kicker">YOUR FIRST PROJECT</span><strong>{completed}<span> / {state.tasks.length} việc</span></strong></div><div className="journey-progress-bar"><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><span>{progress}% hoàn thành <span>·</span> {hoursText(doneMinutes)} / {hoursText(totalMinutes)} dự kiến</span></div><Sprout size={31} strokeWidth={1.3} /></div>
    <div className="planner-layout"><aside className="week-sidebar"><span className="eyebrow">ONE WEEK AT A TIME</span><div className="week-list">{Array.from({ length: weekCount }, (_, index) => { const tasks = state.tasks.filter(t => t.week === index); const done = tasks.filter(t => t.completed).length; return <button key={index} className={`week-button ${visibleWeek === index ? 'active' : ''}`} onClick={() => setWeek(index)} aria-pressed={visibleWeek === index}><span><strong>Tuần {String(index + 1).padStart(2, '0')}</strong><small>{shortDate(weekDate(plan.startDate, index))}</small></span><span className="week-completion">{done === tasks.length && tasks.length > 0 ? <Check size={15} /> : `${done}/${tasks.length}`}</span></button>; })}</div><div className="week-quote"><Leaf size={20} strokeWidth={1.4} /><p>Consistency over intensity.<br /><em>Một chút, đều đặn.</em></p></div></aside>
    <section className="week-paper"><div className="week-heading"><div><span className="eyebrow">{shortDate(start)} — {shortDate(end)} · {start.getFullYear()}</span><h2>Tuần {String(visibleWeek + 1).padStart(2, '0')}<span className="rust-text">.</span></h2></div><div className="week-controls"><button className="icon-button" aria-label="Tuần trước" disabled={visibleWeek === 0} onClick={() => setWeek(visibleWeek - 1)}><ChevronLeft size={20} /></button><button className="icon-button" aria-label="Tuần tiếp theo" disabled={visibleWeek === weekCount - 1} onClick={() => setWeek(visibleWeek + 1)}><ChevronRight size={20} /></button></div></div><div className="week-summary"><span><Clock3 size={14} />{hoursText(weekMinutes)} / {plan.hours} giờ mỗi tuần</span><span>{weekTasks.filter(t => t.completed).length}/{weekTasks.length} việc đã xong</span></div>{weekMinutes > plan.hours * 60 && <p className="capacity-note">Tuần này vượt quỹ thời gian {hoursText(weekMinutes - plan.hours * 60)}. Bạn có thể chuyển việc sang tuần khác.</p>}
    <div className="task-list">{weekTasks.map(task => { const resource = resources.find(r => r.id === task.sourceId); const module = modules.find(m => m.id === task.moduleId); return <article className={`task-row ${task.completed ? 'completed' : ''}`} key={task.id}><label className="task-checkbox"><input type="checkbox" aria-label={`Hoàn thành: ${task.title}`} checked={task.completed} onChange={e => { patchTask({ ...task, completed: e.target.checked, completedAt: e.target.checked ? new Date().toISOString() : undefined }); toast(e.target.checked ? 'Một bước nữa đã hoàn thành 🌱' : 'Đã đánh dấu việc cần làm'); }} /><span><Check size={14} /></span></label><div className="task-content"><div className="task-topline"><span className="eyebrow">{module?.title || 'Việc của bạn'}</span><span className="task-duration">{hoursText(task.minutes)}</span></div><h3>{task.title}</h3><div className="task-bottom">{resource && <External href={resource.url}><BookOpen size={13} />{resource.provider} · Mở nguồn học</External>}{task.notes && <p className="task-notes">{task.notes}</p>}</div></div><button className="icon-button task-edit" aria-label={`Sửa: ${task.title}`} onClick={() => setEditing({ ...task })}><Pencil size={16} /></button></article>; })}</div>
    {weekTasks.length === 0 && <div className="empty-inline">Tuần này đang trống. Bạn có thể thêm một việc nhỏ.</div>}
    {weekTasks.length > 0 && weekTasks.every(t => t.completed) && <div className="week-done"><CheckCheck size={20} /><span>Tuần này đã xong. Dành một chút thời gian nhìn lại điều bạn học được.</span></div>}
    {adding ? <form className="add-task-form" onSubmit={addTask}><label>Việc muốn làm<input autoFocus maxLength={200} required value={customTitle} onChange={e => setCustomTitle(e.target.value)} placeholder="Ví dụ: Ôn lại bài về HTTP" /></label><label>Thời lượng<select value={customMinutes} onChange={e => setCustomMinutes(Number(e.target.value))}><option value={30}>30 phút</option><option value={60}>1 giờ</option><option value={90}>1.5 giờ</option><option value={120}>2 giờ</option></select></label><div className="dialog-actions"><button type="button" className="quiet-button" onClick={() => setAdding(false)}>Hủy</button><button className="primary-button" type="submit"><Plus size={15} />Thêm việc</button></div></form> : <button className="add-task-button" onClick={() => setAdding(true)}><Plus size={17} />Thêm một việc nhỏ</button>}
    <div className="week-paper-footer"><span>YOUR PACE, YOUR PROGRESS.</span><span><Check size={13} />Dữ liệu lưu trên trình duyệt này</span></div></section></div>
    <section className="plan-rhythm-summary"><div><span className="eyebrow">THIS WEEK, ONE STEP AT A TIME</span><h3>{weekTasks.filter(t => t.completed).length} / {weekTasks.length} việc đã hoàn thành trong tuần được chọn</h3><p>Nhịp học 12 tuần và hồ sơ học tập nằm tại Profile.</p></div><Link className="secondary-button" to="/profile">Xem nhịp học <ArrowRight size={16} /></Link></section>
    {state.credentials.length > 0 && <section className="saved-credentials"><div className="section-heading"><div><span className="eyebrow">FOR LATER</span><h2>Mục tiêu chứng nhận đã lưu</h2></div><Link to="/path" className="text-link">Khám phá thêm <ArrowUpRight size={16} /></Link></div><div className="saved-credential-list">{credentials.filter(c => state.credentials.includes(c.id)).map(c => <External key={c.id} href={c.url}><GraduationCap size={19} /><span>{c.name}<small>{c.type} · {c.provider}</small></span></External>)}</div></section>}
    {editing && <Dialog title="Chỉnh một bước nhỏ." eyebrow="MY PLAN" onClose={() => setEditing(null)}><form className="dialog-body task-edit-form" onSubmit={e => { e.preventDefault(); if (!editing.title.trim()) return; patchTask({ ...editing, title: editing.title.trim() }); setWeek(editing.week); setEditing(null); toast('Đã lưu thay đổi'); }}><label>Tên công việc<input required maxLength={200} value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} /></label><div className="form-row"><label>Thời lượng (phút)<input type="number" min={15} max={1200} step={15} required value={editing.minutes} onChange={e => setEditing({ ...editing, minutes: Number(e.target.value) })} /></label><label>Chuyển đến<select aria-label="Chuyển đến" value={editing.week} onChange={e => setEditing({ ...editing, week: Number(e.target.value) })}>{Array.from({ length: weekCount + 1 }, (_, i) => <option key={i} value={i}>Tuần {i + 1}{i === weekCount ? ' · Tuần mới' : ''}</option>)}</select></label></div><label>Ghi chú<textarea maxLength={1000} rows={3} placeholder="Điều muốn nhớ, khó khăn hoặc kết quả…" value={editing.notes} onChange={e => setEditing({ ...editing, notes: e.target.value })} /></label><div className="dialog-actions"><button type="button" className="secondary-button" onClick={() => setEditing(null)}>Hủy</button><button className="primary-button" type="submit">Lưu thay đổi <Check size={16} /></button></div></form></Dialog>}
  </div>;
}
